### ISSUE TITLE
Output stream is only directed to DLNA device with a pre-existent stream.

### ISSUE THREAD

**Issue by Takkat-Nebuk** [masmu/pulseaudio-dlna#10]
We can smoothly switch our output stream from any sink to any DLNA sink created by pulseaudio-dlna and back by using the Ubuntu indicator sound applet. This is awesome!

But this will not work as expected if there was no stream present at the time we started pulseaudio-dlna. 

1. We can switch our output sink to the DLNA device, it will be listed in `pacmd list-sinks`, and pulseaudio-dlna PulseWatcher recognizes switching sinks. But a newly started stream will not be directed to the DLNA sink. There is no pulseaudio sink-input.

2. Switching the output to any other sink (which could also be another DLNA device created by pulseaudio-dlna !) while playing a stream and then switching back to the desired DLNA device will make a DLNA sink-input available, streams then are as expected.

3. We stopped the stream before switching to another non-DLNA sink. Then we switched back to the DLNA sink before we again started playing any stream. This will also work with little issues only (i.e. a somewhat longer delay).

I could trace this down to `parec` which, while running pulseaudio-dlna, will only be loaded when a stream was present. It will then stay loaded (even after the stream had disappeared) to send its stream to a DLNA sink selected as output device.

It may be that this is more an issue on the pulseaudio side but still it is confusing, and it would be very nice to be able to define the DLNA device as output sink before we start audio output.

To overcome this issue I was wondering if starting `parec` with e.g. a dummy stream on selecting a DLNA sink  if there  was no active stream present could be a solution. Alternatively it would be cool to find another way to switch to a DLNA sink when there are not yet any streams ready.

**Comment by Takkat-Nebuk** [comment]
Defining a dummy stream before we start `pulseaudio_dlna.py` indeed leads to the expected results. We can now switch to the DLNA sink without the need of starting our output first.

This can be done e.g. by running from a script:

```bash
#! /bin/bash

pacat /dev/zero &  # this creates a dummy stream
python pulseaudio_dlna.py
```

The disadvantage of this approach is that this will replace any streams with the dummy stream on the default sink.

Killing `pacat` after a DLNA-sink was selected will still let us start another stream on that sink.

We could put this somewhere in the code of pulseaudio_dlna.py to 

1. establish a dummy stream on selecting a DLNA-sink before we actually switch to this sink.
2. this only should be done if there was no other stream.
3. the dummy stream can be terminated as soon as it was sent to parec for the DLNA sink.

I suspect the appropriate place would be in `pulseaudio.py` `PulseWatcher` but I am not so familiar with the code, or any other place it could sit.

**Comment by masmu** [comment]
Thank you very much for your detailed report and your efforts. :smile: 

I am currently pretty busy, but i think i tracked it down.

Could you please test this? [bug/on-stream-changes](https://github.com/masmu/pulseaudio-dlna/tree/bug/on-stream-changes)

**Comment by Takkat-Nebuk** [comment]
Wow, that's just brilliant!

Much better than creating a stupid dummy stream. Everything seems to work as expected now.

Thank you!!!

**Comment by masmu** [comment]
Merged.

_PulseAudio_ just informs you that a device (sink, stream) changed, but not what changed. So, its kind of tricky and therefore up to you to find out what actually changed. When i implemented the ```PulseWatcher``` i pretty was sure that ```on_new_playback_stream``` and ```on_playback_stream_removed``` would get pretty handy sometime :smile:.

Thanks for being so tenacious.

And I don't think your solution was stupid at all, it was a good lead to what was really going on.

 * __0.2.4__ - (_2015-01-25_)
    - Stream changes are now handled correctly (thanks to [Takkat-Nebuk](https://github.com/Takkat-Nebuk))
