### ISSUE TITLE
Make UPNP request timeout configurable

### ISSUE THREAD

**Issue by theli-ua** [masmu/pulseaudio-dlna#102]
Currently it is hardcoded inside pulseaudio_dlna/plugins/upnp/renderer.py as 10
My receiver is kinda slow and is never able to reply to PLAY command in time, thus making pulseaudio-dlna unusable, with bumping it it works fine

**Comment by masmu** [comment]
I create [a branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/request-timeout) for this. Could you test it?

**Comment by masmu** [comment]
What I forgot: If you are using a _devices.json_ you can also specify it there:

```json
    "uuid:e4572d54-c2c7-d491-1eb3-9cf17cf5fe01": {
        "rules": [
            {
                "name": "REQUEST_TIMEOUT", 
                "timeout": 20.0
            }
        ], 
        "flavour": "DLNA", 
        "name": "Device name", 
        "codecs": [
            ...
        ]
    }
```

**Comment by theli-ua** [comment]
Thanks, I'll try this when i get home today.

**Comment by chmduquesne** [comment]
Hi!

@theli-ua Could you please test this feature? The chromecast audio users are impatiently waiting for a release, and your confirmation that this works is needed for this to be included :)

Cheers!

**Comment by theli-ua** [comment]
Sorry, it works for me.

(fails to play with default, plays fine with --request-timeout=60)

**Comment by chmduquesne** [comment]
Awesome, thank you!

**Comment by masmu** [comment]
* __0.4.6__ - (_2015-10-17_)
    - Added support for _Google Chromecast Audio_ (thanks to [leonhandreke](https://github.com/leonhandreke))
    - Fixed a bug where devices which does not specifiy control urls made the application crash
    - Added the `--disable-device-stop` flag
    - Added the `--request-timeout` option
    - You can now also add rules to renderers (e.g. `DISABLE_DEVICE_STOP`, `REQUEST_TIMEOUT`)
    - Fixed a bug where stream urls where not parsed correctly
    - Fixed a bug which made a Chomecast Audio throwing exceptions while stopping
    - Fixed a bug where the system's default encoding could not be determined when piping the applications output
