### ISSUE TITLE
Low-Latency Mode

### ISSUE THREAD

**Issue by jkufner** [masmu/pulseaudio-dlna#104]
When playing music without video, pulseaudio-dlna works perfectly. But it is completely useless when latency is an issue. Even when playing movies, it is very hard to set correct delay to match sound to video.

There should be a way how to transfer sound without latency larger than few miliseconds. Pulseaudio TCP tunnel can do it, so it should be possible fot DLNA too.

**Comment by masmu** [comment]
No, imho, it is not. The delay comes from the HTTP buffer, which needs to be filled. For more on this, see the _README.md_ troubleshooting section.

The reason why _pulseaudio_'s TCP tunnel can do that is, on both ends there is _pulseaudio_ running. So, it is basically completely up to _pulseaudio_'s TCP protocol to decide to use a buffer or not.
In the case of _DLNA_ it is the manufacturers firmware which implements the buffer. And this cannot be controlled or set. _pulseaudio-dlna_ is sending the data as fast as possible, but in the end it does not really matter if the device which is receiving the data waits until it has received a certain amount of it. I am using _cocy_ on a hardware linux reciever and it does not implement a buffer at all. There is nearly zero delay with that. So, if you cannot change your devices firmware to not use a HTTP buffer there is no way around the delay.

As an alternative there would be _RTP_ as protocol. But it is not spread widely, so even if I implement it, it is pretty likely that your device does not support it. I have several _DLNA_ devices of different manufacturers and none of them is implementing this.

**Comment by masmu** [comment]
Closed due to inactivity.

**Comment by stuaxo** [comment]
Is this basically buffer bloat ?

**Comment by stuaxo** [comment]
Paradoxically I wonder if this sending slightly less often could help here, by having a slightly longer window between sending data, the devices in between might be more likely to send on the data they have.

It would be really good to come up with some semi automated test for latency, you could imagine sending a special sound from the pc, while using it's mic to pick it up + measure the end to end latency.
