### ISSUE TITLE
padlna no longer working with pulseaudio v7

### ISSUE THREAD

**Issue by nobanzai** [masmu/pulseaudio-dlna#106]
Hi,
with pulseaudio v7 padlna no longer works 8-(
I get:

10-15 12:09:50 pulseaudio_dlna.listener                       INFO     Discovery complete.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 452, in _check_message_queue
    getattr(self, message_type)(**message)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 634, in add_device
    device.short_name, device.label)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 168, in create_null_sink
    module_id = int(subprocess.check_output(cmd))
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'pactl', u'load-module', u'module-null-sink', u'sink_name="wohnzimmermajikdsmmediarenderer_dlna"', u'sink_properties=device.description="Wohnzimmer:Majik\\ DSM:MediaRenderer\\ (DLNA)"']' returned non-zero exit status -11

DBUS-Module is loaded:

Module #25
        Name: module-dbus-protocol
        Argument: 
        Usage counter: n/a
        Properties:
                module.author = "Tanu Kaskinen"
                module.description = "D-Bus interface"
                module.version = "7.0"

Bye.
Michael.

**Comment by masmu** [comment]
Hmm, the command which _pulseaudio-dlna_ executes fails. Perhaps they changed the command line? Where did you get _pulseaudio_ 7? Which distro?

**Comment by nobanzai** [comment]
It came with the latest snapshot for OpenSuSE Tumbleweed, which means, it will be part of the upcoming OpenSuSE Leap distribution.

**Comment by masmu** [comment]
I tried to install _OpenSuSE Tumbleweed_ in a VM. That failed, which should not happen nowadays any more.
So, I installed a _Ubuntu_ 15.10 wily (beta 2) in a VM and upgraded with a PPA to _pulseaudio_ 7.0.

It all worked without any issues. Seems to be distro specific thing...

**Comment by nobanzai** [comment]
They broke lots of things with the last two snapshots 8-<
I'm curious, if they could get things right before Leap 42.1 will hit the mass market.

**Comment by nobanzai** [comment]
There is a bug in pulseaudio 7. I had to modify an entry in /etc/pulse/default.pa:

load-module module-native-protocol-unix
to
load-module module-native-protocol-unix srbchannel=no

Now everything works as expected again.
