### ISSUE TITLE
Can't find Kodi Upnp

### ISSUE THREAD

**Issue by raev33** [masmu/pulseaudio-dlna#112]
I'm very glad that I found this brilliant piece of software - thank you!

But in my setup there is one annoyance: pulseaudio-dlna can't find Kodi without help. In Kodi I have to manually turn the upnp setting off and the on again, and then pulseaudio-dlna sees and connects to Kodi without further problems - until next restart. Other apps and programs have no problem finding Kodi.

For some reason pulseaudio-dlna also can't see my Chromecast (1. gen.) at all - I actually don't use it, but maybe there's a connection.

I use Ubuntu 14.04 and Kodi through OpenElec 5.0.8. And the suggested ports 8080 and 1900 are open in the firewall.

Can I give you any other information, that can help solve this?

Edit: I have now realized that pulseaudio-dlna actually does find Kodi, just with a delay of 5 minutes or so from when pulseaudio-dlna is started. I suppose this can't be considered a issue any more?

**Comment by masmu** [comment]
Could you describe your network topology? Like: There is a router, my computer is connected via cable to it. Phone connected via (weak / strong) wifi to the router. There is a switch connected to the router and to that switch there are 2 Pis connected by cable. 

What apps can find Kodi?

~~Please do one experiment: The next time it does not find _Kodi_, wait for a longer time, like 10 minutes and report what is happening.~~

**Comment by raev33** [comment]
I use a wireless router, and all devices are connected wirelessly to it. The connection is quite strong.

The strange thing is that pulseaudio-dlna instantly discover Kodi, when I switch Kodis Upnp service off and on again. Openelec use the local ip 192.168.1.13 - I've tried to tell pulseaudio-dlna this with the host command, but the result is the same.

In Windows I use Foobar2000 an Upnp extension without any issue. And on Android BubbleUpnp also works as it should.

**Comment by masmu** [comment]
Please try the following: Edit `/usr/lib/python2.7/site-packages/pulseaudio_dlna/discover.py` with your favorite editor. In line 36 you find the _MX_ value which is set to 2. Try increasing it. Perhaps to 4, 6, 8, 10.

E.g.:
```python
    MSEARCH = 'M-SEARCH * HTTP/1.1\r\n' + \
              'HOST: {}:{}\r\n'.format(SSDP_ADDRESS, SSDP_PORT) + \
              'MAN: "ssdp:discover"\r\n' + \
              'MX: 8\r\n' + \
              'ST: ssdp:all\r\n\r\n'
```

Save the file, restart _pulseaudio-dlna_ and try again.

**Comment by raev33** [comment]
There was no "site-packages/pulseaudio_dlna" sub-directory on my computer, so I created it and the discover.py file. I tried to give it the MX value of 10, but it didn't make a difference. It stills takes quite some time before Kodi is discovered.

**Comment by masmu** [comment]
Did you install via ppa? Normally that file should exist ... Creating it is not a good idea ... so please reverse your steps. After that we search for it `find / | grep -i pulseaudio_dlna`

**Comment by raev33** [comment]
I Used the PPA, but I actually use Elementary OS, but it's based on Ubuntu 14.04 - so I don't think is should make any difference?

I found the file here /usr/lib/python2.7/dist-packages/pulseaudio_dlna/discover.py

I changed the MX value from 2 to 8. But is hasn't done discovery any faster - or not noticeable faster at least.

**Comment by masmu** [comment]
Hmm, you said you are using a firewall, right? Try disabling it for testing purposes and try again a few times.

**Comment by raev33** [comment]
I didn't think that this would work, as I already had opened the specified ports (1900 upd and 8080 tcp), but after a full machine restart it did. Further more I could see my Chromecast-device.

My firewall is set to deny incoming connections. And when I open the ports I open them both ways. I can't figure out what I'm doing wrong, but it's obliviously a firewall issue.

**Comment by masmu** [comment]
Since that worked, I am pretty sure I know what's going on.

If you want to verify this, edit the _discover.py_ (same path like the file before) and add those 2 lines:
```python
sock.setsockopt(s.SOL_SOCKET, s.SO_REUSEADDR, 1)
sock.bind(('', self.SSDP_PORT))
```
It should look like that:
```python
    def search(self, ttl=10, timeout=5, times=4):
        s.setdefaulttimeout(timeout)
        sock = s.socket(s.AF_INET, s.SOCK_DGRAM, s.IPPROTO_UDP)
        sock.setsockopt(s.SOL_SOCKET, s.SO_REUSEADDR, 1)
        sock.bind(('', self.SSDP_PORT))
        sock.setsockopt(s.IPPROTO_IP, s.IP_MULTICAST_TTL, ttl)

        for i in range(0, times):
            sock.sendto(self.MSEARCH, (self.SSDP_ADDRESS, self.SSDP_PORT))
            time.sleep(0.1)

        buffer_size = 1024
        while True:
            try:
                header, address = sock.recvfrom(buffer_size)
                guess = chardet.detect(header)
                self._header_received(header.decode(guess['encoding']), address)
            except s.timeout:
                break
        sock.close()
```

**Comment by masmu** [comment]
After that, re-enable your firewall and try again.

**Comment by raev33** [comment]
That didn't work. And now Kodi (or Chromecast) isn't discovered at all...

**Comment by masmu** [comment]
Let do a little experiment:
Change the file to (Just modified the _sock.bind_ line, replaced `self.SSDP_PORT` with `9200`):
```python
    def search(self, ttl=10, timeout=5, times=4):
        s.setdefaulttimeout(timeout)
        sock = s.socket(s.AF_INET, s.SOCK_DGRAM, s.IPPROTO_UDP)
        sock.setsockopt(s.SOL_SOCKET, s.SO_REUSEADDR, 1)
        sock.bind(('', 9200))
        sock.setsockopt(s.IPPROTO_IP, s.IP_MULTICAST_TTL, ttl)

        for i in range(0, times):
            sock.sendto(self.MSEARCH, (self.SSDP_ADDRESS, self.SSDP_PORT))
            time.sleep(0.1)

        buffer_size = 1024
        while True:
            try:
                header, address = sock.recvfrom(buffer_size)
                guess = chardet.detect(header)
                self._header_received(header.decode(guess['encoding']), address)
            except s.timeout:
                break
        sock.close()
```

Please open udp/9200 in your firewall and try again.

**Comment by raev33** [comment]
That did the trick! Both Kodi and Chromecast now shows instantly on system start. Thank you!

**Comment by masmu** [comment]
Could you try to change the line back to `sock.bind(('', 1900))` and try again? Normally this should work ... And people do not need to open another port. I would like to stick to 8080/tcp and 1900/udp.

**Comment by raev33** [comment]
That doesn't seem to work for me. Neither Kodi nor Chromecast are showing up now.

**Comment by masmu** [comment]
What are you using as firewall and how did you configure it? Please give me a lot of details... trying to reconstruct your environment so that I can reproduce your error.

**Comment by masmu** [comment]
I made a new [branch](https://github.com/masmu/pulseaudio-dlna/tree/feature/ssdp-listener) to hopefully fix your issue. Could you try it out? It should also make the discovering process much faster ...

```bash
# remove the ppa based pulseaudio-dlna version
sudo apt-get remove pulseaudio-dlna

# install all dependencies (if you installed the ppa version before this should not install anything new)
sudo apt-get install python2.7 python-pip python-setuptools python-dbus python-beautifulsoup python-docopt python-requests python-setproctitle python-gobject python-protobuf python-notify2 python-psutil python-concurrent.futures python-chardet vorbis-tools sox lame flac faac opus-tools

# install dependencies necessary for python virtual env
sudo apt-get install virtualenv python-dev git

# goto some folder, e.g. your home folder
cd ~

# clone the actual code and change to that directory
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio-dlna/

# checkout the branch
git checkout feature/ssdp-listener

# make the application runnable
make

# run it
bin/pulseaudio-dlna
```

**Comment by raev33** [comment]
I've used Gufw to configure the firewall settings.

I followed your instructions, and installing all dependencies did install quite a few new packages.

For some reason there isn't a package called 'virtualenv' that I can install. Could it be named something else?

**Comment by masmu** [comment]
Depending in the ubuntu version it could also be python-virtualenv.



Am 6. November 2015 13:37:13 MEZ, schrieb raev33 <notifications@github.com>:

**Comment by raev33** [comment]
python-virtualenv worked! But when i'm running the 'make' command if getting the following output.

virtualenv --system-site-packages -p python2.7 .
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in ./bin/python2.7
Also creating executable in ./bin/python
Installing setuptools, pip...done.
bin/pip install --editable . && touch pulseaudio_dlna.egg-info
/bin/sh: 1: bin/pip: not found
make: *** [pulseaudio_dlna.egg-info] Fejl 127

When I run the last command it says that there no pulseaudio-dlna file I can run. I must be doing something wrong.

I'm only used to ppa's and not this, so sorry for the inconvinience!

**Comment by masmu** [comment]
Don't worry. I am always trying to make instructions bullet proof.
But sometimes I am missing something. :wink: 

```bash
sudo apt-get install python-pip
```

**Comment by raev33** [comment]
It says that 'python-pip' already is installed...

**Comment by masmu** [comment]
Thats odd, please do a
```bash
make clean
make bin/pip
```
and then print the contents of the `bin/` folder here.

**Comment by raev33** [comment]
In the bin folder, there's the following files:
activate      activate.fish	easy_install	  pip	pip2.7	python2
activate.csh  activate_this.py	easy_install-2.7  pip2	python	python2.7

**Comment by masmu** [comment]
Please print the output of `bin/pip -V` here.

**Comment by raev33** [comment]
Loosely translated. I get the following:

Bad intrepeter: No such file or filecatalog.

When is manually open the bin/pip file with at text editor, it looks as the following:

#!/[home directory]/pulseaudio-dlna/pulseaudio-dlna/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by masmu** [comment]
Could you paste the output of `ls -la bin/` here?

**Comment by raev33** [comment]
drwxrwxr-x  2 jakob jakob    4096 nov  6 16:14 .
drwxrwxr-x 11 jakob jakob    4096 nov  6 16:14 ..
-rw-rw-r--  1 jakob jakob    2238 nov  6 16:14 activate
-rw-rw-r--  1 jakob jakob    1294 nov  6 16:14 activate.csh
-rw-rw-r--  1 jakob jakob    2507 nov  6 16:14 activate.fish
-rw-rw-r--  1 jakob jakob    1129 nov  6 16:14 activate_this.py
-rwxrwxr-x  1 jakob jakob     288 nov  6 16:14 easy_install
-rwxrwxr-x  1 jakob jakob     288 nov  6 16:14 easy_install-2.7
-rwxrwxr-x  1 jakob jakob     260 nov  6 16:14 pip
-rwxrwxr-x  1 jakob jakob     260 nov  6 16:14 pip2
-rwxrwxr-x  1 jakob jakob     260 nov  6 16:14 pip2.7
lrwxrwxrwx  1 jakob jakob       9 nov  6 16:14 python -> python2.7
lrwxrwxrwx  1 jakob jakob       9 nov  6 16:14 python2 -> python2.7
-rwxrwxr-x  1 jakob jakob 3345416 nov  6 16:14 python2.7

**Comment by masmu** [comment]
Hmm ... looks okay. Please do a `make` ...

**Comment by raev33** [comment]
Still the same:

/bin/sh: 1: bin/pip: not found
make: *** [pulseaudio_dlna.egg-info] Fejl 127

**Comment by masmu** [comment]
I don't know what's going on ... i will build a custom package. Give me a few minutes ...

**Comment by masmu** [comment]
Do you have a instant message account? Something like _skype_?

**Comment by raev33** [comment]
I only use google hangouts. No Skype, sorry.

**Comment by masmu** [comment]
Name?

**Comment by raev33** [comment]
jakobkgroth

**Comment by masmu** [comment]
It is likely that the new version doesn't not work for you since it selects a random port as the previous one did. Use the `--msearch-port <port>` option and open `<port>`/_udp_ in your firewall. 8080/tcp and 1900/_udp_ are still required.

 * __0.4.7__ - (_2015-11-18_)
    - The application can now co-exist with other applications which are using the port 1900/udp (thanks to [klaernie](https://github.com/klaernie))
    - Fixed the daemon mode to support `psutil` 1.x and 2.x (thanks to [klaernie](https://github.com/klaernie))
    - HTML entities in device descriptions are now converted automatically
    - Faster and more reliable device discovery (new dependency `python-netifaces`)
    - Added the `--cover-mode` option, one mode requires (optional) dependencies `gtk`, `cairo`, `rsvg`
    - L16 codecs are now selected better (e.g. needed for _XBox 360_)
    - Fixed a bug where sometimes it was tried to remove sinks twice on cleanup
    - Added the `--update-device-config` flag
    - Added the `--ssdp-ttl`, `--ssdp-mx`, `--ssdp-amount` options
    - Added the `--msearch-port` option

**Comment by raev33** [comment]
Thanks for the fix! After the update it still seems to work without the new --msearch-port <port> option.
