### ISSUE TITLE
how to debug daemon mode

### ISSUE THREAD

**Issue by klaernie** [masmu/pulseaudio-dlna#113]
Is there a nice way to debug the daemon mode? I cannot get it to work, when started as root if does not detect the running pulseaudio daemon (running under my personal user).  All I get is this output:

```
kandre@mainframe(pts/3) ~ % sudo pulseaudio-dlna
11-01 01:13:12 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
11-01 01:13:12 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
```

**Comment by masmu** [comment]
Not really a specific one. But the `daemon.py` isn't that big. According to your logs I would start placing a new logger here:

```python
# line 201
class PulseAudioFinder(object):
    @staticmethod
    def get_processes():
        processes = []
        try:
            for proc in psutil.process_iter():
                logger.info(proc) # new logger
                if proc.name == 'pulseaudio':
                    proc.__class__ = PulseAudioProcess
                    if not hasattr(proc, 'application'):
                        proc.application = None
                    processes.append(proc)
        except psutil._error.NoSuchProcess:
            pass
        return processes
```

**Comment by masmu** [comment]
* __0.4.7__ - (_2015-11-18_)
    - The application can now co-exist with other applications which are using the port 1900/udp (thanks to [klaernie](https://github.com/klaernie))
    - Fixed the daemon mode to support `psutil` 1.x and 2.x (thanks to [klaernie](https://github.com/klaernie))
    - HTML entities in device descriptions are now converted automatically
    - Faster and more reliable device discovery (new dependency `python-netifaces`)
    - Added the `--cover-mode` option, one mode requires (optional) dependencies `gtk`, `cairo`, `rsvg`
    - L16 codecs are now selected better (e.g. needed for _XBox 360_)
    - Fixed a bug where sometimes it was tried to remove sinks twice on cleanup
    - Added the `--update-device-config` flag
    - Added the `--ssdp-ttl`, `--ssdp-mx`, `--ssdp-amount` options
    - Added the `--msearch-port` option
