### ISSUE TITLE
autostart pulseaudio-dlna at userlogin

### ISSUE THREAD

**Issue by fleixi** [masmu/pulseaudio-dlna#116]
I have problems autostarting "pulseaudio-dlna". I like to start the program at login of a user.

Im using Kubuntu 15.04 and 15.10. The program isnt starting after login. It doesn’t matter if i using kde-tools or x11-tools to auto start it. If i start it manual there are no problems.

**Comment by masmu** [comment]
I assume that is because _pulseaudio_ is not started at this time. It normally runs in user mode and not as system daemon. Try delaying the startup for a few seconds, like in the following script:

```bash
#!/bin/bash
sleep 5
bin/pulseaudio-dlna --debug 2>&1 | tee -a ~/"$(date +"debug_%Y-%m-%d_%H-%M-%S.log")"
```

In case it does not work it will create a _debug.log_ in your home directory.

**Comment by masmu** [comment]
Closed due to inactivity.
