### ISSUE TITLE
Apostrophes in sink names are encoded as `&#39;`

### ISSUE THREAD

**Issue by wlcx** [masmu/pulseaudio-dlna#117]
There seems to be some issues handling `'`s - this should read `Sam's Hifi` but the apostrophe is being html-encoded as `&#39;`. Or maybe it just isn't being decoded?
![2015-11-06-215744_365x96_scrot](https://cloud.githubusercontent.com/assets/3065381/11009789/a8c36c08-84d1-11e5-84aa-5eea27802a4c.png)

**Comment by masmu** [comment]
Hey, could you please provide a full _debug.log_ and pastebin it here?
```bash
bin/pulseaudio-dlna --debug 2>&1 | tee -a
```

**Comment by wlcx** [comment]
@masmu Do you still want debug logs? This seems to be a chromecast thing, I have opened a PR with a fix, please critique as necessary!

**Comment by masmu** [comment]
Yes please. I am currently working on bug in the same direction. Cannot hurt to check that twice.

**Comment by masmu** [comment]
* __0.4.7__ - (_2015-11-18_)
    - The application can now co-exist with other applications which are using the port 1900/udp (thanks to [klaernie](https://github.com/klaernie))
    - Fixed the daemon mode to support `psutil` 1.x and 2.x (thanks to [klaernie](https://github.com/klaernie))
    - HTML entities in device descriptions are now converted automatically
    - Faster and more reliable device discovery (new dependency `python-netifaces`)
    - Added the `--cover-mode` option, one mode requires (optional) dependencies `gtk`, `cairo`, `rsvg`
    - L16 codecs are now selected better (e.g. needed for _XBox 360_)
    - Fixed a bug where sometimes it was tried to remove sinks twice on cleanup
    - Added the `--update-device-config` flag
    - Added the `--ssdp-ttl`, `--ssdp-mx`, `--ssdp-amount` options
    - Added the `--msearch-port` option
