### ISSUE TITLE
Lubuntu ARM not working

### ISSUE THREAD

**Issue by freggel2401** [masmu/pulseaudio-dlna#13]
Hello,
First of all: This is a great piece of software. I installed it on my Ubuntu 12.10 and it works like a charm, but I ran into trouble on Lubuntu ARM. I get  an DBUS error which is very bad vor me as the target machine was the Lubuntu ARM and the Ubuntu 12.10 was just for testing :)
What I have tried so far is:

- installation of all packages listed by pulseaudio-dlna
- loading dbus module (I checked it.)

"pacmd list-modules" brings up:

index: 23
	name: <module-dbus-protocol>
	argument: <>
	used: -1
	load once: yes
	properties:
		module.author = "Tanu Kaskinen"
		module.description = "D-Bus interface"
		module.version = "4.0"

- so I would expect that dbus is running. I also tried to start pulseaudio again which states that already an instance is running.

-next I ran your script which seems to find all my dlna renderer:
./pulseaudio_dlna.py -p 1234 --debug

result:
...
Failure: Module initialization failed
ERROR:root:PulseAudio seems not to be running or pulseaudio dbus module could not be loaded.

I also started in parallel the dbus-monitor wondering if something happens there, but no message was received. I have no idea where to search for the issue. Any hint to solve to problem would be great. Thanks in advance. I would really like to get it up an running on my odroid. This was the only solution on the internet so far which totally met my needs :)

best
freggel

**Comment by masmu** [comment]
I am really sorry. I have no idea what is going on.
You are right, the module should be loaded.

Perhaps there are not all dependencies installed. To make sure you did, install the latest version from the new PPA and try again.
