### ISSUE TITLE
Support in-hardware volume/mute

### ISSUE THREAD

**Issue by leonhandreke** [masmu/pulseaudio-dlna#130]
I'm using a Chromecast Audio. Chromecasts seem to have built-in volume adjustment that is also sticky. So if I e.g. used my Android phone to adjust the volume of the Spotify app playing on the Chromecast, pulseaudio-dlna will keep playing on the Chromecast at that volume.

Looking at the code, adjusting the volume of the Chromecast based on changing volume in PulseAudio looks pretty easy, but the reverse looks a bit more difficult (because the `BaseRenderer` doesn't seem to have a reference to a `PulseBridge` that it may be attached to. I've actually got a patch ready that implements this one-way (but would have to clean it up).

Would you accept a patch that does this or do you think this is too messy/out of scope for pulseaudio-dlna?

**Comment by masmu** [comment]
Actually I don't know, but I am always open to new things. Sometimes you have to try things before judging them. See how they feel. I think that is the case here. Let me play with it. I'll let you know ...
