### ISSUE TITLE
Surround sound

### ISSUE THREAD

**Issue by Yannik** [masmu/pulseaudio-dlna#135]
Hi,
when streaming to AV-Receivers with a 5.1 or 7.1 (or similar) speaker setup, is it possible to actually stream 5.1 audio? At the moment, all I stream is downmixed to stereo. 
AFAIK wav files can contain 5.1 audio, but the pulseaudio configuration gui does not allow me to select a corresponding surround profile.

I could not find a previous question about this in the issues or in the README.

**Comment by masmu** [comment]
The application basically records the sound of _pulseaudio_, pushes the data through an encoder and serves this as an HTTP stream for the devices in your network. _pulseaudio_ it self is capable of handling 5.1 audio. I guess if you adjust some encoder flags this might work. You can try to adjust this yourself in editing the _encoders.py_. Regarding the DLNA devices, you might adjust some HTTP headers too, but this hardly depends on your manufacturers firmware implementation.

**Comment by masmu** [comment]
Closed due to inactivity.
