### ISSUE TITLE
Can't start v.0.4.7 on Debian Stretch

### ISSUE THREAD

**Issue by iacchi** [masmu/pulseaudio-dlna#140]
Hi,
I've just compiled this nice program on my Debian Stretch. pulseaudio dbus module is loaded as far as I can tell, if I launch the device configuration parameter pulseaudio-dlna nicely finds my chromecast and configure it. However, if I just launch the program without any parameters (which, if I understood correctly, is the way to launch it to be used), I get this error:

 iacopo@pensieroprofondo:~$ pulseaudio-dlna 
12-25 13:30:58 pulseaudio_dlna.application                    INFO     Using version: 0.4.7
12-25 13:30:58 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.1.24:8080
12-25 13:30:58 pulseaudio_dlna.application                    INFO     Loaded device config "/home/iacopo/.local/share/pulseaudio-dlna/devices.json"
12-25 13:30:58 pulseaudio_dlna.application                    INFO     Encoder settings:
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <AacEncoder available="True" bit-rate="192">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <FlacEncoder available="True">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <L16Encoder available="True" sample-rate="44100" channels="2">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <LameEncoder available="True" bit-rate="192">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <OggEncoder available="True" bit-rate="192">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <OpusEncoder available="True" bit-rate="192">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <WavEncoder available="True">
12-25 13:30:58 pulseaudio_dlna.application                    INFO     Codec settings:
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav">
12-25 13:30:58 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg">
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pulseaudio_dlna/listener.py", line 87, in run
    self, ('', self.SSDP_PORT), SSDPRequestHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Furthermore, just to check if I understood correctly: if the program launches fine, and I open pavucontrol, I should find a new sink in the output tab, correct?

**Comment by iacchi** [comment]
Quick update: if I launch e.g. VLC while pulseaudio-dlna is opened in a console windows with the [Errno 98] as last line, these new info appear in console:

12-25 13:42:28 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream9"
12-25 13:42:29 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink1
12-25 13:42:29 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink1 finished!

so maybe it is working (although the error needs to be solved I guess), but still no new device appears in pavucontrol to redirect the audio output.

**Comment by masmu** [comment]
You are right about the new sink for your Chromecast. As a first check, please try running the application again with the --disable-ssdp-listener flag.

**Comment by iacchi** [comment]
Yes, it works this way, thanks!

**Comment by masmu** [comment]
The discovery will just work at the application startup with that flag. My assumption is that there must be a application binding to port 1900/tcp and therefore pulseaudio-dlna cannot use that port. If you want to get rid of that flag find out which application uses that port and disable it.

Am 25. Dezember 2015 11:32:16 MEZ, schrieb iacchi <notifications@github.com>:
