### ISSUE TITLE
pulseaudi-dlna doesnt find device (NP2500)

### ISSUE THREAD

**Issue by noise69** [masmu/pulseaudio-dlna#142]
For a long time I searched for a solution to transfer music from my computer to other UPND/DLNA-Renderer and found pulseaudio-dlna, wich worked. 
I have two Renderer in my network  (Philips NP2500 + MK809), but pulseaudio doesn't find NP2500 anymore. 
Nothing in the network was changed. Other UPNP-programms (e.g. Upplay under Linux and all iOS-Apps) find the NP2500 without any problems.

I'm using Linux Mint 17 and pulseaudio-dlna version 0.4.7.

Can someone tell me where the problem is, or how I can access it directly via pulseaudio-dlna --renderer-urls (IP 192.168.178.100).

**Comment by Chaos2000** [comment]
Hi noise69,
try pulseaudio-dlna 0.3.5, this works with Philips MCi500H and MCi298. I tried it with the new version 0.4.7 but MCi298 couldn't start, the MCi500H wasn't detected, so I changed back to 0.3.5 which you will find here
https://launchpad.net/~qos/+archive/ubuntu/pulseaudio-dlna/+p
Hope this helps

**Comment by Chaos2000** [comment]
Hi noise69,
sorry, the link does not work, this one should:
https://launchpad.net/~qos/+archive/ubuntu/pulseaudio-dlna/
Afterwards push "View package details"
KR

**Comment by noise69** [comment]
Hi Chaos2000,
thanks for the hint, I've done the downgrade to 0.3.5 and all devices are found without problem! 
Thank you very much!
