### ISSUE TITLE
rygel renderer not recognized

### ISSUE THREAD

**Issue by tmalch** [masmu/pulseaudio-dlna#147]
Hello,
v0.4.7 doesn't recognize the media renderer provided by rygel v0.20.3
I was able to get it working by changing the attribute st_header of class DLNAPlugin
``` python
--- self.st_header = 'urn:schemas-upnp-org:device:MediaRenderer:1'
+++ self.st_header = 'urn:schemas-upnp-org:device:MediaRenderer:2'
```
Additionally, in the rygel config file, I had to enable the option `force-downgrade-for=python;`
This downgrades the UPnP device version if the field User-Agent contains `python` which is the case for pulseaudio-dlna.

Hope this helps to add compatibility to rygel

**Comment by masmu** [comment]
Hey, thanks a lot for that. Why is it necessary to downgrade the UPnP device version?

**Comment by tmalch** [comment]
I can only tell that the downgrade changes the version in the xml device description (see debug output).
Without downgrade Rygel uses eg `MediaRenderer:2`, with downgrade `MediaRenderer:1`. 

pulseaudio-dlna --debug (the interesting part):
[rygel_without_downgrade.txt](https://github.com/masmu/pulseaudio-dlna/files/80099/rygel_without_downgrade.txt) vs. [rygel_with_downgrade.txt](https://github.com/masmu/pulseaudio-dlna/files/80100/rygel_with_downgrade.txt)

Also I should mention that changing st_header breaks compatibility with Kodi, I had to add the DLNAPlugin a second time (with st_header='...MediaRenderer:2') to the PLUGIN list to get it working for both.

**Comment by masmu** [comment]
So, accepting `MediaRenderer:1` and `MediaRenderer:2` should do the job? Both would be accepted and we would not break _Kodi_, correct?

**Comment by masmu** [comment]
Could you try that [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/support-media-renderers-2)? It contains a fix to work with rygel without any modifications needed. Did not use the `force-downgrade-for=python;` flag.

**Comment by tmalch** [comment]
yes this works perfectly with and without downgrade
