### ISSUE TITLE
Streaming unstable in opensuse 42.1

### ISSUE THREAD

**Issue by DrAxelbauer** [masmu/pulseaudio-dlna#151]
Hi!
At first....Thanks (again) for this horrible cool app ;) This might be another step to overcome the dark power of proprietary energy.

Anyway i have a question:
I use my raspberry (gmrenderer on rasbian) as the renderer. I have two devices, which are streaming to the raspberry: One opensuse machine with pulseaudio-dlna and a android phone with bubbleupnp.

Recently i encountered, that with bubbleupnp streaming music to the raspi is very stable. But when i use my laptop with pulseaudio-dlna i am often "kicked out" and have to restart the stream in pavucontrol. This happens especially when i use clementine. I also tried different files (mp3s, wavs and other high quality formats) but this didn't change the problem.

Here is the command i use:
pulseaudio-dlna --renderer-urls='http://192.168.0.22:49152' --encoder wav

Is there anything at the moment I can do about this?

Best, Benjamin.

System: Opensuse 42.1 Leap
KDE Plasma: 5.4.3
Qt: 5.5.1
Kernel: 4.3.0-2-default
pulseaudio-dlna: 0.4.7

**Comment by masmu** [comment]
Why do you use the `--renderer-urls` flag? Does the discovery of the devices not work?

Could you create a full _debug.log_ and link it here?

```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by DrAxelbauer** [comment]
Hi!
I used the --renderer-urls flag because it didn work in the past… i tried the normal

`pulseaudio-dlna`

which is also workin.

[debug.txt](https://github.com/masmu/pulseaudio-dlna/files/93592/debug.txt)

**Comment by masmu** [comment]
Could you try the `--disable-device-stop` flag and try again?

**Comment by DrAxelbauer** [comment]
Okay i have been streaming for about 1h and it seems to work with the flag…I will let know, if there are occuring any problems… Thanks for the solution…Have a nice day (and a beer)!

**Comment by DrAxelbauer** [comment]
Actually i when streamíng with low quality music, the problem still occurs. I tried it again without the flag and it seems to work better, but still i get kicked out about three times a movie…Any hints?

**Comment by masmu** [comment]
How fast is the computer _pulseaudio-dlna_ is running on?
Could you tell me a little bit about your network? Like: computer and Pi connected via wifi or cable.

You could do the following for testing purposes:
Start _pavucontrol_ and goto the _playback_ tab:
If you play a file with _clementine_ there should be a stream for it.
If _clementine_ finishes playing, e.g.: between 2 tracks, does the stream stay there or is it gonna be removed and re-added? If it is re-added, try to guess how long does it take for _clementine_ to re-add the stream?

You could test my guess with the following modification:
In _pulseaudio.py_ (`/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py`) line ~657 you will find the following block: Try to increase the 1000 to 5000 and try again.
```python
    def _delayed_handle_sink_update(self, sink_path):
        if self.signal_timers.get(sink_path, None):
            gobject.source_remove(self.signal_timers[sink_path])
        self.signal_timers[sink_path] = gobject.timeout_add(
            1000, self._handle_sink_update, sink_path)
```
This will increase the time where _pulseaudio-dlna_ will wait for players to re-add streams to existing sinks.

**Comment by DrAxelbauer** [comment]
Hi! 
Hmm with regard to my setup: the Computer is connect via wifi to the router. The pi is connected via cable to the Router. The pi has gmediarenderer running. 

Wirth regard to pulseaudio: 
Every new song which is starting to play starts a new stream in pavucontrol (which is happening very quick without delay). I will try your script but i am not sure if this is the right place to search... The streaming is mainly crashing while a certain file is playing and not when a new file is starting to play. And....this happens not only within Clementine but also Wirth smplayer whenni stream a DVD movie for example.

Thänks:

**Comment by masmu** [comment]
Well, I just released 0.5.0 and there is a new flag `--auto-reconnect`. I know this may not solve the issue but you don't have to switch back the stream every time yourself. Perhaps the new version also increases stability. Keep me posted!

**Comment by DrAxelbauer** [comment]
Cool…i will give it a try asap...

**Comment by DrAxelbauer** [comment]
Okay i did some experiments with the new version…I tried the --disable-device-stop and the --auto-reconnect flags but it didn't change the problem…still there seems to be the problem… I will explain some stuff:
Interestingly, when i start a stream it works in the beginning and the sound is coming out like a charm. After some time (sometimes 30 secs, sometimes 10min etc… quite randomly) the stream is not hearable anymore but the stream is still connected to the dlna-device (what i can see in the pavu). So pulseaudio-dlna and pulseaudio is still "processing" the stream and it seems that it is working from this side, but the stream is not coming out of hifi…Might it be the case, that there is something rotten on the side of the renderer (gmediarenderer on a raspberry pi). That the renderer is maybe not correctly grasping up the stream? 
I have created a new debud.log

[debug.txt](https://github.com/masmu/pulseaudio-dlna/files/170952/debug.txt)

**Comment by DrAxelbauer** [comment]
Hmmm i tried to follow streaming with the following commands:
<pulseaudio-dlna --debug 2>&1 | tee -a /dev/stdout.log>
…to monitor pulseaudio-dlna and to monitor gmediarenderer:
<gmediarender --logfile=/dev/stdout>

When the stream stops none of these show any changes in the logfile…What else might there be wrong? Insofar that everything works fine with bubbleupnp i conclude, that the router, raspi and gmediarenderer is working correctly…And lets add pulseaudio-dlna insofar as there is nothing showing up in while the log is running…I guess it must have to do with my system on the laptop (Opensuse)...Maybe pulseaudio? Any hints…Do you think my conclusion is wrong?

**Comment by masmu** [comment]
I took a look at your debug.log. Your stream did not collapse and your device should receive the stream data. Otherwise there would be a `Unregistered stream` line in the log, which always is printed as soon as the HTTP connection fails.
```
03-13 12:51:18 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Raspberry (DLNA)".
03-13 12:51:18 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink9"
03-13 12:51:18 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:19 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink9
03-13 12:51:19 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Raspberry (DLNA)" to play ...
03-13 12:51:19 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:19 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:20 pulseaudio_dlna.plugins.upnp.renderer          DEBUG    sending GET_TRANSPORT_INFO to http://192.168.0.22:49494/upnp/control/rendertransport1:
03-13 12:51:20 pulseaudio_dlna.plugins.upnp.renderer          INFO     Device state is stopped. Sending play command.
03-13 12:51:20 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:20 pulseaudio_dlna.pulseaudio                     INFO     The device "Raspberry (DLNA)" is playing.
03-13 12:51:20 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink9 finished!
03-13 12:51:20 pulseaudio_dlna.streamserver                   INFO     URL settings: /dWRuPSJ1dWlkOmRjYmVmZjM4ZmVlNzkzOTJiY2U1NTdlNjg4YTY5OTZjIix0eXBlPSJicmlkZ2Ui/stream.mp3 (udn="uuid:dcbeff38fee79392bce557e688a6996c",type="bridge")
03-13 12:51:20 pulseaudio_dlna.streamserver                   INFO     Registered stream "/dWRuPSJ1dWlkOmRjYmVmZjM4ZmVlNzkzOTJiY2U1NTdlNjg4YTY5OTZjIix0eXBlPSJicmlkZ2Ui/stream.mp3" (0x7f4ab7513250) ...
03-13 12:51:20 pulseaudio_dlna.streamserver                   INFO     Starting processes "parec --format=s16le -d raspberry_dlna.monitor | lame -b 192 -r -"
03-13 12:51:20 pulseaudio_dlna.streamserver                   INFO     Processes of /dWRuPSJ1dWlkOmRjYmVmZjM4ZmVlNzkzOTJiY2U1NTdlNjg4YTY5OTZjIix0eXBlPSJicmlkZ2Ui/stream.mp3 initialized ...
03-13 12:51:38 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:38 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:58 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:51:58 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:52:18 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
03-13 12:52:18 requests.packages.urllib3.connectionpool       INFO     Starting new HTTP connection (1): 192.168.0.22
```
So, I can only assume that _pulseaudio-dlna_ is doing its job. 

Why are you writing your log to `/dev/stdout.log`? Are you even allowed to write there?

**Comment by DrAxelbauer** [comment]
I was writing the log to the terminal because i wanted to monitor pulseaudio-dlna working in process and then take a look when the stream is breaking up…But i don´t think, that the problem has something to do with it…Any ideas?

**Comment by masmu** [comment]
I was referring to that, because I doubt that you can write your logfile there. Normally this directory is only writeable with root permissions. Did you try writing to the home folder of the user _pulseaudio-dlna_ is currently running? It would make totally sense if your log is empty when trying to write the log at that location.

**Comment by DrAxelbauer** [comment]
AS far as i see this file has user permission and not roor (altough many of the others do have root perm and also the /dev…) …

**Comment by masmu** [comment]
Whats about the _dev_ folder itself? Mine has `drwxr-xr-x 21 root root 5020 Apr  1 10:41 /dev` and I am not allowed to write there ...

**Comment by DrAxelbauer** [comment]
Same here…
drwxr-xr-x  20 root root 4000  1. Apr 12:12 dev

**Comment by masmu** [comment]
I guess you are not running _pulseaudio-dlna_ as root. Please use your home folder and write a new debug.log, just to make sure we get a fresh and actual one.

```bash
 pulseaudio-dlna --debug 2>&1 | tee -a ~/debug.log
```

**Comment by DrAxelbauer** [comment]
nono man i won´t ever run such a program as root ;) I am not an expert on linux but an advanced user ;)
As far as I understand it stdout is a specific file to catch the streams of the program…I guess the output was right…
cs. [https://bash.cyberciti.biz/guide//dev/stdout]

**Comment by masmu** [comment]
If you run `pulseaudio-dlna --debug` all output will go to _stdout_ automatically. _tee_ copies the output and 1) displays it to stdout and 2) writes a copy to another location (your /dev/stdout). So, you specified basically the same location. _tee_ is used here so that you can see the output **and** write it to a log file at the same time. Thats why you should run:
```bash
 pulseaudio-dlna --debug 2>&1 | tee -a ~/debug.log
```

**Comment by DrAxelbauer** [comment]
Ahh okay understand…Ähm but there seems to be no change since the last debug.txt i posted above…

**Comment by masmu** [comment]
I really would like to help you more, but it seems as there is no disconnect and data is transmitted. So there is currently no point for me to start a diagnose.
