### ISSUE TITLE
Error : "PulseAudio seems not to be running or PulseAudio dbus module could not be loaded."

### ISSUE THREAD

**Issue by zobi8225** [masmu/pulseaudio-dlna#156]
Hi, pulseaudio looks working, but pulseaudio-dlna say it don't work  :-(

```
$ pulseaudio --check && echo "works"
works
$ uname -a
Linux vitriol 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux

```

Logs in userland  :
http://pastebin.com/XSUbxMra

Logs in root :
http://pastebin.com/h7Gx8HZ1

Any idea ?

(Sorry for my bad english)

**Comment by zobi8225** [comment]
[Castnow](https://github.com/xat/castnow) works without problems...

**Comment by zobi8225** [comment]
Ok, i don't understand how and why, but after restart my computer maytime, it's working...

**Comment by masmu** [comment]
What I can see from the logs you _pulseaudio_ had an error while loading a module... Perhaps it was not installed?
