### ISSUE TITLE
Mumble dependency error

### ISSUE THREAD

**Issue by olehj** [masmu/pulseaudio-dlna#158]
Installing pulseaudio-dlna will remove mumble (ubuntu repo)

**Comment by masmu** [comment]
Cannot confirm this. Deinstalled _pulseaudio-dlna_, installed mumble and re-installed _pulseaudio-dlna_. No problems.

**Comment by olehj** [comment]
Well, I tried even to install it, and then reinstall mumble. Got dependency error. I dunno if the error might be caused by something else or not.

`ole@superpropell:~$ sudo apt-get install pulseaudio-dlna
[sudo] password for ole: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libavahi-compat-libdnssd1 libg15daemon-client1 libmircommon3
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libjs-sphinxdoc libprotobuf9v5 opus-tools python-beautifulsoup python-concurrent.futures python-docopt python-ndg-httpsclient python-netifaces
  python-notify2 python-protobuf python-requests python-setproctitle python-setuptools python-urllib3
Suggested packages:
  python-rsvg python-setuptools-doc python-ntlm
The following packages will be REMOVED
  libmirclient8 libmirprotobuf0 libprotobuf9 mir-client-platform-mesa2 mumble
The following NEW packages will be installed
  libjs-sphinxdoc libprotobuf9v5 opus-tools pulseaudio-dlna python-beautifulsoup python-concurrent.futures python-docopt python-ndg-httpsclient
  python-netifaces python-notify2 python-protobuf python-requests python-setproctitle python-setuptools python-urllib3
0 to upgrade, 15 to newly install, 5 to remove and 3 not to upgrade.
Need to get 1 533 kB of archives.
After this operation, 3 390 kB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://no.archive.ubuntu.com/ubuntu/ wily/main libjs-sphinxdoc all 1.2.3+dfsg-1ubuntu3 [42,9 kB]
Get:2 http://ppa.launchpad.net/qos/pulseaudio-dlna/ubuntu/ wily/main pulseaudio-dlna all 0.4.7 [553 kB]
Get:3 http://no.archive.ubuntu.com/ubuntu/ wily/main libprotobuf9v5 amd64 2.6.1-1.2 [326 kB]
Get:4 http://no.archive.ubuntu.com/ubuntu/ wily/universe opus-tools amd64 0.1.9-1 [73,8 kB]
Get:5 http://no.archive.ubuntu.com/ubuntu/ wily/main python-setuptools all 18.4-1 [171 kB]
Get:6 http://no.archive.ubuntu.com/ubuntu/ wily/universe python-beautifulsoup all 3.2.1-1 [34,6 kB]
Get:7 http://no.archive.ubuntu.com/ubuntu/ wily/universe python-docopt all 0.6.2-1build1 [25,6 kB]
Get:8 http://no.archive.ubuntu.com/ubuntu/ wily/main python-urllib3 all 1.11-1 [56,2 kB]
Get:9 http://no.archive.ubuntu.com/ubuntu/ wily/main python-requests all 2.7.0-3 [53,8 kB]
Get:10 http://no.archive.ubuntu.com/ubuntu/ wily/universe python-setproctitle amd64 1.1.8-1build1 [13,8 kB]
Get:11 http://no.archive.ubuntu.com/ubuntu/ wily/universe python-protobuf amd64 2.6.1-1.2 [98,5 kB]
Get:12 http://no.archive.ubuntu.com/ubuntu/ wily/universe python-notify2 all 0.3-3 [10,5 kB]
Get:13 http://no.archive.ubuntu.com/ubuntu/ wily/main python-concurrent.futures all 3.0.3-1 [31,2 kB]
Get:14 http://no.archive.ubuntu.com/ubuntu/ wily/main python-netifaces amd64 0.10.4-0.1build1 [16,8 kB]
Get:15 http://no.archive.ubuntu.com/ubuntu/ wily/main python-ndg-httpsclient all 0.4.0-1 [24,9 kB]
Fetched 1 533 kB in 0s (2 639 kB/s)                                                      
(Reading database ... 571158 files and directories currently installed.)
Removing mumble (1.2.12-1~ppa3~vivid1) ...
Removing mir-client-platform-mesa2:amd64 (0.12.1+15.04.20150324-0ubuntu1) ...
Removing libmirclient8:amd64 (0.12.1+15.04.20150324-0ubuntu1) ...
Removing libmirprotobuf0:amd64 (0.12.1+15.04.20150324-0ubuntu1) ...
Removing libprotobuf9:amd64 (2.6.1-1) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for menu (2.1.47ubuntu1) ...
Processing triggers for gconf2 (3.2.6-3ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for libc-bin (2.21-0ubuntu4) ...
/sbin/ldconfig.real: /usr/lib/libjspAixPpc.so is not an ELF file - it has the wrong magic bytes at the start.

/sbin/ldconfig.real: /usr/lib/libjspTru64Alpha.so is not an ELF file - it has the wrong magic bytes at the start.

Selecting previously unselected package libjs-sphinxdoc.
(Reading database ... 571113 files and directories currently installed.)
Preparing to unpack .../libjs-sphinxdoc_1.2.3+dfsg-1ubuntu3_all.deb ...
Unpacking libjs-sphinxdoc (1.2.3+dfsg-1ubuntu3) ...
Selecting previously unselected package libprotobuf9v5:amd64.
Preparing to unpack .../libprotobuf9v5_2.6.1-1.2_amd64.deb ...
Unpacking libprotobuf9v5:amd64 (2.6.1-1.2) ...
Selecting previously unselected package opus-tools.
Preparing to unpack .../opus-tools_0.1.9-1_amd64.deb ...
Unpacking opus-tools (0.1.9-1) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_18.4-1_all.deb ...
Unpacking python-setuptools (18.4-1) ...
Selecting previously unselected package python-beautifulsoup.
Preparing to unpack .../python-beautifulsoup_3.2.1-1_all.deb ...
Unpacking python-beautifulsoup (3.2.1-1) ...
Selecting previously unselected package python-docopt.
Preparing to unpack .../python-docopt_0.6.2-1build1_all.deb ...
Unpacking python-docopt (0.6.2-1build1) ...
Selecting previously unselected package python-urllib3.
Preparing to unpack .../python-urllib3_1.11-1_all.deb ...
Unpacking python-urllib3 (1.11-1) ...
Selecting previously unselected package python-requests.
Preparing to unpack .../python-requests_2.7.0-3_all.deb ...
Unpacking python-requests (2.7.0-3) ...
Selecting previously unselected package python-setproctitle.
Preparing to unpack .../python-setproctitle_1.1.8-1build1_amd64.deb ...
Unpacking python-setproctitle (1.1.8-1build1) ...
Selecting previously unselected package python-protobuf.
Preparing to unpack .../python-protobuf_2.6.1-1.2_amd64.deb ...
Unpacking python-protobuf (2.6.1-1.2) ...
Selecting previously unselected package python-notify2.
Preparing to unpack .../python-notify2_0.3-3_all.deb ...
Unpacking python-notify2 (0.3-3) ...
Selecting previously unselected package python-concurrent.futures.
Preparing to unpack .../python-concurrent.futures_3.0.3-1_all.deb ...
Unpacking python-concurrent.futures (3.0.3-1) ...
Selecting previously unselected package python-netifaces.
Preparing to unpack .../python-netifaces_0.10.4-0.1build1_amd64.deb ...
Unpacking python-netifaces (0.10.4-0.1build1) ...
Selecting previously unselected package pulseaudio-dlna.
Preparing to unpack .../pulseaudio-dlna_0.4.7_all.deb ...
Unpacking pulseaudio-dlna (0.4.7) ...
Selecting previously unselected package python-ndg-httpsclient.
Preparing to unpack .../python-ndg-httpsclient_0.4.0-1_all.deb ...
Unpacking python-ndg-httpsclient (0.4.0-1) ...
Processing triggers for man-db (2.7.4-1) ...
Setting up libjs-sphinxdoc (1.2.3+dfsg-1ubuntu3) ...
Setting up libprotobuf9v5:amd64 (2.6.1-1.2) ...
Setting up opus-tools (0.1.9-1) ...
Setting up python-setuptools (18.4-1) ...
Setting up python-beautifulsoup (3.2.1-1) ...
Setting up python-docopt (0.6.2-1build1) ...
Setting up python-urllib3 (1.11-1) ...
Setting up python-requests (2.7.0-3) ...
Setting up python-setproctitle (1.1.8-1build1) ...
Setting up python-protobuf (2.6.1-1.2) ...
Setting up python-notify2 (0.3-3) ...
Setting up python-concurrent.futures (3.0.3-1) ...
Setting up python-netifaces (0.10.4-0.1build1) ...
Setting up pulseaudio-dlna (0.4.7) ...
Setting up python-ndg-httpsclient (0.4.0-1) ...
Processing triggers for libc-bin (2.21-0ubuntu4) ...
/sbin/ldconfig.real: /usr/lib/libjspAixPpc.so is not an ELF file - it has the wrong magic bytes at the start.

/sbin/ldconfig.real: /usr/lib/libjspTru64Alpha.so is not an ELF file - it has the wrong magic bytes at the start.

ole@superpropell:~$ sudo apt-get install mumble
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 mumble : Depends: libprotobuf9 but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Comment by olehj** [comment]
This can be closed.
