### ISSUE TITLE
Autostarting Pulseaudio-(dlna)

### ISSUE THREAD

**Issue by far3ll** [masmu/pulseaudio-dlna#159]
First of all, thank you for your great work.
I'm using a Raspberry Pi B+ with archlinux ARM running on it. Everything works perfekt (I'm streaming to a Denon AVR X4000 via Cmus) as long as I am starting pulseaudio-dlna manually as user. My goal would be to start both pulseaudio and pulseaudio-dlna during the startup of the pi since I'm planning to control my music from a website controlling my pi.
So here are my self-made systemd autostart-configs for pulseaudio:
```
[Unit]
Description=PulseAudio Daemon
Requires=sound.target dbus.service
After=sound.target dbus.service

[Service]
User=pulse
Type=simple
PrivateTmp=true
#ExecStart=/usr/bin/pulseaudio -D --realtime --disallow-exit
ExecStart=/usr/bin/pulseaudio --system --realtime --disallow-exit --disallow-module-loading

[Install]
WantedBy=multi-user.target
```
(tested both different ExecStarts with and without User)
and for pulseaudio-dlna:
```
[Unit]
Description=Pulseaudio DLNA
Requires=sound.target network.target dbus.service pulseaudio.service
After=sound.target network.target dbus.service pulseaudio.service

[Service]
User=pulse
ExecStart=/opt/pulseaudio-dlna/bin/pulseaudio-dlna

[Install]
WantedBy=multi-user.target
```
but after every systemstart, PA-dlna tells me
> PulseAudio seems not to be running or PulseAudio dbus module could not be loaded.

Do you have any suggestions regarding my problem?

**Comment by klaernie** [comment]
Does your pulseaudio system config load the dbus module?

**Comment by far3ll** [comment]
Yes it does, but I have to call ExecStart with `--disallow-module-loading` (so this means, dbus-module is useless?), otherwise PA does not start at all.
Without the `--system`-flag, PA nearly gets instantly killed and does not get resurrected by PA-dlna.

**Comment by klaernie** [comment]
no, `--disallow-module-loading` only prevents PA to load modules dynamically, so it is able to load them during the startup phase from the config files, but as soon as it accepts connections from the outside it is prohibited, so this shared PA setup can't be modified by one user for all possible users.

I am also currently running some tests to see how it works with my setup (PA running as my user, pa-dlna as root in daemon mode).

**Comment by far3ll** [comment]
Thanks for clarification!
When running PA as system-service, `pacmd` tells me there's no service running (even with sudo) but I can see the process via `htop`.
PA-dlna starting without `User` fails instantly with:

> Started Pulseaudio DLNA.
> pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon
> pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ..
> pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (157)
> pulseaudio_dlna.daemon                         INFO     Attaching application to pulseau
> Traceback (most recent call last):
> File "/opt/pulseaudio-dlna/bin/pulseaudio-dlna", line 9, in <module>
> load_entry_point('pulseaudio-dlna', 'console_scripts', 'pulseaudio-dlna')()
> File "/opt/pulseaudio-dlna/pulseaudio_dlna/__main__.py", line 134, in main
> daemon = pulseaudio_dlna.daemon.Daemon()
> File "/opt/pulseaudio-dlna/pulseaudio_dlna/daemon.py", line 46, in __init__
> self._check_processes()
> File "/opt/pulseaudio-dlna/pulseaudio_dlna/daemon.py", line 90, in _check_processes
> proc.attach()
> File "/opt/pulseaudio-dlna/pulseaudio_dlna/daemon.py", line 159, in attach
> compressed_env[k] = proc_env[k]
> KeyError: u'DISPLAY'
> pulseaudio-dlna.service: Main process exited, code=exited, status=1/FAILURE
> pulseaudio-dlna.service: Unit entered failed state.
> pulseaudio-dlna.service: Failed with result 'exit-code'.

**Comment by masmu** [comment]
In my tests, I needed environments _DISPLAY_  variable. But you can try it without or make sure it is set. 

Edit `daemon.py` line 151 and remove it from the list.

**Comment by klaernie** [comment]
On my debian install I didn't need `$DISPLAY` in daemon mode. But my first trials failed as I had multiple users logged in. In this case it failed to attach to both instances.

This is the systemd config I used with the debian package installed:
```
[Unit]
Description=Pulseaudio DLNA
Requires=sound.target network.target dbus.service
After=sound.target network.target dbus.service

[Service]
User=root
ExecStart=/usr/bin/pulseaudio-dlna

[Install]
WantedBy=multi-user.target
```

**Comment by masmu** [comment]
Ok, I will make all those variables optional and in case one is missing, print that in the logs.

**Comment by masmu** [comment]
Done. @far3ll Could you try current git master? If `$DISPLAY` is really not needed it may work now.

**Comment by far3ll** [comment]
Thanks again for your help!
I tried the new git master and the Display-errors vanished.
But no matter which configuration I'm using for systemd, PA (in usermode) exits and can't get started by pulseaudio-dlna automatically. PA-dlna does not connect to PA in systemmode at all.
So I'm about to discard the idea of automatic startup of PA/-dlna and let the http-server start it manually if needed.

**Comment by klaernie** [comment]
Why do you need PA in system mode anyway? Shouldn't be there always a user logged on, that can output audio?

I just checked with d-feet: the pulseaudio service in system mode is only exposing org.pulseaudio.Server on the system bus, while in user mode also org.PulseAudio1 is present and both endpoints are on the session bus.

**Comment by masmu** [comment]
@far3ll : _pulseaudio-dlna_ does not start _pulseaudio_. In daemon mode it waits for _pulseaudio_ instances and attaches to those if found. It also ignores _pulseaudio_ instances running as _root_ and instances running in the context of a display manager.

```python
    def _is_pulseaudio_user_process(self):
        return (self.uid >= self.UID_MIN and
                self._get_uid_name(self.uid) not in self.DISPLAY_MANAGERS)

```

**Comment by masmu** [comment]
@klaernie So, it cannot work in system mode. _pulseaudio-dlna_'s pulseaudio module is using _org.PulseAudio1_ massively.

**Comment by far3ll** [comment]
@klaernie : The _system-mode_ for PA was intended be a method for autostarting and running continuously, but i rejected that idea anyway. My goal is to make a website with a control panel, which controls cmus and streams music to a Denon AVR, so the only user would be `http`.
Now I'm aiming to start the pulseaudio-dlna process as soon as it is needed (somebody is starting music via the website). For testing purpose I'm logged in as user _http_ and start pulseaudio-dlna. Both PA and PA-dlna are listed in running processes as user _http_ (PA was not running before, so PA-dlna "spawns" automatically PA?)
So the problem is:

>  PulseAudio seems not to be running or PulseAudio dbus module could not be loaded.

`load-module module-dbus-protocol` is written in `/etc/pulse/default.pa` and preventively in `~/.config/pulse/default.pa`

Syslog also says:

>  pulseaudio[189]: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

but it's the same error I get when i start PA-dlna as normal user and everything works fine.
Are there any restrictions regarding the system-user _http_ (with set home-directory)?

**Comment by masmu** [comment]
@far3ll : Could you give me the output of `id -u` running as user _http_?

**Comment by far3ll** [comment]
jep, it's 

> 33

**Comment by masmu** [comment]
Edit _daemon.py_ line 106 and change `UID_MIN = 500` to `UID_MIN = 33`. Then it will try to attach to _http_'s pulseaudio instance. Hopefully that instance offers _org.PulseAudio1_.

**Comment by klaernie** [comment]
@masmu I think it should be made clear, that pa-dlna takes the same stance as PA, that system mode for PA is not supported.

But I now tried again, this time with first starting to play something through PA, and it works with PA in system mode. It's seems to be this behaviour: [Section Lookup Service Details](http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/ConnectingToServer/)

**Comment by far3ll** [comment]
It gets me the same error line, BUT I think I found the source of my problem:
I logged into the http-account via `su -s /bin/bash http` (as root) and starting PA-dlna failed. So I created a new test-user and logged in both via `su -s` and natively via SSH and PA-dlna only worked while logged in natively!

**Comment by far3ll** [comment]
So I connected to the _http_-user via SSH and started PA-dlna again. Next error, which showed up:

> 02-06 18:55:10 pulseaudio_dlna.listener                       INFO     Discovery complete.
> Connection failure: Timeout
> 02-06 18:55:28 pulseaudio_dlna.pulseaudio                     INFO     Could not get default sink. Perhaps there is no one set?
> Connection failure: Timeout
> Traceback (most recent call last):
>   File "/opt/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 540, in _on_new_message
>     getattr(self, message_type)(**message)
>   File "/opt/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 731, in add_device
>     device.short_name, device.label)
>   File "/opt/pulseaudio-dlna/pulseaudio_dlna/pulseaudio.py", line 170, in create_null_sink
>     module_id = int(subprocess.check_output(cmd).strip())
>   File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '[u'pactl', u'load-module', u'module-null-sink', u'sink_name="denonavrx4000_dlna"', u'sink_properties=device.description="Denon\\ AVR-X4000\\ (DLNA)"']' returned non-zero exit status 1

`pacmd list-sinks` says

> 0 sink(s) available.

Do I have to define a standard-sink in any of PA-config?

**Comment by masmu** [comment]
No, a default sink is not necessary, although _pulseaudio-dlna_ won't be able to switch back to your default sink in case the stream collapses.

The real error is that the process which adds the device sinks failed.
For some reason this does not work:
```
pactl load-module module-null-sink sink_name="denonavrx4000_dlna" sink_properties=device.description="Denon\ AVR-X4000\ (DLNA)"
```

**Comment by far3ll** [comment]
I think my journey comes to an end (at least for this part of my project).
My problem was that I **only** wrote `load-module module-dbus-protocol
` into the private `default.pa`. So I deleted this file and PA-dlna starts as supposed with _http_-user (hopefully also with php-executes ;).
Once again I would thank you very much for your support!

**Comment by masmu** [comment]
You are welcome. Could you sum up what you had to do in the end? Other users may benefit from this.

**Comment by far3ll** [comment]
### Conclusion:

- Autostarting Pulseaudio and Pulsaudio-DLNA did **not** work (regardless of root or non-root)
- Don't forget `load-module module-dbus-protocol` in `/etc/pulse/default.pa`
- `/etc/pulse/default.pa` will be overwritten by `~/.config/pulse/default.pa`
- `su -s /bin/bash [account]` (as root) is **not** the same as native login over e.g. SSH
- If a system-user should start PA-DLNA (UID < 500) `UID_MIN=500` in _daemon.py_ line 106 must be edited
- Read the instuctions carefully ;)

**Comment by Salohcins** [comment]
I realise this is a closed topic.  However for anyone wishing to figure out this in the future, my solution was achieved after reading the source and referencing [https://bbs.archlinux.org/viewtopic.php?id=197223](https://bbs.archlinux.org/viewtopic.php?id=197223).  The essence of it is that gdm and systemd each start their own dbus-daemon (with the --session arg) which don't interact with each other (also, I'm running into this problem on gnome-ubuntu).

My solution was simply to add to my .profile:
`systemctl --user --import-enviroment DBUS_SESSION_BUS_ADDRESS`
`systemctl --user start pulseaudio-dlna.service`

This overrides the systemd initiated dbus environment variable with one that is actually being used by the current pulseaudio server.  In ~/.config/systemd/user/pulseaudio-dlna.service is:
```
[Unit]
Desciption=Pulseaudio DLNA

[Service]
ExecStart=/usr/bin/pulseaudio-dlna

[Install]
WantedBy=multi-user.target
```

I realise that this is a slightly different goal to what @far3ll was trying to achieve with an autostarted system service running PA-dlna as opposed to a user started service, however I felt the journey warranted a comment in the end.  Now to see if this trick also works for Mopidy.

**Comment by far3ll** [comment]
I also found a new way to autostart pulseaudio and pulseaudio-dlna by user http (who is not logged on and has thereby no running session, tons of problems getting dbus working). After several hours of trial and error I simply followed the instructions on [this site](https://unix.stackexchange.com/questions/105964/launch-a-fake-minimal-x-session-for-pulseaudio-dbus), installed [Xvfb](https://www.archlinux.org/packages/extra/x86_64/xorg-server-xvfb/), wrote a few lines like this:
```
#!/bin/bash
Xvfb :1 -screen 0 1x1x8 &
sleep 2s
DISPLAY=:1 /usr/bin/pulseaudio -D
DISPLAY=:1 /usr/local/bin/pulseaudio-dlna > /tmp/PA-dlna.log 2> /tmp/PA-dlna.error.log
```
autostarted named script with systemd and voilà, pulseaudio-dlna starts and runs under user http.
And therefor, mission accomplished.

**Comment by askmatey** [comment]
[klaernie's systemd unit file](https://github.com/masmu/pulseaudio-dlna/issues/159#issuecomment-179566776) works perfectly fine with Fedora and Chromecast

**Comment by bmullan** [comment]
@far3ll - [you stated](https://github.com/masmu/pulseaudio-dlna/issues/159#issuecomment-220254501) ... pulseaudio-dlna starts and runs under user http.

I don't see anything in that bash script that causes pusleaudio-dlna to start/run under user http?  Was that done by something else you did?   thanks

**Comment by raphaelh** [comment]
I'm under Xubunt 16.04 LTS 64 bits, and didn't manage to autostart pulseaudio-dlna with systemd

Could someone explain in which file this systemd file must be saved, and what are the commands to run after this in order to run pulseaudio-dlna?

Why not include it in the Debian package?

Thanks in advance!

**Comment by merrx** [comment]
Now it's a little late for the answer, but I figurered a way out, to make it working. I used a fresh Ubuntu 16.04 with 64-bit. 

First thing, run Pulseaudio as [System-Wide Daemon](https://freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/). For this I have modified the config of PA.
> /etc/pulse/daemon.conf
```
system-instance = yes
allow-exit = no
cpu-limit = no
realtime-scheduling = yes
enable-shm = no
daemonize = no
```
After this modification pulseaudio has to started by root and then drops privileges to user pulse. Now we can archive the autostart with systemd
> /etc/systemd/system/pulseaudio.service
```
[Unit]
Description=PulseAudio Daemon
Requires=sound.target dbus.service
After=sound.target dbus.service

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
PrivateTmp=true
ExecStart=/usr/bin/pulseaudio
```
It's important to set daemonize in the above config to no (default value), if the system-instance is used. Else the systemd service will be killed immediately after spawning. Now the pulseaudio daemon is started and owned by user pulse. So the pulseaudio-dlna service has to use this user or the dbus makes problems.
> /etc/systemd/system/pulseaudio-dlna.service
```
[Unit]
Description=PulseAudio-DLNA Service
Requires=sound.target dbus.service network.target  pulseaudio.service
After=sound.target dbus.service network.target pulseaudio.service

[Install]
WantedBy=multi-user.target

[Service]
User=pulse
Type=simple
PrivateTmp=true
ExecStart=/usr/bin/pulseaudio-dlna  --disable-device-stop
```
After this settings enable and start the services.
```
systemctl enable pulseaudio.service
systemctl start pulseaudio.service
systemctl enable pulseaudio-dlna.service
systemctl start pulseaudio-dlna.service
```
This settings survived the reboot and every user of the pulse-access group can use the audio.

Additional Information:
Add user to pulse-access: `adduser merrx pulse-access`
View logs for debugging: ` journalctl -u pulseaudio.service`

**Comment by raphaelh** [comment]
Thanks for this great and detailed solution!

**Comment by bmullan** [comment]
thanks I will give this a try...
