### ISSUE TITLE
--create-device-config doesn't work

### ISSUE THREAD

**Issue by deisi** [masmu/pulseaudio-dlna#165]
When I try to create a config file with:

    $ pulseaudio-dlna --create-device-config

It only answers with the short help text like for wrong input. `--update-device-config` gives the same result .

I tried to run the same with `sudo` resulting in the following error:

    02-14 12:46:28 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
    02-14 12:46:28 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    02-14 12:46:28 pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (3712)
    02-14 12:46:28 pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (4042)
    02-14 12:46:30 pulseaudio_dlna.daemon                         INFO     Ignoring pulseaudio process (3712)!
    02-14 12:46:30 pulseaudio_dlna.daemon                         INFO     Attaching application to pulseaudio (4042)
    Traceback (most recent call last):
      File "/usr/bin/pulseaudio-dlna", line 9, in <module>
        load_entry_point('pulseaudio-dlna==0.4.7', 'console_scripts', 'pulseaudio-dlna')()
      File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/__main__.py", line 134, in main
        daemon = pulseaudio_dlna.daemon.Daemon()
      File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/daemon.py", line 46, in __init__
        self._check_processes()
      File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/daemon.py", line 90, in _check_processes
        proc.attach()
      File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/daemon.py", line 159, in attach
        compressed_env[k] = proc_env[k]
    KeyError: u'DISPLAY'

 I use `pulseaudio-dlna 0.4.7-1` on Arch Linux from `AUR`

**Comment by masmu** [comment]
Could you please be a little bit more detailed? I have no idea what you mean with "does not work".

Do have a firewall / iptables enabled?

**Comment by deisi** [comment]
@masmu 
I don't have any firewall enabled.
By doesn't work, I mean that is doesn't do anything. It doesn't create a config file, it doesn't run. It just returns the short help text of pulseaudio-dlna and that's it. If you would run 

    $ pulseaudio-dlna --foobaaadooo

you should get the same as I do I get for 

    $ pulseaudio-dlna --create-device-config

Its not a typo, since I tried it several times with copy/past plus retyping and using autocomlete several times, but It behaves like a typo.

**Comment by masmu** [comment]
Which version are you running and how did you install it? Cloned from master or some sort of package?

**Comment by deisi** [comment]
I'm running 0.4.7-1 from the Arch Linux `AUR` package manager.
I also tried using the cloned `master` branch from the git repo and the `ffmpeg-backend` branch. I see the same for all of them.

**Comment by masmu** [comment]
Well, this is weird. I just tested current master and it works for me. Besides that I really doubt that this is a problem of _pulseaudio-dlna_. Otherwise there would be reports all over github's issue tracker.

I get the following output when running `pulseaudio-dlna --create-device-config`:
```bash
$ pulseaudio-dlna --create-device-config
02-16 13:23:52 pulseaudio_dlna.application                    INFO     Using version: 0.4.7+git-533604a48575e21163085275061b3018c293f461 (master)
02-16 13:23:52 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.166.212:8080
02-16 13:24:01 pulseaudio_dlna.application                    INFO     Found the following devices:
02-16 13:24:01 pulseaudio_dlna.application                    INFO     Wohnzimmer (Chromecast)
02-16 13:24:01 pulseaudio_dlna.application                    INFO       - Mp3Codec
02-16 13:24:01 pulseaudio_dlna.application                    INFO       - AacCodec
02-16 13:24:01 pulseaudio_dlna.application                    INFO       - OggCodec
02-16 13:24:01 pulseaudio_dlna.application                    INFO       - WavCodec
02-16 13:24:01 pulseaudio_dlna.application                    INFO     Your config was successfully written to "/home/masmu/.local/share/pulseaudio-dlna/devices.json"
```
The only thing I could imaging is that there is a problem with your _docopt_ module. Which version are you using?

**Comment by deisi** [comment]
According to my package-manager I'm using using `docopt 0.6.2-3`
Can it also be right problem? Does my user need to be in a special kind of group? I wonder because the output with `sudo` is different from without.

**Comment by masmu** [comment]
I am using `0.6.2-1`. So, this should be fine.

No, this cannot be a right problem. The reason for the different output is the architecture of _pulseaudio_. When _pulseaudio-dlna_ should run as root it has to be started in a different way then just starting the process with root permissions.

I have no idea what is going on. I checked if everything is wired up correctly and it is. Could you debug this yourself? Should be pretty easy. I would start with adding an additional logger to `__main__.py` and verify that the passed CLI options are in that dict. Like:

```python
def main(argv=sys.argv[1:]):

    import pulseaudio_dlna
    options = docopt.docopt(__doc__, version=pulseaudio_dlna.__version__)
    logger.info(options) # additional logger
    level = logging.DEBUG
    ...
    if os.geteuid() == 0:
        ...
    else:
        import pulseaudio_dlna.application
        app = pulseaudio_dlna.application.Application()
        app.run(options)
```

And that dict is passed to `_main_.py`:
```python
    def run(self, options):
        ...
        if options['--create-device-config']:
            self.create_device_config()
            sys.exit(0)
```

**Comment by deisi** [comment]
I just started to look into your code by adding a 

     print(options) 

I then called the programm with:

    python2 pulseaudio-dlna --create-device-config

and out of the sudden I got:

        {u'--bit-rate': None,
     u'--cover-mode': u'default',
     u'--create-device-config': True,
     u'--debug': False,
     u'--disable-device-stop': False,
     u'--disable-ssdp-listener': False,
     u'--disable-switchback': False,
     u'--encoder': None,
     u'--fake-http-content-length': False,
     u'--fake-http10-content-length': False,
     u'--filter-device': None,
     u'--help': False,
     u'--host': None,
     u'--msearch-port': u'random',
     u'--port': u'8080',
     u'--renderer-urls': None,
     u'--request-timeout': u'10',
     u'--ssdp-amount': u'5',
     u'--ssdp-mx': u'3',
     u'--ssdp-ttl': u'10',
     u'--update-device-config': False,
     u'--version': False}
    02-16 21:50:33 pulseaudio_dlna.application                    INFO     Using version: 0.4.7
    02-16 21:50:33 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.22.100:8080
    02-16 21:50:42 pulseaudio_dlna.application                    INFO     Found the following devices:
    02-16 21:50:42 pulseaudio_dlna.application                    INFO     Your config was successfully written to "/home/murmelmu/.local/share/pulseaudio-dlna/devices.json"

so note the last lines. It worked!!! So no debugging needed year. I then tryed to install this with:

    sudo python2 setup install 

and it installed. When I now call

    pulseaudio-dlna --create-device-config

it doesn't work. Looking into your README.md I realize this might be the wrong way to install it. I have this line from the PKGBUILD, which is the script that is used to install the software under Arch Linux. Can this be the problem? It must be installed with `makte` and `makte install`? Thus the PKGBUILD is wrong?

**Comment by masmu** [comment]
Sorry, but I am really the wrong person for _Arch_ questions. On _Ubuntu_ you **would** run `sudo make install`, but this is the dirty way because you are kind of bypassing your package manager.

Whats about using the existing packages for _Arch_?

**Comment by deisi** [comment]
I started with the existing package from Arch. This is where I first encountered the Problem. 
Anyhow, I think you have done all you can do. Thank you very much. I will try further by asking the package maintainer in the Arch Forum or where ever I find him. I will then link this here and when it is fully solved, we should close this here.
