### ISSUE TITLE
can't install from PPA

### ISSUE THREAD

**Issue by avilleret** [masmu/pulseaudio-dlna#166]
I'm not sure if this is the place to report that, but since `README.md` mention those steps, I do.
I can't install form PPA, because ffac is not installable.
But libfaac0 is already installed on my system.
I don't know if this is a bug in the package installation or just my system messed up.

~~~~
$ sudo apt-get install pulseaudio-dlna
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 pulseaudio-dlna : Dépend: faac (>= 1.28) mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
~~~~

**Comment by masmu** [comment]
I guess you are on ubuntu. Which version? _faac_ is available for  precise, trusty, vivid, wily and xenial.

**Comment by avilleret** [comment]
sorry, I forgot to mention some details...
yes Ubuntu 15.10 64bit
but this is my workstation, so there are plenty of dev lib installed...
trying to install it manually (sorry for the French output) : 

~~~~
$ sudo apt-get install faac
Mot de passe [sudo] pour antoine : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Aucune version du paquet faac n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

E: Le paquet « faac » n'a pas de version susceptible d'être installée
~~~~

btw, I managed to build it from source, and it work like a charm !
much better than the raop solution I tried earlier.
thanks a lot to make this available and open source :-)

**Comment by masmu** [comment]
I have no idea what you installed, but normally you can install _faac_ without any problems.

You are welcome!

**Comment by avilleret** [comment]
For the record, `faac` is part of multiverse repo which was not enabled on my computer (and I don't know why since it should be by default)
After adding it, save me. :-)

**Comment by masmu** [comment]
You are right. I will remove that dependency in the next release. Thanks for the hint!
