### ISSUE TITLE
No service type found when start playing

### ISSUE THREAD

**Issue by martin-insulander-info** [masmu/pulseaudio-dlna#17]
When starting to stream to a sink I get an exception
```python
  ERROR:dbus.connection:Exception in handler for D-Bus signal:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/upnp/renderer.py", line 113, in _get_av_transport_url
  return self._get_url(av_transport['control_url'])
  TypeError: 'NoneType' object has no attribute '__getitem__'
```

Looking at my server ( rygel ) it doesn't have any service with 
*urn:schemas-upnp-org:service:AVTransport:1* but with *urn:schemas-upnp-org:service:AVTransport:2*
so I tried change it and it worked.

I don't have a clue what that number means so without that knowledge I propose to change  render.py accordingly:
```python
   def _get_av_transport(self):
       for service in self.services:
            if service['service_type'].startswith(
                        'urn:schemas-upnp-org:service:AVTransport:'):
                return service
```

**Comment by masmu** [comment]
To be honest i don't know that too. But your code handles the case more appropriate and therefore its better :smile: 

Merged!

 * __0.3.1__ - (_2015-02-13_)
    - Fixed a bug so that AVTransports other than 1 can be used (thanks to [martin-insulander-info](https://github.com/martin-insulander-info))

Thanks for your help!
