### ISSUE TITLE
Cannot use SRS-X88

### ISSUE THREAD

**Issue by lucatersi** [masmu/pulseaudio-dlna#178]
The device is found but I get:
`The Chromecast seems not to be an original Chromecast! Model name: "SRS-X88" Skipping device ...`
I can the the volume contreller but the streaming doen,t start
any advice?

**Comment by lucatersi** [comment]
I managed to get it to work, but there are several seconds of delay.

**Comment by masmu** [comment]
That's great!

Regarding the delay: There is an explanation in the project's _README.md_. Section: _Known Issues_.
