### ISSUE TITLE
setup.py fails due to missing man page

### ISSUE THREAD

**Issue by super7ramp** [masmu/pulseaudio-dlna#186]
The debian folder was removed but the man page was there, so the setup.py fails at:
```
data_files=[
        ("share/man/man1", ["debian/pulseaudio-dlna.1"]),
    ],
```
Could you add the man page back to the repository and fix the path in setup.py please?

**Comment by masmu** [comment]
Thank you! Since this is part of ubuntu / debian packaging we should remove the file, right?

**Comment by super7ramp** [comment]
Well, man pages are not specific to a particular distribution so it should stay in this repo in my opinion. And thanks for very fast reply!

**Comment by masmu** [comment]
Does [this](https://github.com/masmu/pulseaudio-dlna/tree/bug/manpage) do the job?

**Comment by super7ramp** [comment]
Yes, thanks for the man folder! but why did you readd the debian folder?

**Comment by masmu** [comment]
read?

**Comment by super7ramp** [comment]
re-add

**Comment by masmu** [comment]
I just re-added the debian folder in a branch... For making my PPA releases. It is gone in master.

**Comment by masmu** [comment]
Ok, it is not. I merged from the wrong branch ...

**Comment by super7ramp** [comment]
:P

**Comment by masmu** [comment]
Well, fixed that. Fingers crossed :wink:

**Comment by super7ramp** [comment]
setup.py runs fine, thank you :)

**Comment by masmu** [comment]
Thank you for the fast info! :+1:
