### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by perok** [masmu/pulseaudio-dlna#188]
Just a heads up; updated pulseaudio-dlna to v0.5.0 from 0.4.7 and got this error:

`> pulseaudio-dlna
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum-compat' distribution was not found and is required by zeroconf
`

Fixed with pip install enum-compat.

**Comment by masmu** [comment]
Which distribution and version?

**Comment by perok** [comment]
Running Ubuntu 15.10. Application was installed from the ppa.

**Comment by masmu** [comment]
What is your version of _python-zeroconf_? `apt-cache show python-zeroconf | grep Version`

**Comment by perok** [comment]
`Version: 0.17.2-1`

**Comment by masmu** [comment]
I don't understand that. _pulseaudio-dlna_ relies in _python-zeroconf_. And you installed that package. _python-zeroconf_ should care about everything needed for it to run. And I do not maintain that package ... There should be a `Requires: enum-compat` in python-zeroconf's control file ...

**Comment by perok** [comment]
Found this in the changelog for python-zeroconf:
> python-zeroconf (0.17.2-1) unstable; urgency=low
> 
>   * New upstream release
>   * debian/pydist-overrides:
>     - Map enum_compat to python-enum34
>   * debian/py3dist-overrides
>     - In Python 3.4, the enum module is already present. Prevent any
>       dependency on python3-enum34.
> 
>  -- Ruben Undheim <ruben.undheim@gmail.com>  Tue, 25 Aug 2015 18:12:42 +0200

It's most likely the python dependency override that is problematic. Closing as this is not relevant for your repo.

**Comment by masmu** [comment]
Just installed an fresh wily vm and I can verify that error. Just don't know what to do. It is not my package which is failing ...

**Comment by masmu** [comment]
I think I have a possible workaround. Just setuptools is failing. Importing _zeroconf_ itself works. I will remove it from _setup.py_ and make sure it is included through debian packaging.

**Comment by perok** [comment]
Yeah, you can use the pypi zeroconf version with the deb package instead?

**Comment by masmu** [comment]
This is one option. But you don't need to. _python-zeroconf_ has everything it needs to run. You can check that with uninstalling the pip version and removing `enum-compat` from `/usr/lib/python2.7/dist-packages/zeroconf-0.17.2.egg-info/requires.txt`

**Comment by masmu** [comment]
I have rebuild the package, version _0.5.0.1_. Just waiting for the build servers until it is published. I think in 30 minutes every one will have the fix. Thanks for the fast information! :+1:

**Comment by masmu** [comment]
The package was build and is now available.
