### ISSUE TITLE
How to turn a Linux machine into a DLNA device (audio sink)?

### ISSUE THREAD

**Issue by petterreinholdtsen** [masmu/pulseaudio-dlna#189]
Hi.  Is it possible to use pulseaudio-dlna to turn a linux box into a DLNA device?  I got a Raspberry Pi connected to my sound system, and it would be useful to be able to hook it up to a DLNA source.

**Comment by masmu** [comment]
Install [Cocy](https://github.com/mnlipp/CoCy), [gmrender-resurrect](http://github.com/hzeller/gmrender-resurrect), [pimusicbox/](http://www.woutervanwijk.nl/pimusicbox/) or [rygel](https://wiki.gnome.org/Projects/Rygel) on the RPi. After that _pulseaudio-dlna_ will be able to find the device and use it as a sink.

**Comment by petterreinholdtsen** [comment]
[Massimo Mund]
> Install [Cocy](https://github.com/mnlipp/CoCy),
> [gmrender-resurrect](http://github.com/hzeller/gmrender-resurrect),
> [pimusicbox/](http://www.woutervanwijk.nl/pimusicbox/) or
> [rygel](https://wiki.gnome.org/Projects/Rygel) on the RPi. After that
> _pulseaudio-dlna_ will be able to find the device and use it as a
> sink.

Thank you very much!  This gave me hope for a solution. :)

But not all of these are in Debian, but I find these:

* cocy - missing
* gmrender-resurrect - https://tracker.debian.org/pkg/gmediarender-resurrect
* rygel - https://tracker.debian.org/pkg/rygel
* pimusicbox - missing

Can you tell me, for a headless box, which one of the Debian packages
you would recommend?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by masmu** [comment]
You are welcome. Personally I am using _cocy_, but it is hard to setup and it is not packaged. So a lot of people are using _gmrender-resurrect_ so I would go with that.

**Comment by davidanger** [comment]
I think the [upmpdcli](https://www.lesbonscomptes.com/upmpdcli/) is what you need!
