### ISSUE TITLE
filter trouble in version 0501

### ISSUE THREAD

**Issue by billsbro** [masmu/pulseaudio-dlna#190]
hi

I am having issues with the Hame Soundrouter again. I set it all back to its defaults so I make a wifi connection to the Hame Soundrouter first. 

I usually filter out other devices but now it skips the Soundrouter : 

bb@bb-Latitude-E6410:~$ pulseaudio-dlna --fake-http-content-length --filter-device=Soundrouter
03-13 16:58:02 pulseaudio_dlna.application                    INFO     Using version: 0.5.0.1
03-13 16:58:02 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.169.3:8080
03-13 16:58:02 pulseaudio_dlna.application                    INFO     Encoder settings:
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="True">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="True" sample-rate="44100" channels="2">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="True">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="False" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="False">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="False" sample-rate="44100" channels="2">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="False" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="False" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="False" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="False">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
03-13 16:58:02 pulseaudio_dlna.application                    INFO     Codec settings:
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
03-13 16:58:02 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
03-13 16:58:03 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:03 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:04 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:05 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...
03-13 16:58:05 pulseaudio_dlna.holder                         INFO     Skipped the device "Soundrouter (DLNA)" ...

**Comment by masmu** [comment]
Thank you for the bug report. I fixed the bug in [bug/device-filter](https://github.com/masmu/pulseaudio-dlna/tree/bug/device-filter). Could you please check it out and verify that it works?

**Comment by billsbro** [comment]
Sure, but how do I do that? 

Date: Tue, 15 Mar 2016 05:44:13 -0700

**Comment by masmu** [comment]
You can build it from source or I could build you a test package (.deb) you simply could install. But for that I would need your email to send it to you. You could contact me via my donations email address so that your own email address remains private.

**Comment by masmu** [comment]
I sent you a custom .deb with the fix included by email.

**Comment by masmu** [comment]
0.5.2 - (2016-04-01)
- Catched an exception when record processes cannot start properly
- Fixed the --filter-device option
- Prioritize mp3 over flac for Chromecasts

**Comment by billsbro** [comment]
Sorry, I totally forgot to reply that I never got the deb file email.

**Comment by masmu** [comment]
No worries. It is published within the ppa. Did you test it?

**Comment by billsbro** [comment]
Its working again. Thanks a lot.
