### ISSUE TITLE
Changes in available devices are not detected

### ISSUE THREAD

**Issue by emk2203** [masmu/pulseaudio-dlna#192]
I use the latest version 0.5.0.1 from the Ubuntu qos ppa  on 16.04LTS, together with a simple `pulseaudio-dlna.service` in `/etc/systemd/system`:

```
[Unit]
Description=PulseAudio-DLNA
Wants=pulseaudio.service
After=pulseaudio.service

[Service]
ExecStart=/usr/bin/pulseaudio-dlna
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

While all devices present at system start work flawless, there is no detection of changes in the available devices. I need to do `systemctl restart pulseaudio-dlna` to make changes appear. 

From my understanding, new devices should appear at runtime since 0.4.0. How can I make `pulseaudio-dlna` recognize them?

**Comment by masmu** [comment]
Could you provide some more information about your OS? And please paste a log here of the process which is not able to recognize your devices.

**Comment by emk2203** [comment]
The issue can be closed. One of the last updates of Ubuntu 16.04LTS has corrected the problem. Devices are now recognized as soon as they are switched on, DLNA and Chromecast. For the record, the process was the unity-control-center sound module.
