### ISSUE TITLE
Stuttering sound with WAV and LPCM while pavucontrol is not open

### ISSUE THREAD

**Issue by nilmerg** [masmu/pulseaudio-dlna#195]
I doubt that this is an issue with pulseaudio-dlna, but I hope to get some hints where to look further or how to debug this properly.

My situtation:
- Ubuntu 15.10 on a DELL XPS 13 (9343) connected to the router using wifi
- Media renderer: Onkyo CR-N755 connected to the router using cable
- The default settings for MP3 work flawlessly

Once I switch to the WAV or LPCM codec, heavy stuttering starts. It stops completely and nearly instantly once I'll open pavucontrol but comes back in the same fashion upon closing pavucontrol.

Is there any chance to get this working properly without keeping pavucontrol running?

**Comment by masmu** [comment]
Is it right that the stuttering is gone while _pavucontrol_ is open?

**Comment by nilmerg** [comment]
Yes, exactly.

**Comment by masmu** [comment]
Which version are you running?

This is really odd. _pavucontrol_ is just a GUI application for managing _pulseaudio-dlna_ but should not influence its behaviour when not actually configuring something. I am also running _Ubuntu_ 15.10 and cannot confirm that. _pulseaudio-dlna_ starts a process (_parec_) which reads data from _pulseaudio_ and pipes that through an encoder. The result is being sent to your device via a HTTP stream. When it works with _pavucontrol_ opened, it would mean that the data from _pulseaudio_ is different from the data when _pavucontrol_ is closed and I have no idea why that should be the case.

Could you try out _ffmpeg_ as  encoder backend (`--encoder-backend=ffmpeg`)? Maybe the _wav_/_l16_ codec ffmpeg produces it more accepted than _sox_'s.

**Comment by nilmerg** [comment]
It's version 0.5.0.1 installed from your ppa.
Using the ffmpeg encoder backend does not change anything.

You mentioned parec, but in singular. I have two such processes. I guess that's because it's stereo? :D
However, they share the same parameters and the associated stream urls are also the same...

**Comment by klaernie** [comment]
In another issue were discussions about pulseaudios pass thru mode - could it be, that the additional monitor (the vu meter in pavucontrol) disables the pass thru mode, and by that means restores the expected behavior?

**Comment by masmu** [comment]
@klaernie Good point!

**Comment by nilmerg** [comment]
Well, I'am not able to fully eliminate that passthrough mode might be the cause because I could not find any indicator that it's active or inactive.

The only thing I noticed, is that once starting up pavucontrol, the latency of all sinks is set to 20000 usec (Including the virtual sink created by pulseaudio-dlna) but upon closing pavucontrol, it raises for the physical sinks to a seemingly very high random number and then resets a few moments later to 0.

Only the virtual sink keeps being set to a high latency once pavucontrol has been closed and is not a random number but 980000. Starting up pavucontrol again, it's set to 20000 again.

Defining a low latency as the default somewhere seems to me being the solution for this issue, but I'm yet to find a way how to accomplish this..

**Comment by pjssilva** [comment]
Just to let you know that I have the same issue in Ubuntu 16.10 and 0.5.2 version of pulseaudio-dlna.
