### ISSUE TITLE
Firestick seen as Chromecast

### ISSUE THREAD

**Issue by JuddRogers** [masmu/pulseaudio-dlna#196]
Hi,

I am seeing a lot of log messages like this:
03-20 20:11:11 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "FireTV Stick" Skipping device ...

I'd like that to stop. What information would you need to help fix the code to decide a firestick is really a firestick?

I have a DHCP server with reserved IPs for devices (when I add them) so I can fix the firestick to a specific IP.

Thanks!

**Comment by masmu** [comment]
Which version are you running? And what do you expect instead of the message?

Am 21. März 2016 02:41:01 MEZ, schrieb Judd Rogers <notifications@github.com>:

**Comment by JuddRogers** [comment]
running from a clone off github:
~/src/pulseaudio-dlna/bin/pulseaudio-dlna --version
0.4.7+git-491a310c3a01ef9e1e35bc78aff0d9b5b52e4f20 (master)

I'd like to see that the code identifies the firestick as a firestick and ignores it if it is not a DLNA device.

It is not a big problem as I can ignore the log messages but it does seem to often be looking at the firestick to figure out how to work with it.

**Comment by masmu** [comment]
> I'd like to see that the code identifies the firestick as a firestick and ignores it if it is not a DLNA device.

Well, that is the case in _0.4.7_.

Please try out latest master. Since the discovery of _Chromecasts_ works now completely different the log message should be gone there.

**Comment by JuddRogers** [comment]
Works now, thanks!
