### ISSUE TITLE
Use localhost IP if no --host option was given

### ISSUE THREAD

**Issue by Takkat-Nebuk** [masmu/pulseaudio-dlna#2]
To further ease usage let me suggest we use localhost IP if no IP was given as an option.

This can e.g. be done by changing code in pulseaudio_dlna.py as below:

```python
+ import subprocess

-    if not options['--host']:
-        print('You must specify host address!')
-        sys.exit(1)
-    else:
-        host = str(options['--host'])
-        port = int(options['--port'])
+    port = int(options['--port'])
+    if options['--host']:
+        host = str(options['--host'])
+    else:
+        retcode = subprocess.Popen(['hostname', '-I'], stderr=subprocess.PIPE, stdout=subprocess.PIPE)
+        host = retcode.communicate()[0].decode().strip('\n')
+        print ('Using localhost: ' + host)
```

**Comment by masmu** [comment]
Getting the local ip address is no simple task if you have multiple interfaces as i do.

What do you think of:

```
import commands
import re

def default_ipv4():
    status_code, result = commands.getstatusoutput('ip route get 255.255.255.255')
    if status_code == 0:
        print result
        match = re.findall(r"(?<=src )(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})", result)
        if match:
            return match[0]
    return None
```

**Comment by Takkat-Nebuk** [comment]
yeah `ip route get' sure is an alternative to `hostname -I'.
However if people had multiple interfaces they may prefer your still working --host option anyway.

**Comment by masmu** [comment]
Sorry for the late reply.

A friend of mine recommended `socket.gethostbyname(socket.getfqdn())`, but since this is all about the important default value **host** i will first test it.

I will implement it this evening (hopefully).

**Comment by masmu** [comment]
* __0.2.1__ - (_2015-01-11_)
    - TTL changed to 10 and timeout to 5 for UDP broadcasting
    - Added the ```--renderer-urls``` option to manually add UPNP devices via their control url
    - Added the ```--debug``` flag
    - The host ip address is now discovered automatically, no need to specifiy ```--host``` anymore

**Comment by Takkat-Nebuk** [comment]
Cool! Works great now. Thank you!

**Comment by masmu** [comment]
Your welcome :)
