### ISSUE TITLE
Add AVM FritzRepeater N/G to supported list

### ISSUE THREAD

**Issue by e-alfred** [masmu/pulseaudio-dlna#201]
Hello,

I am running pulseaudio-dlna with an AVM FritzRepeater N/G that has an audio connector and provides an DLNA compatible media renderer.

Here is more information about it:
http://avm.de/service/fritzwlan/fritzwlan-repeater-ng/uebersicht/

Thank you

**Comment by masmu** [comment]
Thank you! I merged your PR. :+1:
