### ISSUE TITLE
Panasonic TX-P42G30E reported codec not working

### ISSUE THREAD

**Issue by Forage** [masmu/pulseaudio-dlna#203]
Hi,

After discovering pulseaudio-dlna I wanted to share my experience from a short test drive.
First of all: It's great to see (hear) this project! Many thanks for you effort.

I have a Panasonic TX-P42G30E TV which gives me the follow config automatically:

```
{
    "uuid:4D454930-0100-1000-8001-04209AB389E5": {
        "rules": [], 
        "flavour": "DLNA", 
        "name": "VIERA G30 Series", 
        "codecs": [
            {
                "rules": [], 
                "bit_rate": null, 
                "identifier": "mp3", 
                "mime_type": "audio/mpeg"
            }, 
            {
                "channels": null, 
                "rules": [], 
                "identifier": "l16", 
                "sample_rate": null, 
                "mime_type": "audio/L16"
            }
        ]
    }
}
```

mp3 plays just fine with its default settings, be it with a 'massive' 22 seconds delay.
L16 is also reported and even though I get no errors when forcing to use that one, I get no sound at all.
I also forced all the other codecs, but those reported me `Could not find a suitable encoder!` errors as could be expected. I would have expected WAV to be no problem though, like the other Panasonic TV's.

Is there anything you'd like me to try and report to get the L16 codec problem sorted?

**Comment by masmu** [comment]
Is the device connected via cable? And which version are you using?

If you are running the latest version you can try the `--encoder-backend` option and test if _ffmpeg_'s wav stream will be accepted. If it is not, you can try _BubbleUPnP_ and check if it is capable to send a compatible wav stream to your device.

**Comment by Forage** [comment]
Version: 0.5.0.1
OS: Ubuntu GNOME 15.10
The TV is connected by network cable.

With ffmpeg I get the exact same results for mp3, l16 and wav. I.e. music for mp3, silence for l16 and an error for wav.

I can not play wav files on my TV using `AV Control Point` (GUPnP) with audio files from a `miniDLNA` server. I guess that rules out wav support, unlike the other Panasonic TV's.

The TV has no problem playing AAC (.m4a) if I use `AV Control Point` with audio files from a `miniDLNA` server. This, however, results in the same errors when doing so with pulseaudio-dlna (ffmpeg or not).
No transcoding is being done by the miniDLNA server as far as I can tell:
```
<?xml version="1.0" encoding="UTF-8"?>
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">
  <item id="64$1$70$8$0" parentID="64$1$70$8" restricted="1">
    <dc:title>Bridge Burning</dc:title>
    <upnp:class>object.item.audioItem.musicTrack</upnp:class>
    <dc:creator>Foo Fighters</dc:creator>
    <dc:date>2011-01-01</dc:date>
    <upnp:artist>Foo Fighters</upnp:artist>
    <upnp:album>Wasting Light</upnp:album>
    <upnp:genre>Alternative Rock</upnp:genre>
    <upnp:originalTrackNumber>1</upnp:originalTrackNumber>
    <res size="9973548" duration="0:04:46.534" bitrate="256000" sampleFrequency="44100" nrAudioChannels="2" protocolInfo="http-get:*:audio/mp4:DLNA.ORG_PN=AAC_ISO_320;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000">http://192.168.1.10:8200/MediaItems/7713.m4a</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://192.168.1.10:8200/AlbumArt/4313-7713.jpg</upnp:albumArtURI>
  </item>
</DIDL-Lite>
```

I don't know how I can use miniDLNA to let it play l16 for testing.

I'm still waiting for Rygel to finish indexing so I can test it with that server as well. If BubbleUPnP really is a must for testing than let me know, I'd like to prevent installing that one for now.

P.s. How does one remove DLNA PulseAudio devices when hasn't been properly closed (by me using CTRL + x)? They remain present.

**Comment by masmu** [comment]
Normally you close _pulseaudio-dlna_ by pressing _CTRL + C_. If there are still some virtual sinks remaining you could remove them by commandline (`man pactl`) or simply restart _pulseaudio_ (`pulseaudio -k`). If you restart _pulseaudio_ you will also have to restart _pulseaudio-dlna_.

If you really want to force your devices play codecs they are (eventually) not suppose to play:
Edit `sudo gedit /usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/upnp/renderer.py` and change line 158 to the following:
```python
    def activate(self, config):
        self.codecs = [pulseaudio_dlna.codecs.AacCodec()]
        return
        if config:
            self.set_rules_from_config(config)
        else:
            self.codecs = []
            mime_types = self._get_protocol_info()
            if mime_types:
                for mime_type in mime_types:
                    self.add_mime_type(mime_type)
                self.check_for_codec_rules()
                self.prioritize_codecs()
```
This forces the application to always use AAC for streaming. But be warned, your device may not find that very pleasant. 

BubbleUPnP is a great streaming application and I normally use it to get a second option if things fail because of my implementation or because of the manufacturers implementation.

**Comment by masmu** [comment]
In current master and in the next release there is now the `--disable-mimetype-check` flag for that.
