### ISSUE TITLE
pulsaudio-dlna isn't able to figure out my IP address

### ISSUE THREAD

**Issue by tgurr** [masmu/pulseaudio-dlna#206]
pulsaudio-dlna isn't able to figure out my IP address and fails
to start telling me I have to specify it manually via the --host
option:

Mar 23 15:19:33 lxpc6170 pulseaudio-dlna[17735]: 03-23 15:19:33
pulseaudio_dlna.application                    INFO     I could not
determine your host address. You must specify it yourself via the
--host option!

I've done so in the past but now I wanted to add a systemd service
file to our distribution package, which makes it hard to specify an IP
address manually.

The network is up and running fine:

```
# systemctl status systemd-networkd
Mar 23 14:30:19 lxpc6170 systemd[1]: Starting Network Service...
Mar 23 14:30:19 lxpc6170 systemd-networkd[309]: Enumeration completed
Mar 23 14:30:19 lxpc6170 systemd[1]: Started Network Service.
Mar 23 14:30:23 lxpc6170 systemd-networkd[309]: eno1: Gained carrier
Mar 23 14:30:25 lxpc6170 systemd-networkd[309]: eno1: Gained IPv6LL
Mar 23 14:30:26 lxpc6170 systemd-networkd[309]: eno1: DHCPv4 address
10.132.151.86/24 via 10.132.151.1
Mar 23 14:30:37 lxpc6170 systemd-networkd[309]: eno1: Configured
```

I have no idea if I'm missing something or why pulseaudio-dlna isn't
able to figure out the current IP.

**Comment by masmu** [comment]
It uses internally the `ip` command to determine the ip.

```python
def default_ipv4():
    status_code, result = commands.getstatusoutput('ip route get 255.255.255.255')
    if status_code == 0:
        match = re.findall(r"(?<=src )(\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})", result)
        if match:
            return match[0]
    return None
```
Does that help somehow?

**Comment by tgurr** [comment]
Indeed, installing iproute2 did the trick. So I'd like to turn this into a feature request, maybe you can add an additional check to incorporate the output of `networkctl status` which comes with systemd if the ip command is not present on the system? A stripped down system with plain systemd(-networking) can work fine without net-tools/iproute2/iputils.

**Comment by masmu** [comment]
Sounds good. Could you please test [this](https://github.com/masmu/pulseaudio-dlna/tree/feature/support-networkctl)?

**Comment by klaernie** [comment]
@masmu wouldn't it be more fitting to start the listener after the devices have been discovered? As far as I know you should have an incoming packet, that carries your local IP as target. Or is all multicast not involving the unicast IPs?

**Comment by klaernie** [comment]
Or maybe use a Python library: https://pypi.python.org/pypi/netifaces

**Comment by tgurr** [comment]
@masmu Your patch seems to work fine for me having the network configured via systemd-networkd and iproute2 uninstalled, thank you very much!

**Comment by masmu** [comment]
@klaernie I know what you mean. It is not the cleanest solution. Normally you would rather use a library for this. But currently I am focused on stability and I know that the `ip` command is working fine besides the systemd stuff. That's why I prefer to extend the functionality this time instead of replacing it with something which may fail for some users.

Since **tgurr** is planning to ship a startup file, would it be a good idea to insert a check if there is already a running _pulseaudio-dlna_ instance? Just in case a user tries to start the application because he is used to this? Otherwise he will get a bind error, which does not explain how the error occurred.

**Comment by pmithrandir** [comment]
Hello,

I have the same issue, and iproute2 is not present in all distribution.
Maybe you could use one of the solution proposed on this link to retreive the hostname : 
http://stackoverflow.com/questions/4271740/how-can-i-use-python-to-get-the-system-hostname
Or for the ip : 
http://stackoverflow.com/questions/11735821/python-get-localhost-ip
or : http://stackoverflow.com/questions/24196932/how-can-i-get-the-ip-address-of-eth0-in-python

The current method is not so clean...
I don't have a python system here.. sorry, could not push a pull request

Pierre

**Comment by masmu** [comment]
@pmithrandir I know it was not the cleanest solution. But it was the better solution that time. I wanted a stable release and therefore it was better to extend the known to be working system instead of replacing it with a completely new one. It will replace that it in the near future.

**Comment by masmu** [comment]
This issue has been fixed finally in current master. Cheers!
