### ISSUE TITLE
pulsaudio-dlna + Sony STR-DN860 / problem DLNA

### ISSUE THREAD

**Issue by syosB** [masmu/pulseaudio-dlna#209]
Hi,
I LinuxMint 17.3 and pulsaudio dlna. Everything works well with Sony in chromecast.
DLNA does not work. Sony is 100% compatible DLNA / chromecast / Airplay
I get the following error in DLNA: Unknown reason. Your streams where swithedbark to audio interne digital stereo (HDMI)

An idea of ​​the problem and the solution?

Thank you.

**Comment by thoemy** [comment]
Device needs `--fake-http-content-length`
