### ISSUE TITLE
fresh install fails on headless server (ubuntu 14.04)

### ISSUE THREAD

**Issue by roelofz** [masmu/pulseaudio-dlna#21]
After a fresh install, using a vm, following the instructions, I get the following when running pulseaudio-dlna:

Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 9, in <module>
    load_entry_point('pulseaudio-dlna==0.3.1', 'console_scripts', 'pulseaudio-dlna')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/__main__.py", line 40, in <module>
    import gobject
ImportError: No module named gobject

Google did not help, so what to do to fix this?

Thanks!

Roelof

PS: Is this a base to send  a music stream to my dlna compliant receiver (as is possible with media player in Windows). So no player function on the receiver (that is exactly what I want to replace), only receiving.

Appreciate your feedback, thanks!

**Comment by masmu** [comment]
Seems as the gobject module is missing.
Try to install it via ```sudo apt-get install python-gobject```

Yes. You just send a stream to your reciever. But to be honest, it was never meant to be runned on a headless server without GUI.
Is it correct, that there is no X server installed on your headless server? If thats the case, you will have to change the default audio sink via ```pactl``` to make it work. Thats the part you normally would do via a GUI tool, as it is shown in the project description.

But anyways thats interesting, so keep me posted :smile:

**Comment by roelofz** [comment]
Hi,

I think you solved a million problems I had with pulse audio! maybe include this one in the dependencies (or are these already included on a normal desktop?)?

Thanks for your great help, it all seems to start now and pulseaudio-dlna even got my receiver detected.
So next stop auto-start pulseaudio-dlna and pulseaudio and then configuring the sink to my receiver with MPD, the goal is using a web-based interface so all is running on the server, so my ipad is not active while playing music!

But now I need more time, today it is too late, so further testing will ben hopefully on Wednesday!

Thanks again and I will check back with my results!

Roelof

**Comment by roelofz** [comment]
Maybe a stupid question, but how to start pulaseaudio-dlna without the cli waiting for it to be ended?
Is there a --daemon  command for it to run as a daemon or is there another trick?

**Comment by masmu** [comment]
No. There is no ```--daemon``` mode yet.

Search for ```job control fg bg``` or ```screen job control``` on google to get infos how to solve such problems.

**Comment by masmu** [comment]
I added the missing dependency in 0.3.2

 * __0.3.2__ - (_2015-03-14_)
    - Added the Opus Encoder (new dependency: `opus-tools`) (thanks to [MobiusHorizons](https://github.com/MobiusHorizons))
    - Fixed a bug where an empty UPNP device name made the application crash
    - Added a missing dependency (`python-gobject`)
