### ISSUE TITLE
Frequent disconnections (with Harman Kardon amplifier)

### ISSUE THREAD

**Issue by bidinou** [masmu/pulseaudio-dlna#215]
Hi ! I'm using latest pulseaudio-dlna (0.5.2 and also tried the git version) under ArchLinux (KDE Plasma 5). It works properly (my HK amplifier AVR 161 is automatically connected).

However, it gets disconnected  (and automatically properly reconnects) every now and then (from several times per minute to every few minutes). 

Here's what is visible in the terminal : http://textuploader.com/5blwg
I added some blank lines between some of the disconnections.

They do happen whatever codec I use, whatever app I use and is not related to my CPU usage.

Best regards & thanks a lot !!

**Comment by bidinou** [comment]
Oops, I forgot to mention I use a very stable and wired network.

**Comment by masmu** [comment]
This is odd.
```
05-25 11:12:50 pulseaudio_dlna.pulseaudio                     INFO     Remove "avr16116109c645e115923_dlna" sink ...
05-25 11:12:50 pulseaudio_dlna.pulseaudio                     INFO     Removed the device "AVR 161_1610 9c645e115923".
```
Those lines indicate that your device sends a _logoff_ (`SSDP_BYEBYE`) notification to the network.

We can disable the mechanism that is listening to those and see if that is helping you to get rid of those interrupts.

Edit the file `plugins/upnp/__init__.py` and change lines 58-64 to:
```python
        def launch_listener():
            ssdp = pulseaudio_dlna.plugins.upnp.ssdp.listener\
                .ThreadedSSDPListener(
                    cb_on_device_alive=self._on_device_added,
                    cb_on_device_byebye=None
                )
            ssdp.run(ttl=ttl)
```
