### ISSUE TITLE
No valid XML returned from ...

### ISSUE THREAD

**Issue by pfoltyn** [masmu/pulseaudio-dlna#216]
pulseaudio-dlna fails to parse the following description.xml file gotten from "Acoustic Solutions Airplay 20W Speaker System" device.

[description.txt](https://github.com/masmu/pulseaudio-dlna/files/289298/description.txt)

**Comment by munkymack** [comment]
Running into the same problem with AirPin. Seems to connect to the Xbox on the same network properly...could be a problem with the Android app

**Comment by masmu** [comment]
I think if have found the error. To try it out modify `plugins/upnp/renderer.py` lines 554-557 to the following or use that [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/xml-no-manufacturer-specified):
```python
                if upnp_device.manufacturer is not None and \
                   upnp_device.manufacturer.lower() == 'yamaha corporation':
                    upnp_device.workarounds.append(
                        pulseaudio_dlna.workarounds.YamahaWorkaround(xml))
```
