### ISSUE TITLE
Compatibility tests for Freebox

### ISSUE THREAD

**Issue by FrnchFrgg** [masmu/pulseaudio-dlna#220]
First of all, there is no Freebox Player Mini... There is a Freebox mini 4K (Player and Server), which I presume was is the current line is about. That box runs Android, so it should in fact depend on whatever app you install on it (though the base firmware probably has the capability too).

Secondly, I tested with my Freebox Revolution Player (the set-top-box), which is _not_ the same hardware, and has more powerfull software as well and it works like a charm with the codecs WAV, MP3, FLAC, OGG but not OPUS and L16 (it seems it is refused by the renderer because of the mimetype). The box is detected as a DLNA renderer (even though it also implements AirPlay).

Note that the Freebox Revolution Server (the modem) also has tiny speakers and is also a DLNA renderer, but I didn't test yet.

All in all, can you update the compatibility table ?

Thanks

**Comment by d-vogel** [comment]
Hi,
You're right, the commercial name is different indeed. However, 'Freebox Mini Player' is how the device is advertized on the network, and the name we have to filter to detect it. See [this test](https://github.com/masmu/pulseaudio-dlna/blob/6b7aa820bd9b0dfc154e802e2138162399c3f1f4/pulseaudio_dlna/plugins/chromecast/renderer.py#L191).
It doesn't depend on any app install, as it was tested on the device out of the box and might be a buit-in feature on any Android tv device.

I will update the Freebox Mini player (4k) line on the table to provide info about supported codecs.

Cheers

**Comment by FrnchFrgg** [comment]
Beware, I didn't test the Freebox Midi Player (which I don't have, and runs on Android). What I tested is the Freebox Player (the big one, also called «Revolution»). It is not Android, but a completely custom firmware (based on Qt ?).

**Comment by d-vogel** [comment]
I did.
Yeah, you might be right, I remember reading that GUI on the Revolution is QML based.
