### ISSUE TITLE
renderer discovered but not added as pulseaudio sink

### ISSUE THREAD

**Issue by prayner** [masmu/pulseaudio-dlna#223]
pulseaudio-dlna successfully discovers a renderer on my network but
pactl list short sinks still shows only sink 0 the default PCM output (laptop speaker)
I imagine I need to add another pulseaudio module to discover the connection established by pulseaudio-dlna.
If that's the case can someone give me the module name?
thanks

**Comment by masmu** [comment]
Could you please attach a full debug.log here?
```pulseaudio-dlna --debug 2>&1 | tee -a debug.log```
