### ISSUE TITLE
Major lag

### ISSUE THREAD

**Issue by chiraag-nataraj** [masmu/pulseaudio-dlna#226]
I'm not sure if this is fixable, but when I hit play or pause, there's a good 3-4 second gap before the action takes effect. If I'm playing a video with the audio routed through my Chromecast, it's even more obvious (since the A/V sync is destroyed).

**Comment by chiraag-nataraj** [comment]
Never mind…I've been reading some of the closed issues and will try the solutions there.

**Comment by masmu** [comment]
A look in the FAQ will explain that behavior.
