### ISSUE TITLE
[feature request] announce all dlna streams

### ISSUE THREAD

**Issue by ewtoombs** [masmu/pulseaudio-dlna#229]
Though the current system works for dlna sinks that announce their presence over upnp, it doesn't work for others, like VLC, which do not announce their presence. It is possible, though, for dlna sources to announce their presence. This is how minidlna works. Can pulseaudio-dlna do this as well? If not, I for one would really love to have this feature.

**Comment by ustreedee** [comment]
Yes, I think I am having this same issue, can this be done as ewtoombs requested ?

**Comment by masmu** [comment]
There already was that idea / discussion before. You can find those in the closed issues. In short: It is possible but this is simply not the purpose of that project.
