### ISSUE TITLE
Chromecast not recognized by pulseaudio-dlna, but IS recognized in Chrome

### ISSUE THREAD

**Issue by xmbwd** [masmu/pulseaudio-dlna#235]
I just got a Chromecast Audio and set it up on my network.   I can cast audio from both my Android phone and my Ubuntu 16.04 computer's Google Chrome app.  Also, pulseaudio-dlna **does** see other devices around the house (Denon AVR and DirecTV).

But pulseaudio-dlna just doesn't pick up the Chromecast at all.  I tried changing the name of the Chromecast id based on [this issue](https://github.com/masmu/pulseaudio-dlna/issues/228), but it didn't work.

Anyone have any idea why pulseaudio-dlna is not seeing the Chromecast.

**Comment by xmbwd** [comment]
I tried this with 3 different Ubuntu computers (one running 15.10) and none of them saw the Chromecast.

**Comment by xmbwd** [comment]
I was able to resolve this by resetting the router that was between my primary router and the computers that were failing to connect to the Chromecast Audio with `pulseaudio-dlna`.  Some setting (other than firewall) must have conflicted with `pulseaudio-dlna`.

That said, there is _something_ in `pulseaudo-dlna` that operates differently than Google Chrome's casting plug-in and `mkchromecast`, as both of those worked under the old router setup.  

Also, it may be notable that `mkchromecast` did not work with `pulseaudio-dlna` installed.  So there may be more than one conflict.

**Comment by masmu** [comment]
I'd love to hear more details about your old router setup. If you could figure out what was conflicting this would be a great benefit for other users. :+1:

**Comment by xmbwd** [comment]
Hi Masmu.  I wish I could tell you.  I switched the settings too quickly to narrow it down.
