### ISSUE TITLE
Pulseaudio fails to play audio on Chromecast

### ISSUE THREAD

**Issue by Lazzu** [masmu/pulseaudio-dlna#236]
I'm trying to play audio from Spotify and VLC Media player using pulseaudio-dlna, but the log says the sink finishes immediately after it has been activated. There is nothing visible on TV, just the Chromecast wallpaper and clock. The logs when I try to play something are here: https://gist.github.com/Lazzu/7912a667576d693ed56be476e15d942b

**Comment by murygin** [comment]
Same problem with my Arch linux system and _pulseaudio-dlna 0.5.2-1_. Start command:
`pulseaudio-dlna --codec mp3 --encoder-backend=ffmpeg`

Log output:

`08-24 19:44:34 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
08-24 19:44:34 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.39:8080
08-24 19:44:34 pulseaudio_dlna.application                    INFO     Encoder settings:
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
08-24 19:44:34 pulseaudio_dlna.application                    INFO     Codec settings:
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="12" mime_type="audio/aac" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="3" mime_type="audio/opus" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="9" mime_type="audio/flac" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <WavCodec enabled="False" priority="15" mime_type="audio/wav" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="6" mime_type="audio/ogg" backend="ffmpeg">
08-24 19:44:34 pulseaudio_dlna.pulseaudio                     INFO     Added the device "n2castOnkyo (Chromecast)".
08-24 19:44:34 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink6"
08-24 19:44:35 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink6
08-24 19:44:35 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "n2castOnkyo (Chromecast)" to play ...
08-24 19:44:45 pulseaudio_dlna.pulseaudio                     INFO     The device "n2castOnkyo (Chromecast)" is playing.
08-24 19:44:45 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink6 finished!
^CApplication is shutting down.
08-24 19:46:44 pulseaudio_dlna.pulseaudio                     INFO     Remove "n2castonkyo_chromecast" sink ...
`

**Comment by masmu** [comment]
I just tried a fresh install of _pulseaudio-dlna_ 0.5.2 on ubuntu 16.04. It works for me with both _Chromecast_ and _Chromecast Audio_.

@Lazzu : I do not see that you switched the applications audio stream to a _Chromecast_. Did you forget to do this via _pavucontrol_?

@murygin : Your log is absolutely clean. This is no indication for an error. Whats about the different volume levels? You can adjust the devices volume, the streams volume and the Chromecasts volume.

**Comment by murygin** [comment]
Where do I set the volumes? I'm using _pavucontrol_ to set the volume of the application e.g. _banshee_ and the volume of the Chromecast output device. I also set the volume of the Chromecast in the Android app. No sound on the speaker. I there another volume level?

**Comment by masmu** [comment]
@murygin There is still the overall volume for the device (soundcard). I looked over it again and I saw that there is no incoming connection from the Chromecast. Did you have a firewall (e.g. iptables) installed and forgot to open the ports?

**Comment by murygin** [comment]
That's it! After stopping the firewall the Chromecast is working fine. I set 2 new rules and it was working with a running firewall aswell:
* Incoming from the Chromecast IP to my notebook an port 1900, UDP
* Incoming (?) from or to the Chromecast (?) port 8080, TCP 
Is the TCP connection on port 8080 from the Chromecast to my notebook or in the other direction?

**Comment by masmu** [comment]
Both ports incoming to your notebook. Outgoing connections shouldn't be blocked by default anyway. Take a look on the [troubleshooting guide](https://github.com/masmu/pulseaudio-dlna#troubleshooting).
