### ISSUE TITLE
Playing to Emtec N200 (Realtek 1073 - AMP MOservices r13) fail with unknown reason

### ISSUE THREAD

**Issue by batric** [masmu/pulseaudio-dlna#238]
Hello all, I'm trying to play from my pc (Fedora 14 x64) to my Renderer, pulseaudio discovers it just fine and add a sink, however as soon as I try to sendo come audio (even the Speaker test) is fails and switch back to internal audio,
Sending auto to my android phone running BubbleuPnP works just fine, also my phone cano control the renderer successfully even playing the streams from a DLNA Media server NAS.

I tried also using the --fake-http10-content-length and --fake-http-content-length options with same identical results.

I attached a debug log of the entire process from starting pulseaudio-dlna --debug to testing the speakers on the audio control panel.

Many thanks in advance

Riccardo

[n200.log.txt](https://github.com/masmu/pulseaudio-dlna/files/478041/n200.log.txt)

**Comment by masmu** [comment]
This seems to be a incompatibility between my and their DLNA implementation. Could you create a wireshark dump of an actual working instruction set of _BubbleUPnP_? So I could compare that dump with my implementation and figure out what is not working.

**Comment by batric** [comment]
[capture-full.cap.zip](https://github.com/masmu/pulseaudio-dlna/files/504586/capture-full.cap.zip)
Hello, please let me know if this capture is detailed enough, these are the hosts involved:

192.168.2.98  - Etrayz NAS running MiniDLNA v 1.1.4
192.168.2.99  - Emtec N200 running Realtek 1073 - AMP MOservices r13
192.168.2.130 - Samsung S4Mini -CM 13 - BubbleUpnp v. 2.8 licensed

Many thanks for your time

Riccardo

**Comment by batric** [comment]
Hello, did you find the problem?

Many thanks
Riccardo
