### ISSUE TITLE
Chromecast Audio is showing up, but no sound is being send to it: The streaming server could not bind to your specified port (8080).

### ISSUE THREAD

**Issue by JohannesTress** [masmu/pulseaudio-dlna#239]
If I start the pulseaudio-dlna server via terminal I get this: 

`pulseaudio-dlna  
09-22 09:36:39 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
09-22 09:36:39 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.24:8080
09-22 09:36:39 pulseaudio_dlna.application                    INFO     Encoder settings:
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="True" sample-rate="44100" channels="2">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
09-22 09:36:39 pulseaudio_dlna.application                    INFO     Codec settings:
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
09-22 09:36:39 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
09-22 09:36:39 pulseaudio_dlna.streamserver                   CRITICAL The streaming server could not bind to your specified port (8080). Perhaps this is already in use? The application cannot work properly!
09-22 09:36:40 pulseaudio_dlna.pulseaudio                     INFO     Added the device "JoWiWo (Chromecast)".

`

Any idea is very welcome - thanks indeed!

**Comment by masmu** [comment]
Another application is using the specified port. Shut that application down or use the `--disable-ssdp-listener` flag. I have already addressed that issue a lot of times before. Please search in the closed issues for it.
