### ISSUE TITLE
Surula Okto receiver error

### ISSUE THREAD

**Issue by nicleroy** [masmu/pulseaudio-dlna#240]
[pulseaudio-dnla._log.txt](https://github.com/masmu/pulseaudio-dlna/files/488311/pulseaudio-dnla._log.txt)

Hello,

Thanks to pulseaudio-dnla, I get to see my new Okto receiver but can't get it to work. I start pulseaudio-dnla with the following options : pulseaudio-dlna --codec mp3 --encoder-backend=ffmpeg

You'll find the log file attached.

Keep ut the good work !

Nico

**Comment by masmu** [comment]
It looks like your device did not accept the _play_ command. This could have several reasons.
Your device may be somehow locked. E.g. _yamaha_ devices need to be set to a certain mode via remote control to make it possible to stream to them.

Could you attach another output of:
`pulseaudio-dlna --debug --codec mp3 --encoder-backend=ffmpeg 2>&1 | tee -a debug.log`

Maybe I can find more in that.

**Comment by nicleroy** [comment]
Thanks for the quick answer Massimo! Don't bother though, I'm going to send the okto back and go for a more usual device to avoid these problems. Once again, thank you very much.

**Comment by masmu** [comment]
I do not claim 100% DLNA compatibility for _pulseaudio-dlna_. This is one of my goals though, but there is a good chance that I did something wrong. Maybe not.
