### ISSUE TITLE
Crash in zeroconf when wireless disconnects, streaming fails to resume later

### ISSUE THREAD

**Issue by joaoe** [masmu/pulseaudio-dlna#245]
Using pulseaudio-dlna 0.5.2 and zeroconf 0.17.4.

My use case: the computer is running pulseaudio-dlna and sending sound to the DLNA device (a Neet AirStream) through wifi. I turned off the router (was tyding up) and on again. I did not disconnect the wifi through NetworkManager. Obviously the sound stopped being sent to the router, but once the router came online, the sound streaming did not resume.

The terminal showed there was a crash:

```
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrip_inner
  self.run()
File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1057, in run
  self.zc.send(out)
File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1663, in send
  bytes_sent = s.sendto(packet, 0, (addr, port))
error: [Errno 22] Invalid argument
```

I had to kill pulseaudio-dlna and start again to resume sending audio to the device.

Even though I think this is perhaps a problem with zeroconf, pulseaudio could perhaps be a bit more resilient and be able to resume streaming the audio.

**Comment by joaoe** [comment]
![crash_pulsedlna](https://cloud.githubusercontent.com/assets/461983/19443629/9628528a-948d-11e6-92cf-ea4c47d1d57a.png)

**Comment by masmu** [comment]
I was able to reproduce the problem. Please try starting the application via
`pulseaudio-dlna --auto-reconnect`
It takes a while until the connection is reestablished but works for me.
