### ISSUE TITLE
Support for SHIELD TV, currently WIP

### ISSUE THREAD

**Issue by alexbarcelo** [masmu/pulseaudio-dlna#246]
Very interesting project! I just discovered it, but when I went to try my SHIELD TV device, I realized that it was not supported (I saw Chromecast and thought Chromecast as software, not the Chromecast hardware devices... dammit Google and your confusing names!)

I have been looking around with the differences between a Google Chromecast device and the SHIELD TV. Here I will present what I have discovered and the things that I have yet to understand.

First of all, the Chromecast use the DNS `_googlecast._tcp.local.`, while the SHIELD puts itself in `_androidtvremote._tcp.local.`. My first patch was to add both domains in the `ChromecastPlugin`, make `MDNSListener` to accept a list of domains and register each of them through a `ServiceBrowser` instance.

The device info provided by the mdns (the parameter received by `_on_device_added`) contains:

```
ServiceInfo(
    type=u'_androidtvremote._tcp.local.', 
    name=u'SHIELD._androidtvremote._tcp.local.', 
    address='\xde\xad\xbe\xef', 
    port=6466, 
    weight=0, 
    priority=0, 
    server=u'Android.local.', 
    properties={'bt': 'xx:xx:xx:xx:xx:xx'}
)
```

A couple of things here:
- `type`, `name`, `address`, `port`, appear "as expected" (?)
- Not sure if I can change the `server` name --I should double check my SHIELD options.
- `properties` contains a `bt` entry with a MAC address which I assume it is the SHIELD's Bluetooh
- Could not found any extra property.

`ChromecastRendererFactory.from_mdns_info` expects to have some extra properties. I assume that some of them are human-friendliness, but I don't know what is the `udn` field. In the Google Chromecast, that field is retrieved from the `id` property and used in the `udn` argument like this: `'{}:{}'.format('uuid', info.properties['id'])`.

I don't know what is `udn`... so I hardcoded some random value to see "what happens". If I patch that stuff and let the Chromecast SHIELD to be instantiated, then the program eventually fails in `BaseChromecastSocket`, specifically during the `wrap_socket` call. The exception is the following:

```
 SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:1645)
```

And here I am, not having any idea what to do next. Not sure if I should fix the `udn` stuff, if the SSL error is internal, if certificates are not adequate, if the SSL is an error, or what. I would be very grateful of some guidance, help. If somebody wants some debugging information about the SHIELD I can provide it. If I can make the SHIELD work I will ask how to put the PR, but thinking about that now seems to be overly optimistic ;)

**Comment by masmu** [comment]
Well, the _udn_ is just a unique device identifier. It can be anything, the only important thing is, that there is no other device with the exact same one.

Now to the actual problem. Devices announce services via MDNS and _Google_ does announce the _Chromecast service_ in `_googlecast._tcp.local.`
Since the _Shield TV_ is announcing a service in `_androidtvremote._tcp.local.` I assume that this is another service, but not a service which is talking the Google `cast v2` protocol.
That would explain why you get the SSL handshake error. `cast v2` is using SSL and whatever service is running there is not using SSL. So at least that service is just incompatible.

My tips:
- Identify the purpose of the announced service in `_androidtvremote._tcp.local.`. From the name it has something to do with remote controlling the device ...
- Since this is an Android box, there is the chance that is announcing a _Chromecast_ service... But you would really find that in `_googlecast._tcp.local.` not in any other location.

Is your SHIELD TV being listed when you are using your mobile phone to cast e.g. a Youtube video?

**Comment by alexbarcelo** [comment]
Thanks for the feedback @masmu! I will keep looking into it, but just a quick update: 

YouTube app has the "Cast to > SHIELD" ready to go, and it works as expected. In fact, the screensaver of the SHIELD is identical to the Google Chromecast, and the built-in "Cast screen" of Android OS also recognizes the shield and allows to cast to it. I am unable to find any difference (from a end-user point of view) between both of them.

When I poweron the Google Chromecast, it appears under `_googlecast._tcp` as you stated. But the SHIELD behaves just like that and it only seems to appear under `_androidtvremote._tcp`.

I will keep digging into this `_androidtvremote` domain.

**Comment by masmu** [comment]
Try overriding the port 6466 to use 8009. Chromecast is using that port normally.

`plugins/chromecast/renderer.py ~ line 217`
```python
    @classmethod
    def from_mdns_info(cls, info, type_=ChromecastRenderer):

        def _bytes2string(bytes):
            ip = []
            for b in bytes:
                subnet = int(b.encode('hex'), 16)
                ip.append(str(subnet))
            return '.'.join(ip)

        def _get_device_info(info):
            try:
                return {
                    'udn': '{}:{}'.format('uuid', info.properties['id']),
                    'type': info.properties['md'].decode('utf-8'),
                    'name': info.properties['fn'].decode('utf-8'),
                    'ip': _bytes2string(info.address),
                    'port': int(info.port),
                }
            except (KeyError, AttributeError, TypeError):
                return None

        device_info = _get_device_info(info)
        if device_info:
            return type_(
                name=device_info['name'],
                ip=device_info['ip'],
                port=8009, # <- changed
                udn=device_info['udn'],
                model_name=device_info['type'],
                model_number=None,
                manufacturer='Google Inc.'
            )
        return None

```

**Comment by alexbarcelo** [comment]
I have to apologize. Seems that I had something misconfigured (having the SHIELD connected through ethernet seems to hinder the Chromecast features). But I don't know how, even in that "hindered state", the Android devices detect the SHIELD, but they are unable to cast to it.

I am extremely sorry for the fuss. I will make some more tests and comment on them (even if it is only to add it to the list of supported devices). But this issue is definetely misleading. Thank you very much @masmu for your aid on the diagnosis.

**Comment by masmu** [comment]
Thank you for your sincerity, don't be sorry.

But the really important question is, does it work? If not, don't hesitate to ask for assistance.
Good luck and #makethemplay! :smile:
