### ISSUE TITLE
pulseaudio-dlna startup message - CRITICAL PulseAudio seems not to be running or PulseAudio dbus module could not be loaded. The application cannot work properly!

### ISSUE THREAD

**Issue by bradmallan** [masmu/pulseaudio-dlna#247]
Can you point to troubleshooting tips for this.
PulseAudio seems to be running - I verified by looking in the task manager.

Oh yes - warning - newbie to Linux alert.

I have a SONOS system I'm keen to stream to.
Also have not really understood how the software will be used and will be happy to create a wiki page once I get it working to explain to the masses. 
- how to set it up to run all the time - perhaps as a startup application or perhaps make it accessible via a menu option.
- what to do as in what's next after pulseaudio-dlna is running - I'm kinda assuming virtual devices in the pavucontrol selection

and whatever else create some paint by numbers instructions

**Comment by masmu** [comment]
- Installing the package
- Start it by typing: `pulseaudio-dlna`.
- It should detect all your streaming devices at startup and create a virtual audio device for each found device
- Open your systems volume control and switch an applications audio stream to one of those created virtual devices. E.g. you are seeing _pavucontrol_ in the projects sample [image](https://raw.githubusercontent.com/masmu/pulseaudio-dlna/master/samples/images/pavucontrol-sample.png).

> how to set it up to run all the time - perhaps as a startup application or perhaps make it accessible via a menu option.

From day one, there was not startup file shipped with my package. If you would change this, it would certainly break things for users which did that on their own.

> what to do as in what's next after pulseaudio-dlna is running - I'm kinda assuming virtual devices in the pavucontrol selection

You just need the start the application and I creates the devices for you. If not, please paste the output of `pulseaudio-dlna` here.

**Comment by bradmallan** [comment]
Hi thanks for the reply - it seems after a restart (after installation) that the software is creating the devices as you describe.
I'm not getting any sound on the sonos devices though - I'll see what switches I can play with to get some sound.
![image](https://cloud.githubusercontent.com/assets/23107698/20041545/bc1e9c30-a462-11e6-8ffa-93b351db3974.png)

**Comment by masmu** [comment]
If you want you can link a _debug.log_ here and I will take a look on it.
There is an easy command which will create that in the current directory.
`pulseaudio-dlna --debug 2>&1 | tee -a debug.log`

**Comment by bradmallan** [comment]
Cool I do the debug now.
Screenshot of the non debug shows this.
![image](https://cloud.githubusercontent.com/assets/23107698/20041854/6575ef14-a467-11e6-9f8e-8d60488f9713.png)

**Comment by masmu** [comment]
Thanks for the effort, but it is hard to see anything there ...

Try copy and paste the command I sent you in the last post. It will create a file you can upload somewhere.

At least I am pretty sure you are using my application :smile:

**Comment by bradmallan** [comment]
:-). Here's the debug.
https://drive.google.com/file/d/0BywHow1i9pSXMWd4cW5hNXAyMGc/view?usp=sharing

**Comment by masmu** [comment]
Well, looks great. Seems like it is playing. On the other hand the log is stopping too early... The start is in there, but there is no stopping and no error.

I guess you do not hear anything. Did you increase the different volume options?

**Comment by bradmallan** [comment]
I did try fiddling with volume - I will try again tomorrow. And keep it running for longer (sorry but was not seeing more activity - as you observed the response is a good ol' 200.

**Comment by bradmallan** [comment]
Been a while since last trying - so I have a result! :-). The firewall was preventing the traffic - aha!

So I'm almost there - the discovery is really slow? And a bit hit and miss on finding the various SONOS components. Been about 20 mins and my playbar is not coming up yet but it has previously so as I say a bit hit and miss. I have verified it's on by playing my normal music sources through it.

**Comment by bradmallan** [comment]
I started with debug as described above - log file is here in case this is interesting feedback.
https://drive.google.com/file/d/0BywHow1i9pSXMWd4cW5hNXAyMGc/view?usp=sharing

This particular run it found the playbar :-). And it's awesome - thanks for a great idea and software. 
Perhaps publish something about the firewall as a 'got ya!'

**Comment by masmu** [comment]
Glad that it finally works!

I wanted to compare the actual _debug.log_ with the one you provided 9 days ago, but it seems as you replaced the last one. So, as far as I remember there were good old 200 everywhere, but **also** incoming connections. Those usually do not occur when the firewall is set to blocking them. For those cases there is an entry in the [troubleshooting section](https://github.com/masmu/pulseaudio-dlna#troubleshooting).

> So I'm almost there - the discovery is really slow? 

Not really. I assume this is network related. E.g. I have about 12 different streaming devices, all of them being found in 5 seconds. Did you disable your firewall completely or did you open the required ports?
Please try to disable your firewall completely for testing purposes and see if discovery is more reliable.

**Comment by bradmallan** [comment]
Yup disabling the firewall makes it better and you're right my network on wireless is slow - I plugged in and got much faster results in regards to discovery.

I'm good to close this one. Thanks!

**Comment by masmu** [comment]
You are welcome!
