### ISSUE TITLE
support for Ubuntu yakkety (16.10)

### ISSUE THREAD

**Issue by greee-fr** [masmu/pulseaudio-dlna#248]
In the ppa soon ?

**Comment by Takkat-Nebuk** [comment]
For me it works great in Ubuntu 16.10. It may only need sources to be copied to yakkety series. In the meanwhile you are welcome to install from my ppa `ppa:takkat-nebuk/takkat`.

**Comment by masmu** [comment]
@Takkat-Nebuk Hope so :smile: ... Did not test it though.

The package is now published for yakkety.
