### ISSUE TITLE
pulseaudio-dlna: suggests/uses python-rsvg which is deprecated

### ISSUE THREAD

**Issue by muammar** [masmu/pulseaudio-dlna#252]
This is a report I received in  debian's BTS that will affect Ubuntu as well.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844151

**Comment by masmu** [comment]
Thanks for the update. I will try to merge all open PR's in the next days and do the required updates. 
When ends the _Stretch_ cycle?

Btw, I remember an open issue #212 about the bit rate in ogg codec.
