### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by CerebrosuS** [masmu/pulseaudio-dlna#262]
Hey,

thx for making this application and for the great work. What stopps you from porting/implementing it to python3? Or is there no reason and no one just wants to?

This application causes a lot python2 dependencies on my system and some are not available which I have to build then.

Thx and Greetings

**Comment by masmu** [comment]
Well, there was a dependency once that was written in python2. But it is gone. So the answer is: It started as python2 project and there was no real need to change that.

**Comment by Emgalai** [comment]
Maybe there now is more reason to move to Python 3 since python-zeroconf [has dropped Python 2 support at version 0.20.0](https://github.com/jstasiak/python-zeroconf#changelog). #342

**Comment by polyzen** [comment]
January 1, 2020 is the cutoff. https://pythonclock.org/

**Comment by dadosch** [comment]
actually, @aharter has ported it to python3 : https://github.com/aharter/pulseaudio-dlna/tree/python3
For me it works great, tho there are some dependency differences

**Comment by polyzen** [comment]
I would suggest @aharter make a PR, but this project seems abandoned? Ping @masmu

**Comment by polyzen** [comment]
@masmu could you reopen this?

**Comment by fabian727** [comment]
@polyzen 
Hi, thanks for referencing.
Since @masmu did no contribution greater one year to all of his github repos, I think we are left alone?

What is missing, so we could merge python3 into master and ask for integration into ubuntu20.04?

**Comment by polyzen** [comment]
Referencing
https://github.com/masmu/pulseaudio-dlna/pull/389#issuecomment-613709959
and
https://github.com/masmu/pulseaudio-dlna/pull/398
