### ISSUE TITLE
Google Chromecast 1st gen works with flac

### ISSUE THREAD

**Issue by joanwa** [masmu/pulseaudio-dlna#263]
According to the matrix, Google Chromecast should not work with flac. Perhaps one of the recent updates of the Chromecast enabled it?
Also can confirm that Libratone Zipp does not work with opus and aac. Shall I create a PR for this?

**Comment by masmu** [comment]
Thanks for the information!
I just tested it myself, it works. Well, I guess they changed this...

PR? Yes, please.

**Comment by joanwa** [comment]
both added, so closing it
