### ISSUE TITLE
[Feature request] Ability to setup a generic URL "device"

### ISSUE THREAD

**Issue by parkerlreed** [masmu/pulseaudio-dlna#266]
I'm testing sending audio to a basic device with a speaker attached (Linux). Ideally I want to just feed it a URL that's hosted on the pulseaudio-dlna machine, that loads the audio stream.

**Comment by masmu** [comment]
Could you please explain this a little bit more? Did you take a look on [radio.py](https://github.com/masmu/pulseaudio-dlna/blob/master/scripts/radio.py)?

**Comment by parkerlreed** [comment]
Well I managed to get a UPnP renderer working on the device I am using but my idea for the generic was:

In the pulseaudio-dlna configuration have a device that could look like this

````
    "uuid:generic-url": {
        "rules": [], 
        "flavour": "HTTP", 
        "name": "URL", 
        "codecs": [
            {
                "rules": [], 
                "bit_rate": null, 
                "identifier": "mp3", 
                "mime_type": "audio/mpeg"
                "port": "8888"
                "filename": "audio.mp3"
            }, 
        ]
    }
````

This would let anything that could load a URL be able to play your system audio

So I could pass

````
mpv http://<pulseaudio-dlna-machine>:8888/audio.mp3
````

And it could start playing the audio. Just a way to support something that may not already have a UPnP server available.

**Comment by masmu** [comment]
Well actually it is almost that way now. The UUID of the device is encoded in the URL.
```
URL settings: /dWRuPSJ1dWlkOjVjM2FkMDI0LTI4YjYtNDY1MS1hZmY1LTRkNTAyMjEwYWMxMCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3 (udn="uuid:5c3ad024-28b6-4651-aff5-4d502210ac10",type="bridge")
```
There is a settings dict, consisting of a property _type_ and the property _uuid_:
```python
        settings = {
            'type': 'bridge',
            'udn': self.udn, # <- "uuid:5c3ad024-28b6-4651-aff5-4d502210ac10"
        }
```
and this gets stringified and base64 encoded:
```python
        data_string = ','.join(
            ['{}="{}"'.format(k, v) for k, v in settings.iteritems()])
        stream_name = '/{base_string}/{suffix}'.format(
            base_string=urllib.quote(base64.b64encode(data_string)),
            suffix=suffix,
        )
        return urlparse.urljoin(base_url, stream_name)
```
So, the URL for a specific device will always stay the same. To use my example:
```
mpv http://<pulseaudio-dlna-machine>:8888//dWRuPSJ1dWlkOjVjM2FkMDI0LTI4YjYtNDY1MS1hZmY1LTRkNTAyMjEwYWMxMCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3
```
That will work like intended.

**Comment by parkerlreed** [comment]
Ahh thanks! So I can just basically create a fake device and should be able to load the URL? Neat.
