### ISSUE TITLE
Support for MPRIS

### ISSUE THREAD

**Issue by NNois** [masmu/pulseaudio-dlna#268]
Hi,
I have a Denon Receiver who display the song title with an Airplay device.

Pulseaudio DNLA display only the app playing name, which is very cool but what if he could do more like the song title for MPRIS apps like spotify ? ;-)

Thanks

**Comment by masmu** [comment]
Hey, please take a look at #259 for detailed information. Short summary: The DLNA specification does not support this. Chromecast does also not support this, but in that case you could write at least an own media player.
