### ISSUE TITLE
Import error for google.protobuf descriptor_pb2

### ISSUE THREAD

**Issue by novelgazer** [masmu/pulseaudio-dlna#273]
Up until recently, I was successfully running pulseaudio-dlna (from Packman) on OpenSuse Tumbleweed, but some time in late December/early January, I started getting the following error:

`File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_channel_pb2.py", line 7, in <module>
    from google.protobuf import descriptor_pb2
ImportError: cannot import name descriptor_pb2`

I'm guessing this was related to some python update from OpenSuse's end, but I'm wondering if anyone can suggest a fix.

pulseaudio-dlna version: 0.5.2-1.5
python-protobuf version: 3.1.0-1.1

**Comment by masmu** [comment]
Sorry, I have no idea. I am not using OpenSuse. Maybe this is a packaging issue?

**Comment by novelgazer** [comment]
I'll try the OpenSuse mailing list and cross reference any solution here.  Thanks.

**Comment by novelgazer** [comment]
The OpenSuse python-protobuf package maintainer has indicated there was a problem with the package, and a fix should be rolling out soon.  I'll update again when that happens and I get a chance to test.

**Comment by masmu** [comment]
@novelgazer Okay, thanks for the information!

**Comment by novelgazer** [comment]
Resolved error by updated to latest protobuf -- confirmed this was a problem with the protobuf package, as indicated above.
