### ISSUE TITLE
Cannot apt-add-repository ppa:qos/pulseaudio-dlna 

### ISSUE THREAD

**Issue by francesco1119** [masmu/pulseaudio-dlna#28]
apt-add-repository ppa:qos/pulseaudio-dlna
You are about to add the following PPA to your system:
 A small DLNA server which brings DLNA / UPNP support to PulseAudio and Linux.

It can stream your current PulseAudio playback to different UPNP devices (UPNP Media Renderers) in your network. It's main goals are: easy to use, no configuration hassle, no big dependencies.

https://github.com/masmu/pulseaudio-dlna
 More info: https://launchpad.net/~qos/+archive/ubuntu/pulseaudio-dlna
Press [ENTER] to continue or ctrl-c to cancel adding it

Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 160, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/SoftwareProperties.py", line 96, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python2.7/dist-packages/softwareproperties/SoftwareProperties.py", line 584, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python2.7/dist-packages/aptsources/distro.py", line 87, in get_sources
    raise NoDistroTemplateException("Error: could not find a "
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template

**Comment by masmu** [comment]
@francesco1119 
Which ubuntu version are you using?
Did you recently upgrade your ubuntu?
And, can you paste your  ```/etc/lsb-release``` here?

**Comment by francesco1119** [comment]
debian wheezy

**Comment by masmu** [comment]
This is an _Ubuntu_ repository. I think thats where the errors comes from. 

What you can do is download the `.deb` from [launchpad](https://launchpad.net/~qos/+archive/ubuntu/pulseaudio-dlna) with your browser and install it afterwards.

**Comment by francesco1119** [comment]
Thank you

well, it looks like there is no .deb out there...

Thank you anyway

**Comment by masmu** [comment]
There is. You have to click on `view package details` and after that you can open the package panels.

Then you can find the packages under `Package files`
