### ISSUE TITLE
volume keys don't control chromecast volume

### ISSUE THREAD

**Issue by dcherian** [masmu/pulseaudio-dlna#285]
I don't know if this requires extra configuration.

Using the volume keys changes the pulseaudio volume for the built-in speakers even though the chosen sink is chromecast.

I'm using xfce and xfce4-volumed-pulse.

**Comment by masmu** [comment]
Yeah. That's not the desired way of how it should work, but this can't be changed. When using your systems volume control it always affects pulseaudio and not the device the stream is being send to.

I also wanted to change this behavior and actually there are some branches where I tried something similar but no chance. This is internal pulseaudio behavior. I am sorry.

**Comment by dcherian** [comment]
:(
