### ISSUE TITLE
google home device not detected

### ISSUE THREAD

**Issue by dony71** [masmu/pulseaudio-dlna#292]
google home device should be same like chromecast device
any chance to support this?

**Comment by masmu** [comment]
Are you sure that Google home device is a fully capable Chromecast? If yes, it should be detected as every other Chromecast is. Otherwise I would need one to look into that... Or someone with one would need to.

**Comment by dony71** [comment]
Google Home should be showing up in that screenshot like a regular Google Cast device
I have BubbleUPnP server and it lists Google Home device 
Attached screen short shows zeroconf browser information for Google Home 

![google_home](https://cloud.githubusercontent.com/assets/4121053/24628152/2a2074ca-186b-11e7-81ec-8a2b8a530845.jpg)

**Comment by masmu** [comment]
That really looks like this a capable Chromecast client. Is the Google 'Home' application capable of using that device in a device group?

**Comment by dony71** [comment]
Yes, any google cast audio devices are capable of using in a device group
https://support.google.com/googlehome/answer/7174267?hl=en

**Comment by masmu** [comment]
Cool, do you have some time to figure this out now? I can't do this without you, because you're having the device. What we would need is some kind of chat, Skype is popular. And you would need to setup a development version of pulseaudio-dlna, so that I can setup a branch you are executing. If you are using Ubuntu there is a [script](https://github.com/masmu/pulseaudio-dlna/blob/master/scripts/bootstrap.sh) (the `install_dev` function) which gives you an idea of what to do.

Are you up for that?

**Comment by dony71** [comment]
sure, my skype id is dony71
i'm using armbian in armhf platform and initially i setup pulseaudio-dlna from your ppa ubuntu trusty branch

**Comment by masmu** [comment]
Solved for now.

**Comment by dony71** [comment]
@masmu : manage to get pulseaudio and pulseaudio-dlna under normal user mode
no critical or error message now, however google home is still not detected
notice some exception below which could be hint ???
-------------------------------------------------------------------------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/__init__.py", line 48, in discover
    mdns.run(ttl)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/mdns.py", line 54, in run
    self.zeroconf = zeroconf.Zeroconf()
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1336, in __init__
    self._listen_socket = new_socket()
  File "/usr/lib/python2.7/dist-packages/zeroconf.py", line 1303, in new_socket
    s.setsockopt(socket.SOL_SOCKET, reuseport, 1)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available

**Comment by masmu** [comment]
I guess your banana pi is running a kernel < 3.9 and therefore the `socket.SO_REUSEPORT` is not supported. python-zeroconf doesn't really need it, but [versions prior to 0.17.4](https://github.com/jstasiak/python-zeroconf/issues/28) raise that error.

So, either you have to upgrade your kernel (wouldn't recommend that) or you install `python-zeroconf >= 0.17.4`.

**Comment by dony71** [comment]
after reboot google home is not shown anymore in pacmd list-sinks
however log file shows chromecast added
it's very strange
-----------------------------------------------------------------------------------------------
04-04 12:29:51 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()
04-04 12:29:53 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Google Home (Chromecast)".
04-04 12:29:53 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink3"
04-04 12:29:54 pulseaudio_dlna.pulseaudio                     INFO     Added the device "PCH-A110 (00-06-DC-42-CD-0D) (DLNA)".
04-04 12:29:54 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink3

**Comment by dony71** [comment]
@masmu, i have basic question regarding pulseaudio-dlna
I notice in pacmd or pactl, there is set-sink and set-sink-inputs
Can you explain to me what is the different between sink and sink-inputs?
