### ISSUE TITLE
[Support] Bowers & Wilkins Zeppelin

### ISSUE THREAD

**Issue by nguymin4** [masmu/pulseaudio-dlna#294]
Hi,

I'm trying to use pulseaudio-dlna with my speaker Bowers&Wilkins Zeppelin. Though, the speaker is detected but there are errors with starting. If I  use pulseaudio-dlna with the Samsung TV then it works.

Here is the log:
```
04-04 17:57:23 pulseaudio_dlna.pulseaudio                     INFO     Added the device "My Zeppelin Air (DLNA)".
04-04 17:58:12 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream7"
04-04 17:58:13 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink9
04-04 17:58:13 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "My Zeppelin Air (DLNA)" to play ...
04-04 17:58:28 pulseaudio_dlna.plugins.upnp.renderer          ERROR    "My Zeppelin Air" registering failed!
04-04 17:58:28 pulseaudio_dlna.pulseaudio                     ERROR    The device "My Zeppelin Air (DLNA)" failed to play! (408) - Unknown reason.
Failure: No such entity
```

As far as I understand, this may be caused by lacking of `description.xml` schema for my speaker.
If that's the case can you help me to add it to your code somehow? I have the file ready here so we can dig into it.

Thanks

**Comment by masmu** [comment]
What kind of `description.xml`?

Normally if the registering fails the device has to be set into a specific mode before, otherwise it declines the connection. E.g. Yamaha devices have to be set to *Server mode* with the remote control first.

**Comment by nguymin4** [comment]
Ok, probably I misunderstood the point. Could you suggest me what to do in my case?

**Comment by masmu** [comment]
Check the manual if the device need to be set to a specific mode.
Furthermore you can also install _BubbleUPnP_ on your phone and test if this is capable to stream to it.
