### ISSUE TITLE
Connecting to Sony Wireless Speakers fails due to SSL Error

### ISSUE THREAD

**Issue by snareoj** [masmu/pulseaudio-dlna#305]
Hi,
i try to connect to a sony wireless speaker SRS-ZR-5
https://www.sony.de/electronics/kabellose-lautsprecher/srs-zr5
Its found and selectable in the sound settings.
But if i hit "Test loudspeakers" the following stacktrace is printed:
```
> snareoj@snareoj-desktop:~$ sudo pulseaudio-dlna 
> [sudo] Passwort für snareoj: 
> 04-13 09:16:49 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
> 04-13 09:16:49 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
> 04-13 09:16:49 pulseaudio_dlna.daemon                         INFO     Adding pulseaudio process (6323)
> 04-13 09:16:51 pulseaudio_dlna.daemon                         INFO     Attaching application to pulseaudio (6323)
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.30:8080
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO     Encoder settings:
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO     Codec settings:
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
> 04-13 09:16:51 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
> 04-13 09:16:52 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Schlafzimmer (Chromecast)".
> 04-13 09:16:52 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Wohnzimmer (Chromecast)".
> 04-13 09:16:57 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream0"
> 04-13 09:16:58 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink2
> 04-13 09:16:58 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Schlafzimmer (Chromecast)" to play ...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 63, in play
>     self.ip, self.port, self.REQUEST_TIMEOUT)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 229, in __init__
>     ChromecastController.__init__(self, ip, port, timeout)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 128, in __init__
>     self.socket = cast_socket.CastSocket(ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 107, in __init__
>     BaseChromecastSocket.__init__(self, ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 46, in __init__
>     self.sock.connect((ip, port))
>   File "/usr/lib/python2.7/ssl.py", line 866, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 857, in _real_connect
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
>     self._sslobj.do_handshake()
> error: [Errno 104] Connection reset by peer
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 681, in _handle_sink_update
>     result = future.result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 726, in __handle_sink_update
>     artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 139, in play
>     self, stream_url, artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 96, in play
>     cast.cleanup()
> UnboundLocalError: local variable 'cast' referenced before assignment
> 04-13 09:16:59 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
> 04-13 09:16:59 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream0"
```
Its a fresh installed Ubuntu 16.10 and followed the instructions from
https://linuxundich.de/gnu-linux/linux-sound-per-pulseaudio-an-chromecast-oder-dlna-receiver-streamen/

I am a new linux user, perhaps i am missing something fundamental.
Thanks and regards

**Comment by masmu** [comment]
Hi,
I just tried it with a fresh Ubuntu 16.10 and a Chromecast and it works for me.

You don't need to run it with `sudo`, just `pulseaudio-dlna` works fine. Please try it again with that.

**Comment by snareoj** [comment]
Thx for the fast reply!
i tried without sudo:

> snareoj@snareoj-desktop:~$ pulseaudio-dlna
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO     Using version: 0.5.2> 
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.30:8080
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO     Encoder settings:
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO     Codec settings:
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
> 04-13 09:53:59 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
> 04-13 09:54:00 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Schlafzimmer (Chromecast)".
> 04-13 09:54:00 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Wohnzimmer (Chromecast)".
> 04-13 09:54:37 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream4"
> 04-13 09:54:38 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink5
> 04-13 09:54:38 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Schlafzimmer (Chromecast)" to play ...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 63, in play
>     self.ip, self.port, self.REQUEST_TIMEOUT)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 229, in __init__
>     ChromecastController.__init__(self, ip, port, timeout)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 128, in __init__
>     self.socket = cast_socket.CastSocket(ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 107, in __init__
>     BaseChromecastSocket.__init__(self, ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 46, in __init__
>     self.sock.connect((ip, port))
>   File "/usr/lib/python2.7/ssl.py", line 866, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 857, in _real_connect
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
>     self._sslobj.do_handshake()
> error: [Errno 104] Connection reset by peer
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 681, in _handle_sink_update
>     result = future.result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 726, in __handle_sink_update
>     artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 139, in play
>     self, stream_url, artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 96, in play
>     cast.cleanup()
> UnboundLocalError: local variable 'cast' referenced before assignment
> 04-13 09:54:39 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream4"
> 04-13 09:54:40 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink5
> 04-13 09:54:40 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Schlafzimmer (Chromecast)" to play ...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 63, in play
>     self.ip, self.port, self.REQUEST_TIMEOUT)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 229, in __init__
>     ChromecastController.__init__(self, ip, port, timeout)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 128, in __init__
>     self.socket = cast_socket.CastSocket(ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 107, in __init__
>     BaseChromecastSocket.__init__(self, ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 46, in __init__
>     self.sock.connect((ip, port))
>   File "/usr/lib/python2.7/ssl.py", line 866, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 857, in _real_connect
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
>     self._sslobj.do_handshake()
> error: [Errno 104] Connection reset by peer
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 681, in _handle_sink_update
>     result = future.result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
>     return self.__get_result()
>   File "/usr/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 726, in __handle_sink_update
>     artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 139, in play
>     self, stream_url, artist=artist, title=title, thumb=thumb)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 96, in play
>     cast.cleanup()
> UnboundLocalError: local variable 'cast' referenced before assignment
> ^CApplication is shutting down.
> 04-13 09:54:48 pulseaudio_dlna.pulseaudio                     INFO     Remove "schlafzimmer_chromecast" sink ...
> 04-13 09:54:48 pulseaudio_dlna.pulseaudio                     INFO     Remove "wohnzimmer_chromecast" sink ...

And i got the same error.
My Guess is that Sony does sth different in their speakers then google...

**Comment by masmu** [comment]
The real problem is that error:
```python
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 63, in play
>     self.ip, self.port, self.REQUEST_TIMEOUT)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 229, in __init__
>     ChromecastController.__init__(self, ip, port, timeout)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 128, in __init__
>     self.socket = cast_socket.CastSocket(ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 107, in __init__
>     BaseChromecastSocket.__init__(self, ip, port)
>   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 46, in __init__
>     self.sock.connect((ip, port))
>   File "/usr/lib/python2.7/ssl.py", line 866, in connect
>     self._real_connect(addr, False)
>   File "/usr/lib/python2.7/ssl.py", line 857, in _real_connect
>     self.do_handshake()
>   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
>     self._sslobj.do_handshake()
> error: [Errno 104] Connection reset by peer
```

Chromecast devices use SSL connections to exchange data. And for some reason it is not able to establish a connection. The error itself comes from `/usr/lib/python2.7/ssl.py`, pythons SSL implementation. Could you start _pulseaudio-dlna_ with the following command which creates a `debug.log` in the current directory and upload it here?
`pulseaudio-dlna --debug 2>&1 | tee -a debug.log`


But I just tested that with a fresh Ubuntu 16.10 VM and it works for me. I do not get any SSL handshake errors.

**Comment by snareoj** [comment]
Here is the log:
[debug.zip](https://github.com/masmu/pulseaudio-dlna/files/918883/debug.zip)

**Comment by masmu** [comment]
I am sorry, there were no additional hints inside that. This might be a network related error. Do you use any firewall (_iptables_) or stuff like that?

What you can try is current master.
```bash
# Install the dependecies (most of them should already be installed)
    sudo apt-get install \
        python2.7 \
        python-pip \
        python-setuptools \
        python-dbus \
        python-docopt \
        python-requests \
        python-setproctitle \
        python-gi \
        python-protobuf \
        python-notify2 \
        python-psutil \
        python-concurrent.futures \
        python-chardet \
        python-netifaces \
        python-netaddr \
        python-lxml \
        python-zeroconf \
        vorbis-tools \
        sox \
        lame \
        flac \
        opus-tools \
        pavucontrol \
        virtualenv python-dev git-core
# Clone the project
    git clone https://github.com/masmu/pulseaudio-dlna.git ~/pulseaudio-dlna
    cd ~/pulseaudio-dlna
# Make it runnable
    make
# Run it
    bin/pulseaudio-dlna
```

**Comment by snareoj** [comment]
Sadly this doesnt work either.
See output in zip. I'll investigate further and try the original chromecast attached to my tv later.
Thanks for your efforts!
[master_terminal_output.zip](https://github.com/masmu/pulseaudio-dlna/files/918933/master_terminal_output.zip)

**Comment by masmu** [comment]
You are welcome and keep me posted!

**Comment by snareoj** [comment]
Hi,
status update, i have to clearify the setup:

* Two SRS ZR5s: A (="Schlafzimmer"), B (="Wohnzimmer 2")
* They were set to "Stereo" originally, but i set A to normal mode, B then blinked and i even couldn't connect to it via Sonys Music Center APP
* Both weren't allowed to connect to the internet due to router config

What i changed now:
* B now is in normal mode, too - Sonys Music Center APP now finds it again
* A+B were allowed to connect to the internet

Result: 
- The SSL Handshake Error isn't there anymore
- Sonys Music Center App shows that the speaker is now in "Chrome Cast" Mode
- No sound is played

[debug.2.log.zip](https://github.com/masmu/pulseaudio-dlna/files/921544/debug.2.log.zip)

It seems like i have a problem with understanding how chrome cast audio works. I tried to play music via Googles Play Music App (Nexus 9 Android 7.1.1) - playing the files locally on the tablet works. But if i connect to the speaker via Chrome Cast it says it cant play the music because i have to upload them into the Play Music Cloud - what i definitely dont want to do.

So it is not a problem with pulseaudio-dlna, its a problem with cast itself...
Sorry for any inconvenience.

Regards

**Comment by masmu** [comment]
Glad that you found the error. But I am not quite sure if you are able to stream to the Chromecasts. And your log is stopping unexpectedly. Are you using a firewall (e.g. iptables) on your computer?

**Comment by snareoj** [comment]
I downloaded the firewall frontend from ubuntu and it seems it were active.
With deactivated firewall i see the DLNA clients.
In the log i first clicked on the chromecast "Test speakers" and after that on the DLNA "Test Speakers".

But both times no sound.

![bildschirmfoto vom 2017-04-14 09-14-19](https://cloud.githubusercontent.com/assets/20535756/25036220/c8380788-20f2-11e7-9b58-a14a098b2e5d.png)
[debug.log.zip](https://github.com/masmu/pulseaudio-dlna/files/921637/debug.log.zip)

**Comment by masmu** [comment]
Your log looks fine. The firewall should be disabled, or you need to open 2 ports. But the test sound might be too short. Open a media / audio or just goto youtube and play something...

**Comment by snareoj** [comment]
Hi, the hint with the test sound being to short was good... with VLC streaming both chromecast and DNLA works. Hurray! Thanks for your help.

**Comment by masmu** [comment]
Cool that is works. 2 more hints:
- You can group Chromecasts with the Android Home app. Works awesome.
- I prefer to use `pavucontrol` instead of the systems default sound panel because there you can set single streams to certain sinks instead of redirecting really everything. So it is possible to just send the audio players stream to the Chromecasts, but not terminal bells or others system sounds.

**Comment by snareoj** [comment]
Thanks for the hints, i'll have a look.
And a big thanks again for your time and your help!

**Comment by masmu** [comment]
You are welcome!

**Comment by zhartaunik** [comment]
I have similar issue, but it's not clear to me how it can be solved, can you also help me?

```
03-30 09:22:17 pulseaudio_dlna.pulseaudio                     DEBUG    
<Bridge>
    <PulseSink path="/org/pulseaudio/core1/sink3" label="Гостиная (Chromecast)" name="_chromecast" index="3" module="30">
        <PulseStream path="/org/pulseaudio/core1/playback_stream29" device="/org/pulseaudio/core1/sink3" index="29" client="22">
        <PulseStream path="/org/pulseaudio/core1/playback_stream70" device="/org/pulseaudio/core1/sink3" index="70" client="40">

    <CoinedChromecastRenderer name="Гостиная" short="_chromecast" state="idle" udn="uuid:93135916dbacb9b741a8f177d78c94a0" model_name="Chromecast Audio" model_number="None" model_description="None" manufacturer="Google Inc." timeout="15.0">

03-30 09:22:17 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Гостиная (Chromecast)" to play ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 68, in play
    self.ip, self.port, self.REQUEST_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 229, in __init__
    ChromecastController.__init__(self, ip, port, timeout)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/__init__.py", line 128, in __init__
    self.socket = cast_socket.CastSocket(ip, port)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 107, in __init__
    BaseChromecastSocket.__init__(self, ip, port)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/pycastv2/cast_socket.py", line 46, in __init__
    self.sock.connect((ip, port))
  File "/usr/lib/python2.7/ssl.py", line 882, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 873, in _real_connect
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 693, in _handle_sink_update
    result = future.result()
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 738, in __handle_sink_update
    artist=artist, title=title, thumb=thumb)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 144, in play
    self, stream_url, artist=artist, title=title, thumb=thumb)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 101, in play
    cast.cleanup()
UnboundLocalError: local variable 'cast' referenced before assignment
03-30 09:22:21 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()

```
