### ISSUE TITLE
flac transcoding error

### ISSUE THREAD

**Issue by D-i-d-i** [masmu/pulseaudio-dlna#31]
Hello !

Thank you for this work, it's very usefull (the systray support by queeup is awesome too) !

My request is about the flac encoder. When I launch the server with this options, it doesn't work.

This is what I see when the stream begin :

> INFO:root:starting sending stream to "Server PreAmpli"
>
> flac 1.3.0, Copyright (C) 2000-2009, 2011-2013  Josh Coalson & Xiph.Org Foundation
> flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are welcome to redistribute it under certain conditions.  Type `flac' for details.
> 
> (No runtime statistics possible; please wait for encoding to finish...)
> INFO:root:PulseWatcher.on_new_playback_stream "/org/pulseaudio/core1/playback_stream176"
> INFO:root:PulseWatcher.on_playback_stream_removed "/org/pulseaudio/core1/playback_stream176"

(The part where the encoder is launched appears just once ;) ). The stream is closed just after it is opened ...

Is there something I set wrong ?

**Comment by masmu** [comment]
@D-i-d-i 

What is the device you want to stream your music to?
In _0.3.4_ the stream server may hang up to 20 seconds before cleaning up your stream. In that time it may not initialize a new stream if you change your streams. (I am not sure about that, but it may be)

Did you retried it a few times to give some more information under which circumstances this happens?
A ```--debug``` output would be great too.

**Comment by wannesvl** [comment]
I'm not sure if my issue is related, but also immediately after starting a stream it closes when using the flac encoder ([debug log](http://pastebin.com/g1Psxi4n)). It seems only the mp3 stream is working on my device (Audiopro Allroom Air One), but obviously I prefer flac.

**Comment by masmu** [comment]
Closed due to inactivity
