### ISSUE TITLE
Chromecast not working through DLNA

### ISSUE THREAD

**Issue by dejmail** [masmu/pulseaudio-dlna#317]
Hi there

Would like to be able to debug why my casting through the DLNA interface has stopped working. I'm running Xubuntu 16.04 64, pulseaudio-dlna 0.5.2, pulseaudio 8.0.

I know there is nothing wrong with the Chromecast Audio device, because I can cast using the Chrome browser. When I try to cast using the DLNA interface however, I hear the connecting "beep" and the audio looks to be playing, but there is no audible audio. The debug output of running "pulseaudio-dlna" shows no particular errors, so I'm not sure what the problem is. Would be most appreciative of some pointers that I could try to debug this.

### Pavucontrol
![pavucontrol](https://user-images.githubusercontent.com/1876487/27769858-a94a154e-5f33-11e7-9277-c5b98a830c6c.png)

### DLNA Debug Output
[debug_output.txt](https://github.com/masmu/pulseaudio-dlna/files/1117787/debug_output.txt)

**Comment by masmu** [comment]
Is this still up to date?

Maybe a stupid advice... But did you check if the volume of the Chromecast was actually up and also not muted?

**Comment by dejmail** [comment]
Not stupid at all. The parec recording volume was muted, which then muted the Chromecast. Once I unmuted that it played fine. Apologies for missing something so trivial. There is probably a good reason this happens, just not sure what t is.


![untitled](https://user-images.githubusercontent.com/1876487/27983162-278e8b02-63b6-11e7-9161-8d3b547089ec.png)
