### ISSUE TITLE
How do you use this with Chromecast on a TV?

### ISSUE THREAD

**Issue by w0rp** [masmu/pulseaudio-dlna#319]
This program looks like a good Idea to me. I was able to install the program via apt, running it prints "Added the device ..." in the console, and playing some music via XMMS2 or something else prints various messages about sinks and streams. I can't get anything to play on my TV, though.

Chromecast usually involves some kind of splash screen appearing on the TV, and then something appearing on the TV and playing on the TV. I don't see this. Are there any options that need to be used to get the program to connect to Chromecast?

**Comment by masmu** [comment]
Did you maybe miss the part about `pavucontrol`? This is a sound control app which can switch your applications sound streams to your devices.

Basically after you started `pulseaudio-dlna` start `pavucontrol` and switch an applications sound stream to the device you want to. By the way, this step is being shown in the screenshot which is embedded in the readme.

**Comment by w0rp** [comment]
I managed to get XMMS2 to stream audio to the device, but I don't understand how to cast audio to Chromecast on a TV.

**Comment by masmu** [comment]
Same way. Just select the Chromecast from pavucontrol as a target.

**Comment by w0rp** [comment]
Okay, thanks! I'll give a go another time.

I wish that GitHub had some way of sending messages to users without creating issues. Creating an issue is typically the only what I can ask these kinds of questions.

**Comment by masmu** [comment]
No worries. Chromecasts should always work. If you still have problems don't hesitate to ask.
