### ISSUE TITLE
Sonos UPNP support

### ISSUE THREAD

**Issue by alois74** [masmu/pulseaudio-dlna#32]
Hello!

First thank you very much for pulseaudio-dlna! It works great with BubbleUPNP on my Android device!
But when I try to use it with my Sonos speakers I get the following error:
ERROR:dbus.connection:Exception in handler for D-Bus signal:                                                        
Traceback (most recent call last):                                                                                  
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message                     
    self._handler(*args, **kwargs)                                                                                  
  File "/usr/local/src/pulseaudio-dlna-master/pulseaudio_dlna/pulseaudio.py", line 259, in on_device_updated        
    self._handle_sink_update(sink_path)                                                                             
  File "/usr/local/src/pulseaudio-dlna-master/pulseaudio_dlna/pulseaudio.py", line 294, in _handle_sink_update      
    if bridge.upnp_device.register() == 200:                                                                        
  File "/usr/local/src/pulseaudio-dlna-master/pulseaudio_dlna/upnp/renderer.py", line 253, in register              
    return UpnpMediaRenderer.register(self, self.stream_url)
  File "/usr/local/src/pulseaudio-dlna-master/pulseaudio_dlna/upnp/renderer.py", line 141, in register
    url = self._get_av_transport_url()
  File "/usr/local/src/pulseaudio-dlna-master/pulseaudio_dlna/upnp/renderer.py", line 118, in _get_av_transport_url
    return self._get_url(av_transport['control_url'])
TypeError: 'NoneType' object has no attribute '__getitem__'

Technically streaming to Sonos should work as I am able to stream to my Sonos devices when using BubbleUPNP. Are there any debugging infos I could additionally send to help to get pulseaudio-dlna work with Sonos?

Thanks a lot
Alois

**Comment by masmu** [comment]
Which devices is it exactly?

Could you provide a debug.log?

```pulseaudio-dlna --debug 2>&1 | tee -a debug.log```

**Comment by ryanroth** [comment]
I have the same issue. Here is a debug:

https://www.dropbox.com/s/cdj16x25gjsxaw7/debug.log?dl=0

**Comment by masmu** [comment]
@ryanroth @alois74 

Could you please check the new version?

 * __0.3.5__ - (_2015-04-09_)
    - Fixed a bug where Sonos description XML could not get parsed correctly

**Comment by ryanroth** [comment]
Exception happened during processing of request from ('192.168.0.108', 47816)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "build/bdist.linux-x86_64/egg/pulseaudio_dlna/upnp/server.py", line 32, in __init__
    BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/pulseaudio_dlna/upnp/server.py", line 50, in do_GET
    recorder_process, encoder_process = self.create_processes(bridge)
  File "build/bdist.linux-x86_64/egg/pulseaudio_dlna/upnp/server.py", line 77, in create_processes
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by ryanroth** [comment]
It doesn't error out now. It appears the stream starts and then stops immediately 

192.168.0.108 - - [09/Apr/2015 18:02:47] "GET /1921680108sonosplay1.stream HTTP/1.1" 200 -
INFO:root:"192.168.0.108 - Sonos PLAY:1" is playing.
INFO:root:starting sending stream to "192.168.0.108 - Sonos PLAY:1"
192.168.0.108 - - [09/Apr/2015 18:02:47] "HEAD /1921680108sonosplay1.stream HTTP/1.1" 200 -
INFO:root:stream closed. cleaning up remaining procecces

**Comment by ryanroth** [comment]
From the Sonos

 Transport error ERROR_CORRUPT_FILE for account type 0, URI: http://192.168.0.10:12380/1921680108sonosplay1.stream, friendly name: Live Audio, share/server: 192.168.0.10:12380, path: http://192.168.0.10:12380/1921680108sonosplay1.stream, extra info: , http: -1

**Comment by masmu** [comment]
@ryanroth 
Could you provide a debug.log for that as well? Because it really helps to find out what is really going on.

From what i can see now, your Sonos device does not recognize the stream encoding (i assume that you are using the default encoder) mp3. It might be, that the default bitrate of 320 is to high.

Did you try to use other encoders?
```pulseaudio-dlna --encoder ogg``` for Ogg Vorbis
```pulseaudio-dlna --encoder flac``` for Flac
```pulseaudio-dlna --encoder wav``` for Wav

Which linux do you use? Ubuntu?
Which version?
Did you install it by the _ppa_ or did you clone from git?

**Comment by ryanroth** [comment]
I tried wav and flac with the same results. Sonos supports 320kbps mp3s.  I cloned from git.  I will try to grab debugs later today.

~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
~$ uname -a
Linux friscojack 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ryanroth@friscojack:~$

**Comment by ryanroth** [comment]
Debug
https://www.dropbox.com/s/cdj16x25gjsxaw7/debug.log?dl=0

**Comment by masmu** [comment]
@ryanroth Could you try the [streaming-server branch](https://github.com/masmu/pulseaudio-dlna/tree/refactor/streaming-server)?

There are many enhancements included, also your XML fix and another fix which might solve your issue.
If it does not work straight away, you can adjust the encoder and the bitrate (as far these support that) with the `--encoder` and `--bit-rate` options to figure things out.

Just a note: Nearly all encoders default bitrate is now set to 192 kbit/s.

Keep me posted.

**Comment by ryanroth** [comment]
Ok. I tested it and no go.  But I'll mess with it more this weekend.

**Comment by masmu** [comment]
Please update the streaming-server branch. I added some additional DLNA headers and added more debug code.

When it does not work, please don't forget to paste another _debug.log_

**Comment by ryanroth** [comment]
The updated branch errors out when I run it

https://www.dropbox.com/s/cdj16x25gjsxaw7/debug.log?dl=0

**Comment by masmu** [comment]
@ryanroth Sorry for that.

That should be fixed. I updated the branch. Do a ```git pull``` and try again please.

**Comment by ryanroth** [comment]
It now works. Still a bit glitchy depending on the audio import format it seems. I'll try to spend some time with it this week to gather better information and debugs.

**Comment by ryanroth** [comment]
This appears to be working properly.

**Comment by masmu** [comment]
Good to hear :smile: 

Thanks for your feedback!
Which device did you test exactly? I want to add it to the list of tested devices.

**Comment by ryanroth** [comment]
A single PLAY:1, two PLAY:1s in a stereo pair, and a single PLAY:3 all separately, and then all five of my speakers grouped together.  All the grouping was done through the Sonis app.

I also have a couple feature requests/suggestions where would you like those posted?

**Comment by masmu** [comment]
Thanks.

Just open new issues please. One for each to keep things seperate.

**Comment by githob** [comment]
If I am not mistaken, you changed README.md in the master branch, but the files in that branch still doesn't support Sonos. I have Sonos PLAY:5 and wanted to test it using "sudo apt-get install pulseaudio-dlna" but it is not working. Hopefully the next version 0.3.6 supports it and I will test it so you can add it to your list of tested devices :)

**Comment by ryanroth** [comment]
You need to change branches to the streaming-server branch

**Comment by masmu** [comment]
Yeah, i pushed it the the wrong branch. Thanks for the hint!

**Comment by alois74** [comment]
Sorry for not responding earlier, but I forgot to enable e-mail notifications and therefore didn't realize that some approaches on solving were already going on.
When I try to run the refactoring-streaming-server (downloaded via zip) no streaming devices are found.
When starting the (newly) downloaded master branch, still no sound :-(
Is there a difference between a git pull and the zip-Download on the page?
Sorry, but I am no developer and a git-newby.
Debug.log (from master branch): https://www.schmid-alois.de/owncloud/index.php/s/42fcm1cxNP87OMI

**Comment by githob** [comment]
When is the next version (0.3.6) planned?

**Comment by alois74** [comment]
Ich bin von Mo, 13.07.2015 bis Mo, 20.07.2015 abwesend.

Ich werde Ihre Nachrichten nach meiner Rückkehr beantworten.

In dringenden Fällen können Sie sich an Hr. Stephan Unsin (089/2868-3280,
sunsin@gv-bayern.de) wenden.

Mit freundlichen Grüßen
Alois Schmid


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[pulseaudio-dlna] Sonos UPNP support (#32)" gesendet am 18.07.2015 08:07:27
.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by masmu** [comment]
* __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies
