### ISSUE TITLE
Chrome cast audio version 1.35.137090 cannot be discovered

### ISSUE THREAD

**Issue by minsonj2016** [masmu/pulseaudio-dlna#357]
I dont believe this is a pa-dlna issue .
After my 2 chromecast audios got updated to 1.35.137090 they are no longer detected by pa-dlna .
I installed 'gssdp-discover' and it does not see them either .
Both pa-dlna and gssdp-discover do see my regular chromecasts and my 'smart' tv's .

I have opened a ticket with google but I am not hopeful of a resolution .

'HI-FI Cast' on my android tablet still sees the 2 cc audios and plays to them no problem

**Comment by ghomem** [comment]
I'm trying to use pulseaudio-dlna on Ubuntu 16.04 but my Chromecast is not found either. It is an HDMI Chromecast purchased 1 year ago. Chrome streams tabs correctly into it and mobile apps such as youtube also work fine.

Attaching console output.
[pulse-audio-dlna-debug.txt](https://github.com/masmu/pulseaudio-dlna/files/2540303/pulse-audio-dlna-debug.txt)

**Comment by ghomem** [comment]
Interestingly, I can discover the url of the device with:

`sudo apt install gupnp-tools
gssdp-discover`

and connect manually by means of:

`pulseaudio-dlna --renderer-urls http://THEIP:8008/ssdp/device-desc.xml`

**Comment by ghomem** [comment]
Interestingly, I can discover the url of the device with:

`sudo apt install gupnp-tools`
`gssdp-discover`

and connect manually by means of:

`pulseaudio-dlna --renderer-urls http://THEIP:8008/ssdp/device-desc.xml`

**Comment by minsonj2016** [comment]
Is your device a chromecast audio ?
If so what is its firmware version ?

**Comment by minsonj2016** [comment]
oops I missed your 'it is an HDMI' .
The issue I described is specific to chromecast audios

**Comment by ghomem** [comment]
I understand the issue referred to a chromecast audio but I added the comment here because without knowning the protocol details I imagine that the discovery part is independent from the capabilities part (audio, video).

My Chromecast accepts audio from pulseaudio-dlna but the auto discovery does not work, just like in your case.

I can open a separate issue if necessary and I can more provide more debug info.

**Comment by minsonj2016** [comment]
If I could figure out the cca's url I would try '--renderer-urls'  but so far no luck

**Comment by ghomem** [comment]
> If I could figure out the cca's url I would try '--renderer-urls' but so far no luck

`sudo apt install gupnp-tools`
`gssdp-discover`

**Comment by minsonj2016** [comment]
gssdp-discover does not detect the cca's

**Comment by minsonj2016** [comment]
avahi-browse does find them and gives me , for example , this 

= enp1s0 IPv4 Chromecast-Audio-7c962882093bfd5c52abc190be97daa4 _googlecast._tcp     local
   hostname = [7c962882-093b-fd5c-52ab-c190be97daa4.local]
   address = [192.168.1.136]
   port = [8009]
   txt = ["rs=" "nf=2" "bs=FA8FCA851A6D" "st=0" "ca=2052" "fn=ccAden" "ic=/setup/icon.png" "md=Chromecast Audio" "ve=05" "rm=" "cd=E5B084398B14367398FF709A7B05516F" "id=7c962882093bfd5c52abc190be97daa4"]

so what the 'url' is still not clear

**Comment by minsonj2016** [comment]
I am closing this as I feel the issue maybe caused by some weird router issue.
I have an old laptop running Fedora 29 on which pa-dlna works fine .
I also have a MacBookPro  which cannot discover the cca's .

Clueless right now
