### ISSUE TITLE
Add possibility for periodic polling for new UPnP devices

### ISSUE THREAD

**Issue by coder-hugo** [masmu/pulseaudio-dlna#36]
At the moment the application looks at the startup for UPnP devices. If it has found devices it will continue otherwise it stops. If the application runs and some of the UPnP devices are gone in the meantime the application won't recognize this.
This make it impossible to run this cool application as a daemon. Therefore it would be nice if you could add another option that enables a periodic polling for UPnP devices instead of the one time search. A second option for the polling interval would be nice as well.

**Comment by masmu** [comment]
This is planned, but this there are currently other things to do.
I will have to rewrite a lot of memory management code to make that happen.
Besides that, the major change to _systemd_ makes that even harder. So, I don't want to support _upstart_ anymore.

I am sorry but this will take a while.

**Comment by coder-hugo** [comment]
I'm not familiar with *upstart* but a played already a lot with the *systemd* as this is the default init system of Archlinux for a long time. And I think using the *systemd* makes it even simpler to create a daemon. In the end your application has to do nothing special to run with the *systemd*. If the application writes it log output to stdout the *systemd* will automatically redirect this to a "log file" (in the end it's more than a log file, but for this explanation log file should be ok). The application should implement a "shutdown" for the SIGINT signal so it exits clean on a `systemctl stop <deamon>.service`.
Also for the SysVinit an application that should run as a daemon has to act like a normal application. Therefore I assume it's something similar with *upstart*.
In the end there is no reason why the application should decide which init system should be used to daemonize it. This is part of the distribution (and the distributor of the package). So the *upstart* or *systemd* configuration should be part of the debian packaging stuff mentioned in #37.

**Comment by masmu** [comment]
So, in that case for Ubuntu i am the distributor, right?

**Comment by coder-hugo** [comment]
Right.
Btw. I read some documentations about UPnP and recognized that all clients send a periodic advertisement message and also a byebye message if they shutdown. So it's not necessary to poll periodically for all available UPnP cleints instead a UDP server should be implemented that listens for these messages. I had already a look to your code and have some ideas how to implement this. If I find some time I'll add this functionality and provide it as pull-request to you.

**Comment by masmu** [comment]
I really appreciate your efforts.

I recommend you to take a look at the [refactor/streaming-server](https://github.com/masmu/pulseaudio-dlna/tree/refactor/streaming-server) branch. It turned to be my actual development branch, and i changed the whole structure of the application.
Note, that there is _Chromecast_ support in that and i am thinking about more protocols to support.
So every change has to be thought of all protocols (DLNA, Castv2, maybe others) and not just DLNA.

But see what you can manage, patches welcome! :smile:

**Comment by martininsulander** [comment]
Just a small idea (thou I'm not that experienced in this area).

What about using Avahi? As I understand it this is made just that task.
See http://www.avahi.org/wiki/PythonBrowseExample

**Comment by masmu** [comment]
@martininsulander 
_Avahi_ would just be a replacement for the discovery module. But the module itself is fine. 
The problem is how all the different modules are wired together.
As it is now, even if you would keep going detecting more devices they would not be used.
Rewiring the modules is the real task.

**Comment by masmu** [comment]
@coder-hugo 
I just pushed some code which makes _pulseaudio-dlna_ runnable as root.
So, if this looks okay, it should be very simple to make it run as a system service.

Since you are pretty familiar with the code, I would really appreciate if you take a look at this.

**Comment by masmu** [comment]
* __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies
