### ISSUE TITLE
Not So Dead Project

### ISSUE THREAD

**Issue by minsonj2016** [masmu/pulseaudio-dlna#374]
Is this project dead ?

the copr repo for the Fedora version is only valid thru Fedora 28

**Comment by polyzen** [comment]
Currently, yes.

**Comment by Cygn** [comment]
copr owner here:
with Fedora  move to python3 and zeroconf python2 dropped, its too much hassle to package it for 29. There is a python3 fork somewhere on github and I'll look at it when I'll find 2 minutes.

**Comment by masmu** [comment]
Okay, I am looking into the python3 port.

Am 31. Januar 2019 09:15:49 MEZ schrieb Cygn <notifications@github.com>:

**Comment by Cygn** [comment]
oh, nice to hear from you @masmu !
check https://github.com/aharter/pulseaudio-dlna/tree/python3 but I've seen also couple of others.
Maybe @aharter can make a PR back?

**Comment by minsonj2016** [comment]
Thats too bad  . It seems that a solution like this makes more sense than each application having to 'roll its own' .

**Comment by masmu** [comment]
@Cygn Hi :smile: I took a look at the various ports and the one from @aharter was the best. (If you are reading this @aharter, great work! :+1: ) So I took that as a starting point. And here it is [pulseaudio-dlna/python3](https://github.com/masmu/pulseaudio-dlna/tree/python3). This is my first attempt, quite some stuff changed. Testings very welcome!

**Comment by minsonj2016** [comment]
Whats up with

	Upgrade to python3, disable chromecast support

Chromecast suppport is what I loaded this for :}

**Comment by polyzen** [comment]
On February 1, 2019 9:18:15 AM EST, minsonj2016 <notifications@github.com> wrote:
>Whats up with
>
>	Upgrade to python3, disable chromecast support
>
>Chromecast suppport is what I loaded this for :}

Look at the more recent commits.

--
Best,
polyzen

**Comment by minsonj2016** [comment]
oops. 
trying to 'make' on Fedora 29 I get to this configure error


checking for GLIB... no
  configure: error: Package requirements (glib-2.0 >= 2.40) were not met:
  
  Package 'glib-2.0', required by 'virtual:world', not found

Checking with dnf  list I see

dnf list | grep glib2
glib2.x86_64                                                           2.58.3-1.fc29                                                   @updates                 
glib2-devel.x86_64                                                     2.58.3-1.fc29                                                   @updates                 
pulseaudio-libs-glib2.x86_64                                           12.2-1.fc29                                                     @anaconda

**Comment by masmu** [comment]
@minsonj2016 I have no clue what this could be. This doesn't look like my Makefile. Maybe this is a Fedora issue? Normal `make` is working fine here. After that start it with `bin/pulseaudio-dlna`

**Comment by minsonj2016** [comment]
Well in spite of all the noise generated by 'make' the binary was generated and a brief test shows it to be working . I will test some more .

**Comment by minsonj2016** [comment]
I am seeing some these though it still is working . I believe ip 131 is a Samsung TV .

exception happened during processing of request from ('192.168.1.131', 1025)
Traceback (most recent call last):
  File "/usr/lib64/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/theuser/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/dlna/ssdp/listener.py", line 48, in handle
    self.server.cb_on_device_alive(header)
  File "/home/theuser/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/__init__.py", line 39, in wrapper
    self.holder.add_device(device)
  File "/home/theuser/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/holder.py", line 109, in add_device
    device.activate(config)
  File "/home/theuser/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/dlna/renderer.py", line 70, in activate
    mime_types = self.get_mime_types()
  File "/home/theuser/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/dlna/renderer.py", line 217, in get_mime_types
    logger.error('"{}" : {}'.format(self.label, str(e)))
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by masmu** [comment]
@minsonj2016 Thanks for the bug. I take care about this later tonight.

**Comment by masmu** [comment]
@minsonj2016 I updated the branch. Can you please try it again?

**Comment by minsonj2016** [comment]
OK , now  issue with TV is logged

 02-05 09:22:55 pulseaudio_dlna.plugins.dlna.renderer          ERROR    "TV-32C6500 (DLNA)" : The action "GetProtocolInfo" is not supported!
02-05 09:22:55 pulseaudio_dlna.pulseaudio                     INFO     Added the device "TV-32C6500 (DLNA)".

This is not the forum for this question but I'm going to ask any way . The only way I can 'get' your python3 updates is to download the .zip . I have not found any 'git' command that pulls them .  Not sure what I'm doing wrong .

Back to testing python3 branch I looped Amarok over 15 songs playing to a chromecast audio  for > 6 hours with no issues.

**Comment by polyzen** [comment]
> I have not found any 'git' command that pulls them . Not sure what I'm doing wrong .

`git clone https://github.com/masmu/pulseaudio-dlna.git && git checkout python3`
or
`git clone --branch python3 --single-branch https://github.com/masmu/pulseaudio-dlna.git`

**Comment by masmu** [comment]
> The action "GetProtocolInfo" is not supported!

That error describes that the TV does not support to be streamed to. Some TVs are just remove controllers for other DLNA devices and therefore they are lacking that feature. Can you check an old (0.5.x) version of pulseaudio-dlna, to make sure thats not a new bug I brought into the game?

**Comment by minsonj2016** [comment]
5.2 doesnt throw that error

02-06 18:39:10 pulseaudio_dlna.pulseaudio                     INFO     Added the device "cclivingroom (Chromecast)".
02-06 18:39:10 pulseaudio_dlna.pulseaudio                     INFO     Added the device "TV-32C6500 (DLNA)".
02-06 18:39:15 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()

for what its worth I dont care about the TV

**Comment by minsonj2016** [comment]
and the second form of the 'git' command did the trick . I thought I tried that but seems not .
Thanks

**Comment by polyzen** [comment]
Working well from preliminary tests. Will try to test more tomorrow.

I had to remove `"dbus-python >= 1.0.0"` from `setup.py` as I couldn't get the line to work even with `"dbus-python == 1.2.8"` or `"dbus == 1.2.8"` (the installed/latest version).

**Comment by masmu** [comment]
@minsonj2016 Then you found a bug. Could you please create a log via 
`pulseaudio-dlna --debug 2>&1 | tee -a debug.log`
and pastebin that somewhere? I guess a lot of other people would not be very pleased about that :wink:

**Comment by minsonj2016** [comment]
[debug.log](https://github.com/masmu/pulseaudio-dlna/files/2844865/debug.log)

**Comment by polyzen** [comment]
Another note is that it would be great if the `pychromecast` dep were optional.

**Comment by jleclanche** [comment]
@masmu Thanks for your work on this, I'll be packaging pulseaudio-dlna on Arch Linux as soon as Python 3 support is released :)

For the record, in the future if you want help maintaining the package, I'd like to suggest bringing it into [the Code Shelter](https://www.codeshelter.co).

**Comment by polyzen** [comment]
@jleclanche, oy, as the current `pulseaudio-dlna` AUR maintainer, I think I have dibs :p. It would've already been in the repos if I weren't having issues (which have seemed to pass), but now I figure I might as well wait for the next release.

Edit: But you are definitely welcome to co-maintain it and its deps.

**Comment by jleclanche** [comment]
@polyzen didn't realize! Woops.

**Comment by ehoitinga** [comment]
Sorry if this is a noob question, I am not that experienced with github. I see that there are a lot of branches. These branches (and especially the python3 one), will they be eventually be merged in the master?

Does it make sense for me to try the python3 branch to see if some of my issues mentioned in [this](https://github.com/masmu/pulseaudio-dlna/issues/373) post are are solved?

Thanks and sorry to bother you.

Erik

**Comment by masmu** [comment]
@minsonj2016 I updated the `python3` branch. Could you do a `git pull` and check if your TV issue is resolved?

**Comment by masmu** [comment]
@polyzen About the optional `pychromecast` dependency. May I ask why? And by the way, thank you for packaging this to Arch.

**Comment by masmu** [comment]
@jleclanche Thank you for the suggestion. This might be something for my own Ubuntu PPA.

**Comment by masmu** [comment]
@ehoitinga Sure, once this is ready I'll merge it back to master. But currently I am refactoring a lot of the code to make it more maintainable.

**Comment by minsonj2016** [comment]
02-09 07:58:03 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()
02-09 08:02:37 pulseaudio_dlna.pulseaudio                     INFO     Added the device "TV-32C6500 (DLNA)".

**Comment by polyzen** [comment]
> @polyzen About the optional `pychromecast` dependency. May I ask why?

It would be nice to not have it and its deps installed as I don't have any Chromecasts.

> And by the way, thank you for packaging this to Arch.

Glad I was able to snag it. :)

**Comment by Cygn** [comment]
> Is this project dead ?
> 
> the copr repo for the Fedora version is only valid thru Fedora 28

I've setup the copr repo for F29 with 0.6.0 (python3). 
Testing welcome.

**Comment by ehoitinga** [comment]
> > Is this project dead ?
> > the copr repo for the Fedora version is only valid thru Fedora 28
> 
> I've setup the copr repo for F29 with 0.6.0 (python3).
> Testing welcome.

I tried to install pulseaudio-dlna on Fedora 29 (yes @masmu I'm trying Fedora...) using the following commands:

```
sudo dnf install  flac
sudo dnf install  lame
sudo dnf install  opus-tools
sudo rpm -Uvh rrpmfusion-nonfree-release-29.noarch.rpm
sudo dnf install faac-devel
sudo dnf copr enable cygn/pulseaudio-dlna
sudo dnf install pulseaudio-dlna
```

When I try to start pulseaudio-dlna I get an error messages by setup.py saying that the version of ps-util is too old. The version installed in Fedora 29 is python3-psutil-5.4.3-6.fc29.x86_64 and the version needed is psutil>=5.4.7.

On pkgs.org I do not find a newer version for Fedora 29.

Erik

**Comment by Cygn** [comment]
> I tried to install pulseaudio-dlna on Fedora 29 (yes @masmu I'm trying Fedora...) using the following commands:
> 
Welcome to Fedora ! you'll like it here :smile:  
> ```
> ..
> sudo dnf install pulseaudio-dlna
> ```
> 
> When I try to start pulseaudio-dlna I get an error messages by setup.py saying that the version of ps-util is too old. The version installed in Fedora 29 is python3-psutil-5.4.3-6.fc29.x86_64 and the version needed is psutil>=5.4.7.

Can you please check that you've got the release -5 ?  
$ rpm -qa pulseaudio-dlna                                                                      
pulseaudio-dlna-0.6.0 **-5** .noarch

I've disabled all require checks from setup.py in this one because they are already handled at rpm install time.

If you are still on -3 or -4 just 
$ dnf update **--refresh**

**Comment by minsonj2016** [comment]
I enabled and installed the Fedora 29 version and its working so far

$ rpm -qa pulseaudio-dlna
pulseaudio-dlna-0.6.0-5.noarch

**Comment by ehoitinga** [comment]
@Cygn and @minsonj2016,

Ok, `dnf update --refresh` did the trick. Indeed I was on version -4.

Sorry as you know I'm a bit new on Fedora. Does the command `dnf update --refresh` refreshes the complete repository or just pulseaudio-dlna? Have to do some reading starting with the differences between yum, dnf and rpm. So far I'm really starting to like Fedora. First impression is that it is faster and more stable than mint and preinstalled software and kernel are of a far more newer version than in Mint.

For now Fedora lives in VirtualBox and I'm trying to install/testing the extra software I use on Mint.

Thank you guys,

Erik

**Comment by Cygn** [comment]
> Does the command `dnf update --refresh` refreshes the complete repository or just pulseaudio-dlna? 
It refreshes all repo indexes. It does it by itself every 2-3 deays, but just in case you have to force it and you know a newer version has come up.

Have to do some reading starting with the differences between yum, dnf and rpm. So far I'm really starting to like Fedora. First impression is that it is faster and more stable than mint and preinstalled software and kernel are of a far more newer version than in Mint.
> 
Indeed.

> 
> Thank you guys,

Cheers,

S
