### ISSUE TITLE
FEATURE REQ:  DLNA Renderer

### ISSUE THREAD

**Issue by ilpillo** [masmu/pulseaudio-dlna#47]
This is a feature request:
I was wondering if Pulseaudio-dlna will ever act as a DLNA Media Renderer,
The scenario is: 
Laptop or desktop computer (Pulseaudio-dlna) connected to a HiFi set with a good pair of speakers.
You and all of your house guests can reproduce the music that you have on the phones. Super!
No more usb cables copying files back and forth!
Thank you for sharing

**Comment by masmu** [comment]
@ilpillo Have you ever heard of [cocy](https://github.com/mnlipp/CoCy) ?
It is a software DMR you can install to your system.

**Comment by ilpillo** [comment]
I also found this one:
https://github.com/hzeller/gmrender-resurrect
Thank you
