### ISSUE TITLE
Dbus or pulse audio not starting on Fedora 

### ISSUE THREAD

**Issue by glennpierce** [masmu/pulseaudio-dlna#48]
After running https://github.com/masmu/pulseaudio-dlna

Results in something like

<CoinedUpnpMediaRenderer name="Upstairs" short_name="upstairs" state="idle">
<CoinedUpnpMediaRenderer name="Kodi (Tardis)" short_name="koditardis" state="idle">
<CoinedUpnpMediaRenderer name="Livingroom" short_name="livingroom" state="idle">
INFO:root:You can now use your upnp devices!
DEBUG:root:setting stream url for Upstairs to "http://192.168.1.65:8080/upstairs.stream"
DEBUG:root:setting stream url for Kodi (Tardis) to "http://192.168.1.65:8080/koditardis.stream"
DEBUG:root:setting stream url for Livingroom to "http://192.168.1.65:8080/livingroom.stream"
Failure: Module initialization failed
ERROR:root:PulseAudio seems not to be running or pulseaudio dbus module could not be loaded.

pacmd list-modules | grep dbus
	name: <module-dbus-protocol>

Has this issue been seen ?

Thanks

**Comment by masmu** [comment]
Which operation system do you use? On Ubuntu this should not happen ...
On other linux distributions you may have to install it manually.

Try a:
```pactl load-module module-dbus-protocol```

It that works it will also in _pulseaudio-dlna_. If not, install the dbus module for pulseaudio and try again.

**Comment by glennpierce** [comment]
Fedora 20
I added some more logging to the exception handler and got 

ERROR:root:org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files

Sure enough I can't see that session bus or anything todo with pulseaudio using d-feet dbus inspector.

**Comment by glennpierce** [comment]
I have tried on Fedora 21 and I can see devices now.
Nothing plays but its a start.

**Comment by masmu** [comment]
At least Kodi should play if you enable UPNP in the kodi settings. What are the other both devices?

**Comment by glennpierce** [comment]
I needed lame installed . Thought I had it.
All seems to work except spotify becomes choppy and distorted if the volume is changed. I don't think
that has anything to do with pulseaudio-dlna though.  Opensource apps playing local music works fine.

Thanks
