### ISSUE TITLE
systray support

### ISSUE THREAD

**Issue by queeup** [masmu/pulseaudio-dlna#5]
I made systray application for pulseaudio_dlna. I just test it on Linuxmint with Cinnamon.

[pulseaudio-dlna-systray](https://github.com/queeup/pulseaudio-dlna-systray)

Stop menu item need signal-handler support for working proper.

**Comment by masmu** [comment]
Hey, thats great. I really like the idea.

I will take a deeper look at this during the weekend to see how we can make the installation easier.

Great work!

**Comment by masmu** [comment]
I am sorry, i did not have the time yet. I was busy fixing bugs.

But i promise you will not be forgotten.

**Comment by queeup** [comment]
No problem at all. Just I want you to know what I did. I already using it for my self :)

**Comment by masmu** [comment]
Note that there is now a PPA to install from.
The process name changed to ```pulseaudio-dlna```.

 * __0.3.0__ - (_2015-02-01_)
    - Added debian packaging
    - Added proper signal handlers (new dependency: `python-setproctitle`)
    - Fixed a bug where binding to an already used port made the application crash
    - HTTP charset encoding is now specified correctly

**Comment by queeup** [comment]
Yea I saw it. I will make proper changes.

**Comment by queeup** [comment]
I did some changes and renaming. Also updated README. You can test it if you want.

**Comment by muammar** [comment]
@queeup very nice, I am using your systray application under awesomewm. It works very well.

**Comment by muammar** [comment]
@masmu do you plan to add this systray support to the application?.

**Comment by klaernie** [comment]
I would suggest not integrating it too tighly. In my experience I would rather prefer to have it sitting in the background in daemon mode, so all required for activation is choosing the right sink in pulseaudio.

**Comment by masmu** [comment]
No. Basically because of the same reason. It also would break the application for people using this in a non X environment, e.g.: RPi users.

**Comment by muammar** [comment]
@masmu @klaernie thanks for your replies. I understand now.

**Comment by jkufner** [comment]
I think it makes sense to keep these two parts close, but as separate packages. So, link each other in documentation?

**Comment by typhoe** [comment]
Hi,

I had a few problem to easily make the systray script launch in my Arch install, so if it can help other people, here's what I did:
Get the script from Queeup and its icon
`sudo wget -P /usr/local/bin/ -c https://raw.githubusercontent.com/queeup/pulseaudio-dlna-systray/master/systray_icon.png`
`sudo wget -P /usr/local/bin/ -c https://raw.githubusercontent.com/queeup/pulseaudio-dlna-systray/master/pulseaudio-dlna-systray`
The script seems to only work with python2, so change the sheebang
`sudo sed -i 's,^#!/usr/bin/env python.*,#!/usr/bin/env python2,' /usr/local/bin/pulseaudio-dlna-systray`
Make the script executable
`sudo chmod 755 /usr/local/bin/pulseaudio-dlna-systray`

Then to autolaunch when I login my Gnomeshell session, if necessary, create the autostart directory
`mkdir -p ~/.config/autostart 2>/dev/null`
And create a desktop shortcut to the script
`cat <<EOF > ~/.config/autostart/pulseaudio-dlna-systray.desktop`
`[Desktop Entry]`
`Type=Application`
`Exec=/usr/local/bin/pulseaudio-dlna-systray`
`Hidden=false`
`X-GNOME-Autostart-enabled=true`
`Name=pulseaudio-dlna-systray`
`Comment=PulseAudio DLNA Systray`
`EOF`

That's all. The systray icon appears in the bottom left corner on gnomeshell.
