### ISSUE TITLE
Sangean DDR-63+ Support

### ISSUE THREAD

**Issue by lgro** [masmu/pulseaudio-dlna#53]
Hi there, similar to #32 I have a problem with my Sangean DLNA client when I assign an audio output to it.
```
INFO:root:Found devices:
<CoinedUpnpMediaRenderer name="DDR-63+ 002261a8ce7e" short_name="ddr63002261a8ce7e" state="idle">
INFO:root:You can now use your upnp devices!
INFO:root:PulseWatcher.on_device_updated "/org/pulseaudio/core1/sink5"
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 259, in on_device_updated
    self._handle_sink_update(sink_path)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 294, in _handle_sink_update
    if bridge.upnp_device.register() == 200:
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/upnp/renderer.py", line 253, in register
    return UpnpMediaRenderer.register(self, self.stream_url)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/upnp/renderer.py", line 141, in register
    url = self._get_av_transport_url()
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/upnp/renderer.py", line 118, in _get_av_transport_url
    return self._get_url(av_transport['control_url'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by masmu** [comment]
I am not quite sure, but i think that bug is fixed in the actual development version.

**Comment by lgro** [comment]
I'm running pulseaudio-dlna  0.3.5-2 under Manjaro Linux but still this problem occurs.

**Comment by masmu** [comment]
It is not release yet. Would be something larger than _0.4.x_

**Comment by masmu** [comment]
* __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies
