### ISSUE TITLE
Android/BubbleUpnp

### ISSUE THREAD

**Issue by w3stley** [masmu/pulseaudio-dlna#55]
Hello, 
i have installed pulseaudio-dlna, but when i start BubbleUPPnP and want to connect, i am not getting the server. But on my Laptop i get this:
<script src="https://gist.github.com/w3stley/2e8980f00cc3f80f01d9.js"></script>
https://gist.github.com/w3stley/2e8980f00cc3f80f01d9

Can you help?

**Comment by masmu** [comment]
Which distro do you use?

The process which records your audio stream fails on starting. It seems as the necessary commands could not be found on your system.
Check if the commands __parec__ and __lame__ are available on your system.
In your case i guess it is _lame_ which is missing.

**Comment by w3stley** [comment]
I use Debian Jessie.
I have installed lame, but nothing happens.
But i also dont get any hint on the app about a possible connection.

**Comment by masmu** [comment]
What you can do: Insert the following three lines in pulseaudio-dlna/pulseaudio_dlna/upnp/server.py, line 70.
```python
print(bridge)
print(self.server.recorder_cmd.format(bridge.sink.monitor).split(' '))
print(self.server.encoder_cmd.split(' '))
```
so, that it looks like:
```python
    def create_processes(self, bridge):
        print(bridge)
        print(self.server.recorder_cmd.format(bridge.sink.monitor).split(' '))
        print(self.server.encoder_cmd.split(' '))
        recorder_process = subprocess.Popen(
            self.server.recorder_cmd.format(
                bridge.sink.monitor).split(' '),
            stdout=subprocess.PIPE)
        encoder_process = subprocess.Popen(
            self.server.encoder_cmd.split(' '),
            stdin=recorder_process.stdout,
            stdout=subprocess.PIPE)
        recorder_process.stdout.close()
        return recorder_process, encoder_process
```
Then save and try again and please paste the output.

Perhaps this is about some legal issues with mp3 encoding in lame. In past versions of ubuntu you had to install lame from the multiverse repository to also get _encoding_ features.

**Comment by w3stley** [comment]
Can it be that it is necessary that you need a sound source so that BubbleUPnP can connect?
Because i have tested it and now it works fine, much better then rygel. Thank you for your help.

**Comment by masmu** [comment]
What do you mean by sound source?
You just start _BubbleUPnP_ and leave it. You don't have to do anything in _BubbleUPnP_.
When _BubbleUPnP_ is started, just switch the application sound stream to 'BubbleUPnP (SM-G800F)' via _pavucontrol_ as it is shown in the README image.

The latency is mostly network related. More information about that https://github.com/masmu/pulseaudio-dlna/issues/51 here.
How fast it can be can be viewed in [that really cool video](https://www.youtube.com/watch?v=g8a1VYdrAlI). But in that setup it is used with cable connection.
I have a latency about 3 seconds on wifi... But i am sitting next to the wifi transmitter.

**Comment by w3stley** [comment]
e.g. youtube, vlc.
If i connect with BubbleUPnP to Windows, i select Windows in BubbleUPnP. Here it is not so.
So it work now. I wil check the links.

**Comment by masmu** [comment]
_pulseaudio-dlna_ is not a DMS (Digital Media Server). It is made for redirecting streams from your pc to devices, not made for accessing files on your pc via the devices.

**Comment by w3stley** [comment]
yes, i know. But the connecting is a bit different, so at first i was a bit confused.
With switching to the html5-player, youtube is imho a bit faster.
