### ISSUE TITLE
Fedora rpm packages

### ISSUE THREAD

**Issue by Cygn** [masmu/pulseaudio-dlna#56]
Hi there,

I've setup a fedora copr repo at https://copr.fedoraproject.org/coprs/cygn/pulseaudio-dlna/
It's built on refactor branch so the current version is 3.4.

As a side note, I had to include notify2.py  with the sources as it's not available in fedora, and encoders except vorbis are optional dependencies. I also had to hack setup.py a bit and add a MANIFEST.in to build the src.rpm correctly.

Thx for your work!

**Comment by masmu** [comment]
You are releasing a development branch? I really like your effort, but why should you do that? The actual released version is _0.3.5_ ... so your _0.3.4_ is not even the same as it is for the rest of the world.

To be honest: I would appreciate it if you take this down and just package what was released here.
I am currently working hard finishing _0.4.0_, which will be runnable as a system service.

**Comment by Cygn** [comment]
Well, the master branch fails to run in my box, maybe its fedora specific:

```
Traceback (most recent call last):
  File "__main__.py", line 164, in <module>
    sys.exit(main())
  File "__main__.py", line 160, in main
    pulseaudio_dlna.startup()
  File "__main__.py", line 111, in startup
    dlna_discover.search()
  File "Development/pulseaudio-dlna/build/lib/pulseaudio_dlna/upnp/discover.py", line 67, in search
    BaseUpnpMediaRendererDiscover.search(self, ttl, timeout, times)
  File "Development/pulseaudio-dlna/build/lib/pulseaudio_dlna/upnp/discover.py", line 50, in search
    self._header_received(header, address)
File "Development/pulseaudio-dlna/build/lib/pulseaudio_dlna/upnp/renderer.py", line 311, in from_header
    if header['location']:
KeyError: u'location'
```

Regarding the latest discussion here, I got the impression that you did prefer the devel branch, where the code is fresher. Besides, I don't think neither of us would take the time debug what's wrong on 0.3.5/master on fedora as 0.3.4/refactor works. Anyway no problem to pull this back in the meantime if you prefer so, or add a big [experimental/may kill your kitten] tag.

I really like the idea of a systemd service by the way.

+

**Comment by masmu** [comment]
Yeah, you found a bug! That should look like that:
```python
    @classmethod
    def from_header(self, header, type_=UpnpMediaRenderer):
        if header.get('location', None):
            return self.from_url(header['location'], type_)
```

Please don't use any official version numbers. I would be a pity if i cannot rely anymore on somebody saying he is using _0.3.4_. And add some _experimental_ tag. So, in ubuntu you can use a **~** to lower a version number. Can't you use something like _0.4.0~alpha1_?

**Comment by Cygn** [comment]
Done. its 0.4-0.alpha then. 
I don't plan to repack until next release, as this one works for me.  

thx again for your dedication!

**Comment by masmu** [comment]
Packing time! Do you want your repository to be listed in the README?

 * __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies

**Comment by Cygn** [comment]
yes, will pack today. 
Congrats for the 0.4 and your dedicated work.

**Comment by masmu** [comment]
Your repository was added. It would be nice if you could adapt the project description, because of the added Chromecast support.

Thanks for packaging! :+1:

**Comment by Cygn** [comment]
Done. I've also added rpms for RHEL / CentOS 7. Not tested though but I'm pretty confident that they'll work.

+

**Comment by masmu** [comment]
Should I add RHEL and CentOS?

It is up to you if you also want to maintain those packages...

**Comment by Cygn** [comment]
yes, go ahead. it's really no extra work, just one more box to tick in copr :-)
