### ISSUE TITLE
[feature] Support for upnp renderer type 3, 2

### ISSUE THREAD

**Issue by Lahorde** [masmu/pulseaudio-dlna#57]
Hi Masmu,

Now upnp renderer:2, renderer:3 are not supported. 
Only renderer:1 is supported, in fromURL method from UpnpMediaRendererFactory in renderer.py I've replaced l284 with : 

    if re.match(r"^urn:schemas-upnp-org:device:MediaRenderer:[1,2,3]$", device.devicetype.text) is None:

and tested  with my rygel, gmrender renderers. All was fine. 

Renderer of type 2, 3 are backward compatible in upnp, but it must be tested on some other renderers (I have only rygel and gmrender installed on some raspberry).

**Comment by masmu** [comment]
I am very sorry, some how i overlooked that issue.

Thank you for you bug report! This bug is already fixed in the next version.
So, please stay tuned!

**Comment by masmu** [comment]
* __0.4.0__ - (_2015-07-27_)
    - Added the ```--fake-http10-content-length``` option
    - The application can now run as root
    - Catch pulseaudio exceptions for streams, sinks and modules when those are gone
    - Fixed a bug where a missing ssdp header field made the application crash
    - New devices are added now during runtime (thanks to [coder-hugo](https://github.com/coder-hugo))
    - Rewrite of the streaming server
    - Upnp devices can now request their audio format based on their capabilities
    - Added AAC encoder
    - If a device stops playing, the streams currently playing on
      the corresponding sink are switched back to the default sink
    - If a device failes to start playing, streams currently playing on
      the corresponding sink are switched back to the default sink
    - Added Chromecast support (new dependency: `python-protobuf`)
    - Fixed a bug where the application crashed when there was no suitable encoder found
    - Added the ```--bit-rate``` option
    - Added additional headers for DLNA devices
    - Added switch back mode also for sinks, not just for streams (new dependency: `python-notify2`)
    - Added better logging
    - Validate encoders for installed dependencies
