### ISSUE TITLE
Majik DSM

### ISSUE THREAD

**Issue by nobanzai** [masmu/pulseaudio-dlna#6]
Hi,
first let me say thank you for that really useful and simple to use piece of software! You've got a few Euros yesterday, because I was totally excited about it after having no success with rygel for months.
One question though:
We have a Majik DSM and two Phillips NP2900 in our network.
After installing your package yesterday everything worked like a charme.
Today the Majik DSM refused to play anything from its pulseaudio output device - no sound, although the device existed and pavucontrol clearly showed, that the music was playing.
After fiddling around a bit the solution was simply to switch the output in the playback section of pavucontrol to a different renderer and switch it back to the Majik DSM.
Is there anything you can send the Majik DSM (for example some kind of start signal), so that it will start playing without that manual back and forth switching?
Thx a lot!
Bye.
Michael.

**Comment by masmu** [comment]
You are right. I recognized this behavior myself sometimes. Sadly, i cannot reliable reproduce it.
That would make it much more easy to debug.
Can you provide a reliable way to reproduce it?

Thanks for your enthusiasm and of cause for your donation ;)

**Comment by nobanzai** [comment]
Hi,
I can reproduce it reliably.
It happens everytime, a different UPnP client connects the renderer and is "stealing the focus". It also happens the next morning after the renderer went into sleep mode over night.
All the other UPnP clients (like eezUPnP or some Windows clients) just grab the "focus" from the renderer and start playing - not pulseaudio-dlna.
TIA.
By.
Michael.

**Comment by masmu** [comment]
* __0.2.4__ - (_2015-01-25_)
    - Stream changes are now handled correctly (thanks to [Takkat-Nebuk](https://github.com/Takkat-Nebuk))

Please test this version. I am pretty sure it fixes your issues besides when another upnp controller registers to your renderer and therefore it is stealing the focus.
Currently i do not listen to upnp events, and therefore i doubt that _pulseaudio-dlna_ gets informed about that.

This feature will take some time, but it is planned.

**Comment by masmu** [comment]
* __0.3.0__ - (_2015-02-01_)
    - Added debian packaging
    - Added proper signal handlers (new dependency: `python-setproctitle`)
    - Fixed a bug where binding to an already used port made the application crash
    - HTTP charset encoding is now specified correctly

Note that there is now a PPA to install from.

Did __0.2.4__ fix your problems?

**Comment by nobanzai** [comment]
Didn't find the time to test 0.2.4, sry 8-<
Tested 0.3.0 today. Had a few problems with my scripts, because the startup logic for pulseaudio-dlna has changed, but not I have it up and running.
And: This version indeed fixed my problem.
Thx a lot.
Bye. Michael.
