### ISSUE TITLE
version 4.x : "The SSDP listener could not bind to the port 1900/UDP"

### ISSUE THREAD

**Issue by yannek** [masmu/pulseaudio-dlna#62]
Thanks for "pulseaudio-dlna", it is generally very usefull.

I was using "pulseaudio-dlna" on a Linux Mint 17.2 Cinnamon 64-bit computer to push the sound on my HiFi music player Sony:CMT-SBT300W. It worked fine with the 3.5 version.

After an update to 4.3 version, "pulseaudio-dlna" terminates with this message (whether the musicplayer is connected or not) :

"pulseaudio dlna.application ERROR The SSDP listener could not bind to the port 1900/UDP. Perhaps this is already in use? Application terminates"

I am back to 3.5 and it works again.

**Comment by Takkat-Nebuk** [comment]
You may be running another DLNA server using this port (e.g. miniDLNA). This port is used for client discovery in pulseaudio-dlna 4.x and it can't be accessed if another server used it.

You may have to stop the other DLNA server before using pulseaudio-dlna.

**Comment by masmu** [comment]
Takkat is right.

I am planning to make a small adjustment in the next version, where a used port or perhaps a flag just disables the auto discover feature, so that _pulseudio-dlna_ and other DMS can live in co-existance and harmony.

**Comment by yannek** [comment]
Thank you for your answers. The options "multicast/RTP receiver" and "multicast/RTP sender" and some others linked to network were enabled in pulseaudio. 

After disabling it, I was able to use the last version perfectly. I conjecture that it is linked to the port you mentioned. Thanks again for your work.

**Comment by masmu** [comment]
* __0.4.4__ - (_2015-08-07_)
    - Added `--disable-ssdp-listener` option
    - Fixed a bug with applications which remove and re-add streams all the time
    - Added a missing dependency `python-psutil`
