### ISSUE TITLE
Streaming to Kodi doesn't work

### ISSUE THREAD

**Issue by theli-ua** [masmu/pulseaudio-dlna#68]
Used to work before all of the streaming/etc rework ... now it just doesn't

**Comment by theli-ua** [comment]
It looks like now it just starts indefinitely buffering and only tries to start playing something if I kill pulseaudio-dlna

**Comment by masmu** [comment]
Which version are you using? Which OS?

Could you provide a debug.log?
```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

I just tested it with _kodi_ 15 and _pulseaudio-dlna_ _0.4.4_ ... works for me.

**Comment by theli-ua** [comment]
Just tested it - it does seem to work without problems with ogg or mp3.
Doesn't work anymore with FLAC or WAV

**Comment by theli-ua** [comment]
With FLAC pulseaudio-dlna reports everything just fine but Kodi just never starts to play

**Comment by theli-ua** [comment]
debug log with FLAC encoder http://paste.ee/p/q2vvm

**Comment by theli-ua** [comment]
oh, and I'm running Kodi 14.2 on Openelec (Linux) on raspberry pi

**Comment by theli-ua** [comment]
Oh, and it does seem to work with WAV, so its not that big of a deal I guess

**Comment by theli-ua** [comment]
@masmu I think FLAC streaming to Kodi (or anywhere else I tried) works with latest version.
I could open a separate issue for that though.

**Comment by theli-ua** [comment]
er, i DON'T think it works
