### ISSUE TITLE
Streaming to ONKYO receiver doesn't work

### ISSUE THREAD

**Issue by theli-ua** [masmu/pulseaudio-dlna#69]

**Comment by masmu** [comment]
Could you provide a debug.log?

```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by theli-ua** [comment]
Log with FLAC: http://paste.ee/p/VIijX
It does seem to work with MP3+fake length though

**Comment by theli-ua** [comment]
I take it back, It worked ONCE , I wasn't able to reproduce it since then :(

Also, it works just fine with FLAC or LPCM from 'allstream' android app (kinda similar, captures audio output and plays via dlna)

**Comment by theli-ua** [comment]
OK, it does now work for me with WAV encoder. So this is not that big of deal I guess

**Comment by theli-ua** [comment]
Though in a pretty inconsistent way, and when the player I was using for testing switches to new track it recreates playback stream... and receiver gets stuck

**Comment by masmu** [comment]
Which version were you using for that?

In your log your device returns a error code (`Transport is locked`). A little research shows, that this might be specific to Onkyo devices. [See here](http://forum.xda-developers.com/showpost.php?s=e28c93c9ad934026a2228fff9ea2f3ec&p=48025039&postcount=10).

Is it possible that this is some kind of security setting from _Onkyo_ you have to disable before actually using it?

**Comment by theli-ua** [comment]
Well, as I said it streams without a hitch from a different APP

**Comment by masmu** [comment]
Did you at least give it a try?

Which different app? Can you provide a _wireshark_ recording for that?

**Comment by theli-ua** [comment]
Allstream Android was the app which just worked with it https://play.google.com/store/apps/details?id=com.kineticgamestudios.airtunes.android&hl=en
Its not open source and unfortunately I don't have a way to capture communication between them.

**Comment by masmu** [comment]
Oh you can. Its called _kPacketCapture_, its free and does not require root.

**Comment by theli-ua** [comment]
On Sun, Aug 16, 2015 at 12:09 PM, Massimo Mund <notifications@github.com>
wrote:

> *kPacketCapture*



I assume you mean tPacketCapture. Last time I tried it didn;t work too
reliable. It also doesn't capture UDP traffic

**Comment by masmu** [comment]
Yes you are right. _tPacketCapture_.
Don't worry about UDP. The interesting stuff is all TCP.
