### ISSUE TITLE
Add an option to not stop playback when all playbackstreams are destroyed

### ISSUE THREAD

**Issue by theli-ua** [masmu/pulseaudio-dlna#70]
It would be great to have a 'continious stream' option so that if playbackstreams are destroyed it would not stop the device from playing.

Some music players without gapless playback with recreate playback stream for each track. This will make pulseaudio-dlna to issue stop to device and then play again, which is undesired

**Comment by masmu** [comment]
Currently there is another [issue](https://github.com/masmu/pulseaudio-dlna/issues/61) where we found that problem. Since i am just using _spotify_ i would never found this bug myself :smile: 

In _0.4.4_ _pulseaudio_ events get aggregated, so that they sum up in certain time intervals. So, if your application adds and removes streams after each track, they should not induce any actions any more.

Can you confirm this behaviour?

**Comment by theli-ua** [comment]
"they should not induce any actions any more."
Well, I'm using tip of master and they are making pulseaudio-dlna sending STOP to device

**Comment by masmu** [comment]
I spend the last 4 hours fixing issues such as yours. I hope you don't feel offended by my spelling mistakes.

Could you provide a .log for that issue? It would be great if you can add some comments for your specific problem. Such things as: I did this at that time and i would expect the following ...
The more detailed the better i can help you. Words are cheap ...

**Comment by theli-ua** [comment]
http://paste.ee/p/onYp8
When my player switches tracks pulseaudio-dlna will send a STOP rhen a PLAY again. I would really love a way to avoid that.
How I would imagine that - having an option such as --constant-stream or --insert-silence .. etc which would NOT stop a DLNA device when there is nothing playing to pulseaudio-dlna provided sink

**Comment by masmu** [comment]
I've added the `--disable-device-stop` flag in [that branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/sound-vanishes).

Please check if that solves your problem.

**Comment by theli-ua** [comment]
Thanks, works wonderfully on both of my Kodi and ONKYO receiver, I'll also
close my ONKYO ticket as with this option it works wonderfully

**Comment by masmu** [comment]
Did you also use version _0.3.5_ and if yes, there you encounter the same issue with that version?

Nice. Please do me a favour and test this over a few days. Then please share your experience. Perhaps it is causing any trouble ...
