### ISSUE TITLE
crash at discovering my device

### ISSUE THREAD

**Issue by flattman** [masmu/pulseaudio-dlna#71]
Hi,

first, thanks for this fine extension!

I got the following error after starting the program width pulseaudio-dln --debug at discovering my devices.

http://pastebin.com/zdShHQ4x

My system: 3.18.3-031803-generic, Ubuntu 14.04.3 LTS

Does anyone have an idea how to fix this?

**Comment by masmu** [comment]
That should be easy to fix. But i need some more logs. I created a [branch](https://github.com/masmu/pulseaudio-dlna/tree/bug/mimetype-lookup) for that.

Could you replace your `/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/upnp/renderer.py` with [that one](https://raw.githubusercontent.com/masmu/pulseaudio-dlna/bug/mimetype-lookup/pulseaudio_dlna/plugins/upnp/renderer.py) and paste a new log?

**Comment by flattman** [comment]
no problem: http://pastebin.com/Pnkzmtkw

**Comment by masmu** [comment]
Nice. Could you replace the same file with [that one](https://raw.githubusercontent.com/masmu/pulseaudio-dlna/bug/mimetype-lookup/pulseaudio_dlna/plugins/upnp/renderer.py). 

This should fix your problem.

**Comment by flattman** [comment]
works perfectly!, Thx!

**Comment by masmu** [comment]
Nice, you will find that fix in the next release.
