### ISSUE TITLE
The SSDP listener could not bind to the port 1900/UDP

### ISSUE THREAD

**Issue by David056** [masmu/pulseaudio-dlna#79]
Hello,

I'm new on linux (mint 17.2) and try to stream audio from Kodi to my Chromecast (with google cast)
I've got this issue when I will run pulseaudio-dlna

08-27 20:05:45 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.25:8080
08-27 20:05:45 pulseaudio_dlna.application                    INFO     Loaded encoders:
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <LameEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/mpeg,audio/mp3">
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <WavEncoder bit-rate="None" state="True" enabled="True" mime-types="audio/wav,audio/x-wav">
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <AacEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/aac,audio/x-aac">
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <FlacEncoder bit-rate="None" state="True" enabled="True" mime-types="audio/flac,audio/x-flac">
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <OggEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/ogg,audio/x-ogg,application/ogg">
08-27 20:05:45 pulseaudio_dlna.application                    INFO     <OpusEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/opus,audio/x-opus">
08-27 20:05:45 pulseaudio_dlna.application                    ERROR    The SSDP listener could not bind to the port 1900/UDP. Perhaps this is already in use? Application terminates. You can disable this feature with the "--disable-ssdp-listener" flag

So I can't choose DLNA/Upnp option in Pulseaudio prefs
The same with ufw disable
Can you help me?
Thanks
David

**Comment by masmu** [comment]
There is an application on your computer which is using the port 1900. This port is needed to detect devices **while** the application is running. You can disable that feature with the `--disable-ssdp-listener` flag. If you do devices will be detected at application start up, but not anymore while the application runs. But in most cases that does not matter ...

**Comment by David056** [comment]
Hello Masmu,

Yes indeed, plex use this port, if i try to run kodi before I have also the same error on port 8080 
I've tried with --disable-ssdp-listener 
pulseaudio-dlna --disable-ssdp-listener 
08-28 19:51:23 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.178.25:8080
08-28 19:51:23 pulseaudio_dlna.application                    INFO     Loaded encoders:
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <LameEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/mpeg,audio/mp3">
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <WavEncoder bit-rate="None" state="True" enabled="True" mime-types="audio/wav,audio/x-wav">
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <AacEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/aac,audio/x-aac">
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <FlacEncoder bit-rate="None" state="True" enabled="True" mime-types="audio/flac,audio/x-flac">
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <OggEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/ogg,audio/x-ogg,application/ogg">
08-28 19:51:23 pulseaudio_dlna.application                    INFO     <OpusEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/opus,audio/x-opus">
08-28 19:51:29 pulseaudio_dlna.listener                       INFO     Discovery complete.

But If I go to the Pulseaudio prefs or control, I can't reach my chromecast and I can't choose this options
![sans titre](https://cloud.githubusercontent.com/assets/14003696/9553552/14446e9e-4dc0-11e5-9350-d11d32cf2732.png)

Sorry I'm new on linux and I'm sure I do anything wrong. If you don't have time don't waste it for me :)

Have a nice w-e

**Comment by masmu** [comment]
The pulseaudio settings have nothing in common with _pulseaudio-dlna_. You won't find any settings there.

In your log there are no lines for encoders. For example `<LameEncoder ...>` is missing.
Did you install _pulseaudio-dlna_ via a ppa? If you did, all needed encoders should be installed automaticly. Anyway, make sure you installed the following binarys:
- `sox`
- `lame`
- `oggenc`
- `flac`
- `faac`

Besides that i am missing a line about a found Chromecast. What is your network setup?

**Comment by Zopieux** [comment]
I ran into your issue when hacking a bit with `pulseaudio-dlna`. Let me guess: you tried to Ctrl-C out of the program, it did not exit right away, so you did another Ctrl-C. Hard kill. This poped the `pulse_watcher` subprocess out of the process tree, right into PID 1, thus making it "unkillable" through Ctrl-C.

The solution to your issue is to give `pulseaudio-dlna` more time to shutdown. If it does not terminate after a few seconds, you can kill it, but don't forget to also `pkill pulse_watcher` to free the 1900 UDP port.

---
Nevertheless, there is still an issue when `pulseaudio-dlna` does not terminate cleanly after a `KeyboardInterrupt` and this should be addressed.

**Comment by masmu** [comment]
@Zopieux 
I have never experienced that myself, what does not mean that you are wrong. But it is hard to fix it if does not happen to you. So, if you figure out whats going on, patches/PRs very welcome.

And don't think that this is what's happening for David. He mentioned himself that the application which uses the port is _plex_.

**Comment by Zopieux** [comment]
Oh indeed, didn't notice the relevant reply sorry. Never mind, I'll open an issue if I run into this ghost process issue again.

**Comment by masmu** [comment]
- Distored sound
   If you experience distored sound, try to pause / unpause the playback or changing the volume.

**Comment by masmu** [comment]
Closed due to inactivity.
