### ISSUE TITLE
Question regarding encoders

### ISSUE THREAD

**Issue by nobanzai** [masmu/pulseaudio-dlna#80]
Is it possible to not use an encoder at all, but stream the songs in their native format?
All of my UPnP renderers are capable of all formats I use for my files, i.e. flac, ogg, mp3 and wav.
Or is this something that isn't possible by design?
Thx!

**Comment by masmu** [comment]
`parec` delivers audio as _raw audio_. In my tests non of my devices were able to play those stream, what does not mean that it is not possible.
Thats why those raw audio data is piped to an encoder, which converts it to something devices can play.

Whats the problem with the encoding in general?

**Comment by masmu** [comment]
I think i got that question wrong. _pulseaudio-dlna_ does not record the native audio data, it records what is played on a specific sink. And that results in recording _raw audio_. So, from that point of view it is not possible by design.

**Comment by nobanzai** [comment]
ic
The point behind that question was to avoid converting sound two times, because the files are already in the correct format for the target devices.
And: I'm not really sure, but my problems with padlna seem to get better or worse with different encoders. The worst results I had with the flac encoder, it *seemed* to get better with the mp3 encoder and I will try the wav enocder next, because that was the default encoder in version 0.3.x, if I remember correctly. And 0.3.x made no problems.

**Comment by Cygn** [comment]
the feature you are looking for is an upnp control point. It would let you send directly a media file to the renderer. By comparison, padlna takes the overall sound output from the OS and does not care/know where this signal comes from.
In linux AFAIK currently only usable control point is upplay http://www.lesbonscomptes.com/upplay/ https://github.com/medoc92/upplay
For this to work, your media files must be available through a upnp server. Rygel handles this easily.

**Comment by nobanzai** [comment]
I already use ezupnp for that purpose, which is great for the things where you need a control point.
And no, I don't want a control point instead of padlna :)
I thought, that padlna gets the original format and could stream it 1:1 to the renderer.
But what you  explained of course makes that impossible.

**Comment by masmu** [comment]
So, question solved? :wink:

**Comment by nobanzai** [comment]
yes, thx!
