### ISSUE TITLE
Exception when returned sinks end with an comma

### ISSUE THREAD

**Issue by kifj** [masmu/pulseaudio-dlna#85]
Hi,

I've a Yamaha RX-671 Audio Receiver. The answer send by the device is

09-07 21:07:01 pulseaudio_dlna.plugins.upnp.renderer          DEBUG    sending GET_PROTOCOL_INFO to http://192.168.1.3:49154/ConnectionManager/ctrl:
 - headers:
{u'SOAPAction': u'"urn:schemas-upnp-org:service:ConnectionManager:1#GetProtocolInfo"', u'Content-Type': u'text/xml; charset="utf-8"'}
 - data:
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <u:GetProtocolInfo xmlns:u="urn:schemas-upnp-org:service:ConnectionManager:1">
        </u:GetProtocolInfo>
    </s:Body>
</s:Envelope>
 - result: 200
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetProtocolInfoResponse xmlns:u="urn:schemas-upnp-org:service:ConnectionManager:1"><Source></Source><Sink>http-get:*:audio/L16;channels=2;rate=44100:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=44100:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=48000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=48000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=32000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=32000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=88200:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=88200:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=96000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=96000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=64000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=64000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=22050:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=22050:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=24000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=24000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=16000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=16000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=11025:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=11025:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=12000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=12000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=2;rate=8000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16;channels=1;rate=8000:DLNA.ORG_PN=LPCM,http-get:*:audio/L16:DLNA.ORG_PN=LPCM,http-get:*:audio/mpeg:DLNA.ORG_PN=MP3,http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMABASE,http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMAFULL,http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMDRM_WMABASE,http-get:*:audio/x-ms-wma:DLNA.ORG_PN=WMDRM_WMAFULL,http-get:*:audio/mp4:DLNA.ORG_PN=AAC_ISO,http-get:*:audio/mp4:DLNA.ORG_PN=AAC_ISO_192,http-get:*:audio/mp4:DLNA.ORG_PN=AAC_ISO_320,http-get:*:audio/3gpp:DLNA.ORG_PN=AAC_ISO,http-get:*:audio/3gpp:DLNA.ORG_PN=AAC_ISO_192,http-get:*:audio/3gpp:DLNA.ORG_PN=AAC_ISO_320,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-flac:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/x-aac:*,http-get:*:audio/x-mp3:*,http-get:*:audio/x-mp4:*,http-get:*:audio/x-mpg:*,http-get:*:audio/x-wav:*,http-get:*:audio/3gpp:*,http-get:*:audio/aacp:*,http-get:*:audio/flac:*,http-get:*:audio/mpeg:*,http-get:*:audio/aac:*,http-get:*:audio/m4a:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/wav:*,</Sink></u:GetProtocolInfoResponse></s:Body></s:Envelope>

As you see the list of sinks ends with ',' (which may be nasty), but this causes an exception in renderer.py line 250, which can be fixed with an additional check, if the sink is empty:

                for sink in sinks.split(','):
                    if sink:
                        http_get, w1, mime_type, w2 = sink.strip().split(':')
                        if mime_type.startswith('audio/'):
                           self.protocols.append(mime_type)

Regards
Joe

**Comment by kifj** [comment]
This happens on 0.4.3, not on master

**Comment by masmu** [comment]
I know. Expect the fixes in _0.4.5_ ...

**Comment by masmu** [comment]
* __0.4.5__ - (_2015-09-20_)
    - Exceptions while updating sink and device information from pulseaudio are now handled better
    - Changed `--fake-http10-content-length` flag to `--fake-http-content-length` to also support HTTP 1.1 requests
    - Fixed a bug where the supported device mime types could not get parsed correctly
    - Fixed a bug where the device UUID was not parsed correctly
    - Fixed a bug where just mime types beginning with `audio/` where accepted, but not e.g. `application/ogg`
    - The stream server will now respond with 206 when receiving requests with `range` header
    - UPNP control commands have now a timeout of 10 seconds
    - Fixed a bug where the wrong stream was removed from the stream manager
    - Fixed several bugs caused by purely relying on stopping actions for the devices idle state
    - Added L16 Encoder
    - The encoder option can now handle multiple options separated by comma
    - Added the `--create-device-config` flag
    - Fixed a bug where the dbus session was bound from the wrong process
    - Fix a bug where the wrong device UDN was retrieved from XML documents containing multiple devices
