### ISSUE TITLE
Load pulseaudio module-dbus-protocol at runtime

### ISSUE THREAD

**Issue by Takkat-Nebuk** [masmu/pulseaudio-dlna#9]
Rather than exiting the application it would be nicer to load the missing `module-dbus-protocol` at runtime. This module was not loaded in a default Ubuntu installation. Therefore before running  `pulseaudio-dlna` a manual loading of this pulseaudio module or editing of `default.pa` is always required.

This may not be wanted later when users may be able to install e.g. by a DEB package.

Loading of this missing module can be done with the following lines in `pulseaudio.py`

```python
    def _get_bus(self):
        try:
            server_address = self._get_bus_address()
            return dbus.connection.Connection(server_address)
        except dbus.exceptions.DBusException:
            subprocess.Popen(['pactl','load-module','module-dbus-protocol'])
            try:
                server_address = self._get_bus_address()
                return dbus.connection.Connection(server_address)
            except dbus.exceptions.DBusException:
                logging.error('PulseAudio seems not to be running ')
                sys.exit(1)
```

**Comment by masmu** [comment]
Thank you very much! I merged it right away.

 * __0.2.2__ - (_2015-01-18_)
    - Fixed encoding issues
    - Try to load the DBus module if it is loaded before (thanks to [Takkat-Nebuk](https://github.com/Takkat-Nebuk))

**Comment by Takkat-Nebuk** [comment]
Hi - thanks for merging.

Unfortunately after some testing we could  see that loading the module may take too long. Then a dbus connection exception will raise despite the module had loaded properly. This will lead to an unwanted program termination.

To overcome this we need to wait for the subprocess to terminate by calling Popen.wait() or  Popen.communicate()

```python
61            subprocess.Popen(['pactl','load-module','module-dbus-protocol']).communicate()
```

So sorry for me having posted code here without proper testing.

**Comment by masmu** [comment]
Don't worry, those things happen. I noticed this myself today, but without the report i would have cared about it later.

So thanks for the fix! :smile: 

 * __0.2.3__ - (_2015-01-21_)
    - Fixed a timing bug where the pulseaudio module was not loaded fast enough (thanks to [Takkat-Nebuk](https://github.com/Takkat-Nebuk))
