### ISSUE TITLE
Please add python-concurrent.futures as a dependency

### ISSUE THREAD

**Issue by Takkat-Nebuk** [masmu/pulseaudio-dlna#90]
grats to the new release - very (very!!!) nice new features.

One thing: we need `python-concurrent.futures` as a dependency. This module is not installed by default and if missing makes pulseaudio-dlna crash after updating from your ppa.

Carry on with your good work!

**Comment by masmu** [comment]
Thank you Takkat. I was pretty sure futures belong to stock python2.7. My mistake :wink: 

 * __0.4.5.1__ - (_2015-09-20_)
    - Added a missing dependency `python-concurrent.futures` (thanks to [Takkat-Nebuk](https://github.com/Takkat-Nebuk))
