### ISSUE TITLE
Can't play on LG MusicFlow h4

### ISSUE THREAD

**Issue by p1ratrulezzz** [masmu/pulseaudio-dlna#93]
Hi, I got an error:

  09-24 12:27:16 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "LG Music Flow H4(65) (DLNA)" to play ...
09-24 12:27:16 pulseaudio_dlna.plugins.upnp.renderer          ERROR    "LG Music Flow H4(65)" registering failed!
09-24 12:27:16 pulseaudio_dlna.pulseaudio                     ERROR    The device "LG Music Flow H4(65) (DLNA)" failed to play! (None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 580, in _handle_sink_update
    result = future.result()
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 23: ordinal not in range(128)

**Comment by masmu** [comment]
Could you create a full _debug.log_ and paste it somewhere?

`pulseaudio-dlna --debug 2>&1 | tee -a debug.log`

**Comment by patufet99** [comment]
Hello, I have a simillar error "registering failed" with a Yamaha CRX-N560D device. I can select the device, but when trying to  play some music, pulseaudio gives this error:

`09-26 21:33:41 pulseaudio_dlna.plugins.upnp.renderer          ERROR    "CRX-N560D 8294F" registering failed!`
`09-26 21:33:41 pulseaudio_dlna.pulseaudio                     ERROR    The device "CRX-N560D 8294F (DLNA)" failed to play! (None)`
`09-26 21:33:41 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink4 finished!`
`09-26 21:33:41 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"`
`09-26 21:33:42 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink1`

Here a link to the debug file.
[pulseaudio-dlna_debug.txt](https://www.dropbox.com/s/lk9xwe0zwz8qri6/pulseaudio-dlna_debug.txt?dl=0)

I have tried with Ubuntu 14.04 and 15.04 with the same result.

Any hints?

**Comment by masmu** [comment]
@patufet99 Thanks for the _debug.log_. Your device returns `<errorCode>501</errorCode>` when trying to register the playback stream. That code means `ACTION FAILED`. Sadly, there is no additional information why the action failed.

So, since i am not owning that device the only way i can help you is when you provide a wireshark capture of a working register action. For example _BubbleUPnP_ is a good Android application which hopefully can instruct the device to play. If you could record that data i could look for differences to the current implementation.

**Comment by patufet99** [comment]
Thank you for your feedback. I guess that the DLNA of the Yamaha CRX-N560D has some broken implementation. While AirPlay works flawlessly, I have tested 3 different android applications: iMediaShare, AirWire and AirPinCast to stream audio files to the device, but  all three applications return an error. The 3 applications recongnize the player (as pulseaudio-dlna) but when trying to stream audio an error is returned.

**Comment by masmu** [comment]
I have read about the same errors. But it is always stupid to tell people it is the firmware of your devices which is bugging. Sorry for that. On the other hand, I believe, there is must be an implementation which works. Otherwise they would have never released it (hopefully).

**Comment by patufet99** [comment]
You are right on that. The device has received a certificate as stated [here](http://certification.dlna.org/certs/REG61013683.pdf), so there must be a working implementation. I have tried as you suggested BubbleUPnP but this seems to fail as well. Unfortunately the dlna certification tools seems to be available only to member companies. 
Yamaha provides an Android application to stream to the device, but I do not know if the application uses dlna.

**Comment by patufet99** [comment]
I have tried to use Wireshark to catch the communication between android<->CRX-N560D when using the Yamaha application (Yamaha NP Controller). Unfortunately when using my PC as a WiFi Hotspot it does'nt seem to work, only when I connect the mobile directly to the WiFi router I can stream to the device.
I have then checked with the "GUPnP Universal Control Point" and then I can catch the events when streaming a file to the player with the android application: [GUPnP_Universal_Control_Point_CRX-N560D_events.txt](https://www.dropbox.com/s/leez2qqryfrysmh/GUPnP_Universal_Control_Point_CRX-N560D_events.txt?dl=0).
Perhaps this can give some additional useful indication?

**Comment by masmu** [comment]
I will take a look at this.

In the meantime please try to capture the traffic directly on your phone with _tPacketCapture_. It is a free android application which does not require root.

**Comment by patufet99** [comment]
I have done as you suggested with tPacketCapture. You can get the pcap file [here](https://www.dropbox.com/s/fhnyx8ddg08ki5x/2015_09_28_230312.pcap?dl=0).

**Comment by masmu** [comment]
There is no register action in the dump. Please close every application on the phone and start the application which does the register action first when you started the capture. Do a lot of actions in the application to force a lot of data.

Besides that, please delete the old dump, there seems to be some sensitive information in it. You can link the new dump here or send it via email. That's up to you.

**Comment by patufet99** [comment]
I have removed the ADSL cable, closed the applications on the mobile,
launched tPacketCaptureand, start recording and then launched the "Yamaha
NP Controller". I have then from the Yamaha application turned on the
device, listened to the radio, streamed several musics from the phone,
changed volume, etc. I have then turned off the device and stopped the
recording. I send you here attached the file. There does not seem to be,
however, any exchange with the IP 192.168.1.22 of the device ???

**Comment by patufet99** [comment]
Finally I have found the way to record the communication. My fritz wifi
router allows directly to do that! I just had to browse
http://192.168.1.1/html/capture.html and start to sniff the network
interface eth0 to which the Yamaha is connected.

**Comment by masmu** [comment]
Yeah, FritzBoxes are great! Can do a lot of stuff with them. Waiting for the dump ...

**Comment by patufet99** [comment]
Wasn't it included  in the message?

**Comment by masmu** [comment]
Nope. If you directly respond to github emails attachments get dropped. You find my email in the donation link.

**Comment by patufet99** [comment]
masmu found out that the Yamaha CRX-N560D works with pulseaudio-dlna when the player is set to SERVER mode. Thank you for your help!
