### ISSUE TITLE
Not working with Panasonic 2015 TV

### ISSUE THREAD

**Issue by xoxys** [masmu/pulseaudio-dlna#97]
Hi,
i have problems to get pulseausio-dlna working with my Panasonic TV (CXW684). During the discovery process i got following messages
```
10-01 20:39:34 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Panasonic VIErA" Skipping device ...
10-01 20:39:34 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Panasonic VIErA" Skipping device ...
```
and at the end 
```
10-01 20:39:39 pulseaudio_dlna.listener                       INFO     Discovery complete.
10-01 20:39:40 pulseaudio_dlna.pulseaudio                     INFO     Added the device "50CX680_Series (DLNA)".
```

That looks good, but if i try to play something from firefox to the device i got only an error message 
```
10-01 20:48:45 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Panasonic VIErA" Skipping device ...
10-01 20:48:45 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Panasonic VIErA" Skipping device ...
10-01 20:48:49 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink7"
10-01 20:48:50 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink7
10-01 20:48:50 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "50CX680_Series (DLNA)" to play ...
10-01 20:48:50 pulseaudio_dlna.plugins.upnp.renderer          ERROR    "50CX680_Series" registering failed!
10-01 20:48:50 pulseaudio_dlna.pulseaudio                     ERROR    The device "50CX680_Series (DLNA)" failed to play! (None)
10-01 20:48:50 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink7 finished!
10-01 20:48:50 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink0"
10-01 20:48:51 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0
10-01 20:48:51 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0 finished!
```
Any idea on this problem?

**Comment by masmu** [comment]
It finds your device and tries to instruct it to play the stream which _pulseaudio-dlna_ is serving for that purpose. For the play action you first have to register that stream url. That action failes.

First the simple things:
May it be that you have to accept that via your TVs remote control? Something like: "The computer XXX wants to access this TV. Do you want to proceed?"

If it is not something like this:
The following command will create a _debug.log_ in the current folder. Can you paste it somewhere and link it here?

```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```

**Comment by xoxys** [comment]
There is no option on the TV to accept anything. Also streaming ist working from BubbleUPNP or Android Youtube App to the TV out of the box. So it seems there is no general problem with the TV or the settings. 

Here you can find the Logfile http://pastebin.com/YfpjnY9g

**Comment by masmu** [comment]
Thank you! Could you paste another one? One where you did try to play something on the device? I am interested in the error code the device returns.

Besides that, the highest chance that i can i help you is when i get a _wireshark_ dump of a working session. E.g. between _BubbleUPnP_ and the device. If you own a _FritzBox_ as router this is pretty easy to achieve. But you also can do it with _tPacketCapture_ (free _android_ app, non-root). If you need some further instructions don't hesitate to ask.

**Comment by xoxys** [comment]
No problem :-) Thanks for your help. There is nothing in the logfile i give you? Strange... i tried to stream something. 

Here is another one i hope this one is better http://pastebin.com/EPGbCTd8. tPacketCapture is not working with android 5+  i will try something with tcpdump.

**Comment by masmu** [comment]
Thanks. Error is _705_ `Transport is locked`. Will do some googling later what that means.

If you have the dump until this evening I have something to do :wink:

**Comment by xoxys** [comment]
I think i got it :-)on question is it possible to anonymize a tcp dump file (.cap)?

**Comment by masmu** [comment]
Someone who is caring about privacy in the times of facebook and selfys. I like that :wink: 

From a theoretic point of view: Yes. Its an open format. You can change whatever you like.
From a practical point of view: I am not quite sure. I could imaging that you can drop single packets from a dump with _wireshark_. But best practice is: Record the least amount of data. Close all applications which do not need to run and don't publish your dump here. Instead send it via email. You can find my email address in the donation link.

**Comment by xoxys** [comment]
Of course. Too many peoples dont think about his privacy and in times where data worth much more than money i try to keep it everytime in mind ;-)
You got an email. 

Ps. You are from germany? I asked because you have an *.de mail address?

**Comment by masmu** [comment]
Closed due to magic :wink:
