### ISSUE TITLE
Nexus Player Support

### ISSUE THREAD

**Issue by cmiceli** [masmu/pulseaudio-dlna#98]
Hi!

The Nexus Player doesn't appear to be supported however as far as I know it is the same protocol as the Chromecast, in the case that it isn't I am happy to look at sending you a diff to accept it. Let me know! I have attached the output.

10-01 21:06:50 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
10-01 21:06:50 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.1.4:8080
10-01 21:06:50 pulseaudio_dlna.application                    INFO     Loaded encoders:
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <LameEncoder bit-rate="192" state="True" enabled="True" mime-types="audio/mpeg,audio/mp3">
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <WavEncoder bit-rate="None" state="False" enabled="True" mime-types="audio/wav,audio/x-wav">
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <AacEncoder bit-rate="192" state="False" enabled="True" mime-types="audio/aac,audio/x-aac">
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <FlacEncoder bit-rate="None" state="True" enabled="True" mime-types="audio/flac,audio/x-flac">
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <OggEncoder bit-rate="192" state="False" enabled="True" mime-types="audio/ogg,audio/x-ogg,application/ogg">
10-01 21:06:50 pulseaudio_dlna.application                    INFO     <OpusEncoder bit-rate="192" state="False" enabled="True" mime-types="audio/opus,audio/x-opus">
10-01 21:06:51 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Nexus Player" Skipping device ...
10-01 21:06:51 pulseaudio_dlna.plugins.chromecast.renderer    INFO     The Chromecast seems not to be an original Chromecast! Model name: "Nexus Player" Skipping device ...

**Comment by masmu** [comment]
It high likely that every _google_ device is supported. But since i am just owning a _chromecast_ it did not test them. If you did test it successfully i am very happy to accept it :wink: 

Another guy tested the new _Google Chromecast Audio_ a day ago and added the support for that, so please get a fresh copy of _master_.

**Comment by masmu** [comment]
@cmiceli _bump_

**Comment by masmu** [comment]
@cmiceli Did you try it? This would be very interesting for me.

**Comment by masmu** [comment]
Closed due to inactivity.
